//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginPile.SortingPlugin.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluginPile.SortingPlugin.Properties.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 1 Kanto.
        /// </summary>
        internal static string Gen1Kanto {
            get {
                return ResourceManager.GetString("Gen1Kanto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 2 Johto.
        /// </summary>
        internal static string Gen2Johto {
            get {
                return ResourceManager.GetString("Gen2Johto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 3 Hoenn.
        /// </summary>
        internal static string Gen3Hoenn {
            get {
                return ResourceManager.GetString("Gen3Hoenn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 3 Kanto.
        /// </summary>
        internal static string Gen3Kanto {
            get {
                return ResourceManager.GetString("Gen3Kanto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 4 Johto.
        /// </summary>
        internal static string Gen4Johto {
            get {
                return ResourceManager.GetString("Gen4Johto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 4 Sinnoh Diamond/Pearl.
        /// </summary>
        internal static string Gen4SinnohDiamondPearl {
            get {
                return ResourceManager.GetString("Gen4SinnohDiamondPearl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 4 Sinnoh Platinum.
        /// </summary>
        internal static string Gen4SinnohPlatinum {
            get {
                return ResourceManager.GetString("Gen4SinnohPlatinum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 5 Unova Black 2/White 2.
        /// </summary>
        internal static string Gen5UnovaBlack2White2 {
            get {
                return ResourceManager.GetString("Gen5UnovaBlack2White2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 5 Unova Black/White.
        /// </summary>
        internal static string Gen5UnovaBlackWhite {
            get {
                return ResourceManager.GetString("Gen5UnovaBlackWhite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 6 Hoenn.
        /// </summary>
        internal static string Gen6Hoenn {
            get {
                return ResourceManager.GetString("Gen6Hoenn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 6 Kalos.
        /// </summary>
        internal static string Gen6Kalos {
            get {
                return ResourceManager.GetString("Gen6Kalos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 6 Kalos Areas.
        /// </summary>
        internal static string Gen6KalosAreas {
            get {
                return ResourceManager.GetString("Gen6KalosAreas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Central Kalos.
        /// </summary>
        internal static string Gen6KalosAreasCentralKalos {
            get {
                return ResourceManager.GetString("Gen6KalosAreasCentralKalos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Costal Kalos.
        /// </summary>
        internal static string Gen6KalosAreasCostalKalos {
            get {
                return ResourceManager.GetString("Gen6KalosAreasCostalKalos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mountain Kalos.
        /// </summary>
        internal static string Gen6KalosAreasMountainKalos {
            get {
                return ResourceManager.GetString("Gen6KalosAreasMountainKalos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Akala Island.
        /// </summary>
        internal static string Gen7AlolaIslandsAkala {
            get {
                return ResourceManager.GetString("Gen7AlolaIslandsAkala", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Melemele Island.
        /// </summary>
        internal static string Gen7AlolaIslandsMelemele {
            get {
                return ResourceManager.GetString("Gen7AlolaIslandsMelemele", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Poni Island.
        /// </summary>
        internal static string Gen7AlolaIslandsPoni {
            get {
                return ResourceManager.GetString("Gen7AlolaIslandsPoni", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ula&apos;ula Island.
        /// </summary>
        internal static string Gen7AlolaIslandsUlaula {
            get {
                return ResourceManager.GetString("Gen7AlolaIslandsUlaula", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 7 Alola Sun/Moon.
        /// </summary>
        internal static string Gen7AlolaSunMoon {
            get {
                return ResourceManager.GetString("Gen7AlolaSunMoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 7 Alola Sun/Moon Islands.
        /// </summary>
        internal static string Gen7AlolaSunMoonIslands {
            get {
                return ResourceManager.GetString("Gen7AlolaSunMoonIslands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 7 Alola Ultra Sun/Ultra Moon.
        /// </summary>
        internal static string Gen7AlolaUltraSunUltraMoon {
            get {
                return ResourceManager.GetString("Gen7AlolaUltraSunUltraMoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 7 Alola Ultra Sun/Ultra Moon Islands.
        /// </summary>
        internal static string Gen7AlolaUltraSunUltraMoonIslands {
            get {
                return ResourceManager.GetString("Gen7AlolaUltraSunUltraMoonIslands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 7 Kanto.
        /// </summary>
        internal static string Gen7Kanto {
            get {
                return ResourceManager.GetString("Gen7Kanto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 8 Galar.
        /// </summary>
        internal static string Gen8Galar {
            get {
                return ResourceManager.GetString("Gen8Galar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 8 Galar Areas.
        /// </summary>
        internal static string Gen8GalarAreas {
            get {
                return ResourceManager.GetString("Gen8GalarAreas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Crown Tundra.
        /// </summary>
        internal static string Gen8GalarAreasCrownTundra {
            get {
                return ResourceManager.GetString("Gen8GalarAreasCrownTundra", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Galar.
        /// </summary>
        internal static string Gen8GalarAreasGalar {
            get {
                return ResourceManager.GetString("Gen8GalarAreasGalar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Isle of Armor.
        /// </summary>
        internal static string Gen8GalarAreasIsleofArmor {
            get {
                return ResourceManager.GetString("Gen8GalarAreasIsleofArmor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 8 Hisui.
        /// </summary>
        internal static string Gen8Hisui {
            get {
                return ResourceManager.GetString("Gen8Hisui", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 8 Hisui Areas.
        /// </summary>
        internal static string Gen8HisuiAreas {
            get {
                return ResourceManager.GetString("Gen8HisuiAreas", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alabaster Icelands.
        /// </summary>
        internal static string Gen8HisuiAreasAlabasterIcelands {
            get {
                return ResourceManager.GetString("Gen8HisuiAreasAlabasterIcelands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cobalt Coastlands.
        /// </summary>
        internal static string Gen8HisuiAreasCobaltCoastlands {
            get {
                return ResourceManager.GetString("Gen8HisuiAreasCobaltCoastlands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Coronet Highlands.
        /// </summary>
        internal static string Gen8HisuiAreasCoronetHighlands {
            get {
                return ResourceManager.GetString("Gen8HisuiAreasCoronetHighlands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Crimson Mirelands.
        /// </summary>
        internal static string Gen8HisuiAreasCrimsonMirelands {
            get {
                return ResourceManager.GetString("Gen8HisuiAreasCrimsonMirelands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Obsidian Fieldlands.
        /// </summary>
        internal static string Gen8HisuiAreasObsidianFieldlands {
            get {
                return ResourceManager.GetString("Gen8HisuiAreasObsidianFieldlands", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 8 Sinnoh.
        /// </summary>
        internal static string Gen8Sinnoh {
            get {
                return ResourceManager.GetString("Gen8Sinnoh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gen 9 Paldea.
        /// </summary>
        internal static string Gen9Paldea {
            get {
                return ResourceManager.GetString("Gen9Paldea", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SortBoxesBy.
        /// </summary>
        internal static string MenuItemKey {
            get {
                return ResourceManager.GetString("MenuItemKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sort Boxes By.
        /// </summary>
        internal static string MenuItemName {
            get {
                return ResourceManager.GetString("MenuItemName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to National Pokédex.
        /// </summary>
        internal static string NationalPokédex {
            get {
                return ResourceManager.GetString("NationalPokédex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to National Pokédex (Regional Forms With Generation).
        /// </summary>
        internal static string NationalPokédexRegionalForms {
            get {
                return ResourceManager.GetString("NationalPokédexRegionalForms", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} Regional Pokédex.
        /// </summary>
        internal static string RegionalPokédexTemplate {
            get {
                return ResourceManager.GetString("RegionalPokédexTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
