//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginPile.InsertionPlugin.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluginPile.InsertionPlugin.Properties.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Box Number should be between 1 and {0}.
        /// </summary>
        internal static string BoxNumberRangeError {
            get {
                return ResourceManager.GetString("BoxNumberRangeError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Box {0} Slot {1} is already empty.
        /// </summary>
        internal static string BoxSlotEmptyError {
            get {
                return ResourceManager.GetString("BoxSlotEmptyError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input Error.
        /// </summary>
        internal static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insertion Plugin.
        /// </summary>
        internal static string MenuItemName {
            get {
                return ResourceManager.GetString("MenuItemName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There are no empty slots after Box {0} Slot {1}.
        /// </summary>
        internal static string NoEmptySlotsError {
            get {
                return ResourceManager.GetString("NoEmptySlotsError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Slot Number should be between 1 and {0}.
        /// </summary>
        internal static string SlotNumberRangeError {
            get {
                return ResourceManager.GetString("SlotNumberRangeError", resourceCulture);
            }
        }
    }
}
