using PKHeX.Core;

namespace PluginPile.SortingPlugin {
  class Gen8_Hisui : SortingBase {

    private static readonly Dictionary<SpeciesForm, int> ObsidianFieldlandsDex = new Dictionary<SpeciesForm, int>() {
      {Species.Bidoof, 10},
      {Species.Bibarel, 11},
      {Species.Starly, 12},
      {Species.Staravia, 13},
      {Species.Staraptor, 14},
      {Species.Shinx, 15},
      {Species.Luxio, 16},
      {Species.Luxray, 17},
      {Species.Wurmple, 18},
      {Species.Silcoon, 19},
      {Species.Beautifly, 20},
      {Species.Cascoon, 21},
      {Species.Dustox, 22},
      {Species.Ponyta, 23},
      {Species.Rapidash, 24},
      {Species.Eevee, 25},
      {Species.Vaporeon, 26},
      {Species.Jolteon, 27},
      {Species.Flareon, 28},
      {Species.Espeon, 29},
      {Species.Umbreon, 30},
      {Species.Leafeon, 31},
      {Species.Glaceon, 32},
      {Species.Sylveon, 33},
      {Species.Zubat, 34},
      {Species.Golbat, 35},
      {Species.Crobat, 36},
      {Species.Drifloon, 37},
      {Species.Drifblim, 38},
      {Species.Kricketot, 39},
      {Species.Kricketune, 40},
      {Species.Buizel, 41},
      {Species.Floatzel, 42},
      {(Species.Burmy, 0), 43},
      {(Species.Burmy, 1), 43},
      {(Species.Burmy, 2), 43},
      {(Species.Wormadam, 0), 44},
      {(Species.Wormadam, 1), 44},
      {(Species.Wormadam, 2), 44},
      {(Species.Mothim, 0), 45},
      {(Species.Mothim, 1), 45},
      {(Species.Mothim, 2), 45},
      {Species.Geodude, 46},
      {Species.Graveler, 47},
      {Species.Golem, 48},
      {Species.Stantler, 49},
      {Species.Wyrdeer, 50},
      {Species.Munchlax, 51},
      {Species.Snorlax, 52},
      {Species.Paras, 53},
      {Species.Parasect, 54},
      {Species.Pichu, 55},
      {Species.Pikachu, 56},
      {Species.Raichu, 57},
      {Species.Abra, 58},
      {Species.Kadabra, 59},
      {Species.Alakazam, 60},
      {Species.Chimchar, 61},
      {Species.Monferno, 62},
      {Species.Infernape, 63},
      {Species.Buneary, 64},
      {Species.Lopunny, 65},
      {Species.Cherubi, 66},
      {(Species.Cherrim, 0), 67},
      {(Species.Cherrim, 1), 67},
      {Species.Psyduck, 68},
      {Species.Golduck, 69},
      {Species.Combee, 70},
      {Species.Vespiquen, 71},
      {Species.Scyther, 72},
      {Species.Kleavor, 73},
      {Species.Scizor, 74},
      {Species.Heracross, 75},
      {Species.MimeJr, 76},
      {Species.MrMime, 77},
      {Species.Aipom, 78},
      {Species.Ambipom, 79},
      {Species.Magikarp, 80},
      {Species.Gyarados, 81},
      {(Species.Shellos, 0), 82},
      {(Species.Shellos, 1), 82},
      {(Species.Gastrodon, 0), 83},
      {(Species.Gastrodon, 1), 83},
      {Species.Happiny, 86},
      {Species.Chansey, 87},
      {Species.Blissey, 88},
      {Species.Togepi, 127},
      {Species.Togetic, 128},
      {Species.Togekiss, 129},
      {Species.Machop, 154},
      {Species.Machoke, 155},
      {Species.Machamp, 156},
      {Species.Mesprit, 226},
      {Species.Landorus, 233}
    };

    private static readonly Dictionary<SpeciesForm, int> CrimsonMirelandsDex = new Dictionary<SpeciesForm, int>() {
      {Species.Bidoof, 10},
      {Species.Bibarel, 11},
      {Species.Zubat, 34},
      {Species.Golbat, 35},
      {Species.Crobat, 36},
      {Species.Kricketot, 39},
      {Species.Kricketune, 40},
      {(Species.Burmy, 0), 43},
      {(Species.Burmy, 1), 43},
      {(Species.Burmy, 2), 43},
      {(Species.Wormadam, 0), 44},
      {(Species.Wormadam, 1), 44},
      {(Species.Wormadam, 2), 44},
      {(Species.Mothim, 0), 45},
      {(Species.Mothim, 1), 45},
      {(Species.Mothim, 2), 45},
      {Species.Geodude, 46},
      {Species.Graveler, 47},
      {Species.Golem, 48},
      {Species.Paras, 53},
      {Species.Parasect, 54},
      {Species.Pichu, 55},
      {Species.Pikachu, 56},
      {Species.Raichu, 57},
      {Species.Cherubi, 66},
      {(Species.Cherrim, 0), 67},
      {(Species.Cherrim, 1), 67},
      {Species.Psyduck, 68},
      {Species.Golduck, 69},
      {Species.Combee, 70},
      {Species.Vespiquen, 71},
      {Species.Budew, 89},
      {Species.Roselia, 90},
      {Species.Roserade, 91},
      {Species.Carnivine, 92},
      {Species.Petilil, 93},
      {(Species.Lilligant, 1), 94},
      {Species.Tangela, 95},
      {Species.Tangrowth, 96},
      {Species.Barboach, 97},
      {Species.Whiscash, 98},
      {Species.Croagunk, 99},
      {Species.Toxicroak, 100},
      {Species.Ralts, 101},
      {Species.Kirlia, 102},
      {Species.Gardevoir, 103},
      {Species.Gallade, 104},
      {Species.Yanma, 105},
      {Species.Yanmega, 106},
      {Species.Hippopotas, 107},
      {Species.Hippowdon, 108},
      {Species.Pachirisu, 109},
      {Species.Stunky, 110},
      {Species.Skuntank, 111},
      {Species.Teddiursa, 112},
      {Species.Ursaring, 113},
      {Species.Ursaluna, 114},
      {Species.Goomy, 115},
      {(Species.Sliggoo, 1), 116},
      {(Species.Goodra, 1), 117},
      {Species.Onix, 118},
      {Species.Steelix, 119},
      {Species.Rhyhorn, 120},
      {Species.Rhydon, 121},
      {Species.Rhyperior, 122},
      {Species.Bonsly, 123},
      {Species.Sudowoodo, 124},
      {Species.Lickitung, 125},
      {Species.Lickilicky, 126},
      {Species.Togepi, 127},
      {Species.Togetic, 128},
      {Species.Togekiss, 129},
      {Species.Turtwig, 130},
      {Species.Grotle, 131},
      {Species.Torterra, 132},
      {Species.Gastly, 136},
      {Species.Haunter, 137},
      {Species.Gengar, 138},
      {Species.Murkrow, 140},
      {Species.Honchkrow, 141},
      {Species.Azelf, 227},
      {Species.Enamorus, 234}
    };

    private static readonly Dictionary<SpeciesForm, int> CobaltCoastlandsDex = new Dictionary<SpeciesForm, int>() {
      {Species.Bidoof, 10},
      {Species.Bibarel, 11},
      {Species.Starly, 12},
      {Species.Staravia, 13},
      {Species.Staraptor, 14},
      {Species.Wurmple, 18},
      {Species.Silcoon, 19},
      {Species.Beautifly, 20},
      {Species.Cascoon, 21},
      {Species.Dustox, 22},
      {Species.Eevee, 25},
      {Species.Vaporeon, 26},
      {Species.Jolteon, 27},
      {Species.Flareon, 28},
      {Species.Espeon, 29},
      {Species.Umbreon, 30},
      {Species.Leafeon, 31},
      {Species.Glaceon, 32},
      {Species.Sylveon, 33},
      {Species.Drifloon, 37},
      {Species.Drifblim, 38},
      {Species.Buizel, 41},
      {Species.Floatzel, 42},
      {(Species.Burmy, 0), 43},
      {(Species.Burmy, 1), 43},
      {(Species.Burmy, 2), 43},
      {(Species.Wormadam, 0), 44},
      {(Species.Wormadam, 1), 44},
      {(Species.Wormadam, 2), 44},
      {(Species.Mothim, 0), 45},
      {(Species.Mothim, 1), 45},
      {(Species.Mothim, 2), 45},
      {Species.Geodude, 46},
      {Species.Graveler, 47},
      {Species.Golem, 48},
      {Species.Stantler, 49},
      {Species.Wyrdeer, 50},
      {Species.Paras, 53},
      {Species.Parasect, 54},
      {Species.Pichu, 55},
      {Species.Pikachu, 56},
      {Species.Raichu, 57},
      {Species.Psyduck, 68},
      {Species.Golduck, 69},
      {Species.Combee, 70},
      {Species.Vespiquen, 71},
      {Species.Aipom, 78},
      {Species.Ambipom, 79},
      {Species.Magikarp, 80},
      {Species.Gyarados, 81},
      {(Species.Shellos, 0), 82},
      {(Species.Shellos, 1), 82},
      {(Species.Gastrodon, 0), 83},
      {(Species.Gastrodon, 1), 83},
      {(Species.Qwilfish, 1), 84},
      {Species.Overqwil, 85},
      {Species.Happiny, 86},
      {Species.Chansey, 87},
      {Species.Blissey, 88},
      {Species.Tangela, 95},
      {Species.Tangrowth, 96},
      {Species.Croagunk, 99},
      {Species.Toxicroak, 100},
      {Species.Togepi, 127},
      {Species.Togetic, 128},
      {Species.Togekiss, 129},
      {Species.Murkrow, 140},
      {Species.Honchkrow, 141},
      {Species.Spheal, 143},
      {Species.Sealeo, 144},
      {Species.Walrein, 145},
      {Species.Remoraid, 146},
      {Species.Octillery, 147},
      {Species.Skorupi, 148},
      {Species.Drapion, 149},
      {(Species.Growlithe, 1), 150},
      {(Species.Arcanine, 1), 151},
      {Species.Glameow, 152},
      {Species.Purugly, 153},
      {Species.Machop, 154},
      {Species.Machoke, 155},
      {Species.Machamp, 156},
      {Species.Chatot, 157},
      {Species.Duskull, 158},
      {Species.Dusclops, 159},
      {Species.Dusknoir, 160},
      {Species.Piplup, 161},
      {Species.Prinplup, 162},
      {Species.Empoleon, 163},
      {Species.Mantyke, 164},
      {Species.Mantine, 165},
      {(Species.Basculin, 2), 166},
      {Species.Basculegion, 167},
      {Species.Vulpix, 168},
      {Species.Ninetales, 169},
      {Species.Tentacool, 170},
      {Species.Tentacruel, 171},
      {Species.Finneon, 172},
      {Species.Lumineon, 173},
      {Species.Magby, 174},
      {Species.Magmar, 175},
      {Species.Magmortar, 176},
      {Species.Heatran, 228},
      {Species.Thundurus, 232}
    };

    private static readonly Dictionary<SpeciesForm, int> CoronetHighlandsDex = new Dictionary<SpeciesForm, int>() {
      {Species.Shinx, 15},
      {Species.Luxio, 16},
      {Species.Luxray, 17},
      {Species.Zubat, 34},
      {Species.Golbat, 35},
      {Species.Crobat, 36},
      {(Species.Burmy, 0), 43},
      {(Species.Burmy, 1), 43},
      {(Species.Burmy, 2), 43},
      {(Species.Wormadam, 0), 44},
      {(Species.Wormadam, 1), 44},
      {(Species.Wormadam, 2), 44},
      {(Species.Mothim, 0), 45},
      {(Species.Mothim, 1), 45},
      {(Species.Mothim, 2), 45},
      {Species.Geodude, 46},
      {Species.Graveler, 47},
      {Species.Golem, 48},
      {Species.Stantler, 49},
      {Species.Wyrdeer, 50},
      {Species.Paras, 53},
      {Species.Parasect, 54},
      {Species.Cherubi, 66},
      {(Species.Cherrim, 0), 67},
      {(Species.Cherrim, 1), 67},
      {Species.Psyduck, 68},
      {Species.Golduck, 69},
      {Species.Scyther, 72},
      {Species.Kleavor, 73},
      {Species.Scizor, 74},
      {Species.Heracross, 75},
      {Species.Magikarp, 80},
      {Species.Gyarados, 81},
      {Species.Budew, 89},
      {Species.Roselia, 90},
      {Species.Roserade, 91},
      {Species.Carnivine, 92},
      {Species.Barboach, 97},
      {Species.Whiscash, 98},
      {Species.Croagunk, 99},
      {Species.Toxicroak, 100},
      {Species.Yanma, 105},
      {Species.Yanmega, 106},
      {Species.Hippopotas, 107},
      {Species.Hippowdon, 108},
      {Species.Stunky, 110},
      {Species.Skuntank, 111},
      {Species.Teddiursa, 112},
      {Species.Ursaring, 113},
      {Species.Ursaluna, 114},
      {Species.Goomy, 115},
      {(Species.Sliggoo, 1), 116},
      {(Species.Goodra, 1), 117},
      {Species.Onix, 118},
      {Species.Steelix, 119},
      {Species.Rhyhorn, 120},
      {Species.Rhydon, 121},
      {Species.Rhyperior, 122},
      {Species.Bonsly, 123},
      {Species.Sudowoodo, 124},
      {Species.Gastly, 136},
      {Species.Haunter, 137},
      {Species.Gengar, 138},
      {Species.Machop, 154},
      {Species.Machoke, 155},
      {Species.Machamp, 156},
      {(Species.Basculin, 2), 166},
      {Species.Basculegion, 167},
      {Species.Magnemite, 177},
      {Species.Magneton, 178},
      {Species.Magnezone, 179},
      {Species.Bronzor, 180},
      {Species.Bronzong, 181},
      {Species.Elekid, 182},
      {Species.Electabuzz, 183},
      {Species.Electivire, 184},
      {Species.Gligar, 185},
      {Species.Gliscor, 186},
      {Species.Gible, 187},
      {Species.Gabite, 188},
      {Species.Garchomp, 189},
      {Species.Nosepass, 190},
      {Species.Probopass, 191},
      {(Species.Voltorb, 1), 192},
      {(Species.Electrode, 1), 193},
      {(Species.Rotom, 0), 194},
      {(Species.Rotom, 1), 194},
      {(Species.Rotom, 2), 194},
      {(Species.Rotom, 3), 194},
      {(Species.Rotom, 4), 194},
      {(Species.Rotom, 5), 194},
      {Species.Chingling, 195},
      {Species.Chimecho, 196},
      {Species.Misdreavus, 197},
      {Species.Mismagius, 198},
      {Species.Cleffa, 199},
      {Species.Clefairy, 200},
      {Species.Clefable, 201},
      {(Species.Sneasel, 1), 202},
      {(Species.Sneasel, 0), 202},
      {Species.Sneasler, 203},
      {Species.Weavile, 204},
      {Species.Cresselia, 230}
    };

    private static readonly Dictionary<SpeciesForm, int> AlabasterIcelandsDex = new Dictionary<SpeciesForm, int>() {
      {Species.Bidoof, 10},
      {Species.Bibarel, 11},
      {Species.Eevee, 25},
      {Species.Vaporeon, 26},
      {Species.Jolteon, 27},
      {Species.Flareon, 28},
      {Species.Espeon, 29},
      {Species.Umbreon, 30},
      {Species.Leafeon, 31},
      {Species.Glaceon, 32},
      {Species.Sylveon, 33},
      {Species.Zubat, 34},
      {Species.Golbat, 35},
      {Species.Crobat, 36},
      {Species.Drifloon, 37},
      {Species.Drifblim, 38},
      {(Species.Burmy, 0), 43},
      {(Species.Burmy, 1), 43},
      {(Species.Burmy, 2), 43},
      {(Species.Wormadam, 0), 44},
      {(Species.Wormadam, 1), 44},
      {(Species.Wormadam, 2), 44},
      {(Species.Mothim, 0), 45},
      {(Species.Mothim, 1), 45},
      {(Species.Mothim, 2), 45},
      {Species.Geodude, 46},
      {Species.Graveler, 47},
      {Species.Golem, 48},
      {Species.Stantler, 49},
      {Species.Wyrdeer, 50},
      {Species.Munchlax, 51},
      {Species.Snorlax, 52},
      {Species.Abra, 58},
      {Species.Kadabra, 59},
      {Species.Alakazam, 60},
      {Species.Buneary, 64},
      {Species.Lopunny, 65},
      {Species.Aipom, 78},
      {Species.Ambipom, 79},
      {Species.Happiny, 86},
      {Species.Chansey, 87},
      {Species.Blissey, 88},
      {Species.Ralts, 101},
      {Species.Kirlia, 102},
      {Species.Gardevoir, 103},
      {Species.Gallade, 104},
      {Species.Lickitung, 125},
      {Species.Lickilicky, 126},
      {Species.Gastly, 136},
      {Species.Haunter, 137},
      {Species.Gengar, 138},
      {Species.Glameow, 152},
      {Species.Purugly, 153},
      {Species.Machop, 154},
      {Species.Machoke, 155},
      {Species.Machamp, 156},
      {Species.Duskull, 158},
      {Species.Dusclops, 159},
      {Species.Dusknoir, 160},
      {(Species.Basculin, 2), 166},
      {Species.Basculegion, 167},
      {Species.Bronzor, 180},
      {Species.Bronzong, 181},
      {Species.Elekid, 182},
      {Species.Electabuzz, 183},
      {Species.Electivire, 184},
      {Species.Gligar, 185},
      {Species.Gliscor, 186},
      {Species.Gible, 187},
      {Species.Gabite, 188},
      {Species.Garchomp, 189},
      {Species.Chingling, 195},
      {Species.Chimecho, 196},
      {Species.Misdreavus, 197},
      {Species.Mismagius, 198},
      {(Species.Sneasel, 1), 202},
      {(Species.Sneasel, 0), 202},
      {Species.Sneasler, 203},
      {Species.Weavile, 204},
      {Species.Snorunt, 205},
      {Species.Glalie, 206},
      {Species.Froslass, 207},
      {Species.Swinub, 212},
      {Species.Piloswine, 213},
      {Species.Mamoswine, 214},
      {Species.Bergmite, 215},
      {(Species.Avalugg, 1), 216},
      {Species.Snover, 217},
      {Species.Abomasnow, 218},
      {(Species.Zorua, 1), 219},
      {(Species.Zoroark, 1), 220},
      {Species.Rufflet, 221},
      {(Species.Braviary, 1), 222},
      {Species.Riolu, 223},
      {Species.Lucario, 224},
      {Species.Uxie, 225},
      {Species.Regigigas, 229},
      {Species.Tornadus, 231}
    };

    private static readonly Dictionary<SpeciesForm, int> dex = new Dictionary<SpeciesForm, int>() {
      {Species.Rowlet, 1},
      {Species.Dartrix, 2},
      {(Species.Decidueye, 1), 3},
      {Species.Cyndaquil, 4},
      {Species.Quilava, 5},
      {(Species.Typhlosion, 1), 6},
      {Species.Oshawott, 7},
      {Species.Dewott, 8},
      {(Species.Samurott, 1), 9},
      {Species.Bidoof, 10},
      {Species.Bibarel, 11},
      {Species.Starly, 12},
      {Species.Staravia, 13},
      {Species.Staraptor, 14},
      {Species.Shinx, 15},
      {Species.Luxio, 16},
      {Species.Luxray, 17},
      {Species.Wurmple, 18},
      {Species.Silcoon, 19},
      {Species.Beautifly, 20},
      {Species.Cascoon, 21},
      {Species.Dustox, 22},
      {Species.Ponyta, 23},
      {Species.Rapidash, 24},
      {Species.Eevee, 25},
      {Species.Vaporeon, 26},
      {Species.Jolteon, 27},
      {Species.Flareon, 28},
      {Species.Espeon, 29},
      {Species.Umbreon, 30},
      {Species.Leafeon, 31},
      {Species.Glaceon, 32},
      {Species.Sylveon, 33},
      {Species.Zubat, 34},
      {Species.Golbat, 35},
      {Species.Crobat, 36},
      {Species.Drifloon, 37},
      {Species.Drifblim, 38},
      {Species.Kricketot, 39},
      {Species.Kricketune, 40},
      {Species.Buizel, 41},
      {Species.Floatzel, 42},
      {(Species.Burmy, 0), 43},
      {(Species.Burmy, 1), 43},
      {(Species.Burmy, 2), 43},
      {(Species.Wormadam, 0), 44},
      {(Species.Wormadam, 1), 44},
      {(Species.Wormadam, 2), 44},
      {(Species.Mothim, 0), 45},
      {(Species.Mothim, 1), 45},
      {(Species.Mothim, 2), 45},
      {Species.Geodude, 46},
      {Species.Graveler, 47},
      {Species.Golem, 48},
      {Species.Stantler, 49},
      {Species.Wyrdeer, 50},
      {Species.Munchlax, 51},
      {Species.Snorlax, 52},
      {Species.Paras, 53},
      {Species.Parasect, 54},
      {Species.Pichu, 55},
      {Species.Pikachu, 56},
      {Species.Raichu, 57},
      {Species.Abra, 58},
      {Species.Kadabra, 59},
      {Species.Alakazam, 60},
      {Species.Chimchar, 61},
      {Species.Monferno, 62},
      {Species.Infernape, 63},
      {Species.Buneary, 64},
      {Species.Lopunny, 65},
      {Species.Cherubi, 66},
      {(Species.Cherrim, 0), 67},
      {(Species.Cherrim, 1), 67},
      {Species.Psyduck, 68},
      {Species.Golduck, 69},
      {Species.Combee, 70},
      {Species.Vespiquen, 71},
      {Species.Scyther, 72},
      {Species.Kleavor, 73},
      {Species.Scizor, 74},
      {Species.Heracross, 75},
      {Species.MimeJr, 76},
      {Species.MrMime, 77},
      {Species.Aipom, 78},
      {Species.Ambipom, 79},
      {Species.Magikarp, 80},
      {Species.Gyarados, 81},
      {(Species.Shellos, 0), 82},
      {(Species.Shellos, 1), 82},
      {(Species.Gastrodon, 0), 83},
      {(Species.Gastrodon, 1), 83},
      {(Species.Qwilfish, 1), 84},
      {Species.Overqwil, 85},
      {Species.Happiny, 86},
      {Species.Chansey, 87},
      {Species.Blissey, 88},
      {Species.Budew, 89},
      {Species.Roselia, 90},
      {Species.Roserade, 91},
      {Species.Carnivine, 92},
      {Species.Petilil, 93},
      {(Species.Lilligant, 1), 94},
      {Species.Tangela, 95},
      {Species.Tangrowth, 96},
      {Species.Barboach, 97},
      {Species.Whiscash, 98},
      {Species.Croagunk, 99},
      {Species.Toxicroak, 100},
      {Species.Ralts, 101},
      {Species.Kirlia, 102},
      {Species.Gardevoir, 103},
      {Species.Gallade, 104},
      {Species.Yanma, 105},
      {Species.Yanmega, 106},
      {Species.Hippopotas, 107},
      {Species.Hippowdon, 108},
      {Species.Pachirisu, 109},
      {Species.Stunky, 110},
      {Species.Skuntank, 111},
      {Species.Teddiursa, 112},
      {Species.Ursaring, 113},
      {Species.Ursaluna, 114},
      {Species.Goomy, 115},
      {(Species.Sliggoo, 1), 116},
      {(Species.Goodra, 1), 117},
      {Species.Onix, 118},
      {Species.Steelix, 119},
      {Species.Rhyhorn, 120},
      {Species.Rhydon, 121},
      {Species.Rhyperior, 122},
      {Species.Bonsly, 123},
      {Species.Sudowoodo, 124},
      {Species.Lickitung, 125},
      {Species.Lickilicky, 126},
      {Species.Togepi, 127},
      {Species.Togetic, 128},
      {Species.Togekiss, 129},
      {Species.Turtwig, 130},
      {Species.Grotle, 131},
      {Species.Torterra, 132},
      {Species.Porygon, 133},
      {Species.Porygon2, 134},
      {Species.PorygonZ, 135},
      {Species.Gastly, 136},
      {Species.Haunter, 137},
      {Species.Gengar, 138},
      {Species.Spiritomb, 139},
      {Species.Murkrow, 140},
      {Species.Honchkrow, 141},
      {(Species.Unown, 0), 142},
      {(Species.Unown, 1), 142},
      {(Species.Unown, 2), 142},
      {(Species.Unown, 3), 142},
      {(Species.Unown, 4), 142},
      {(Species.Unown, 5), 142},
      {(Species.Unown, 6), 142},
      {(Species.Unown, 7), 142},
      {(Species.Unown, 8), 142},
      {(Species.Unown, 9), 142},
      {(Species.Unown, 10), 142},
      {(Species.Unown, 11), 142},
      {(Species.Unown, 12), 142},
      {(Species.Unown, 13), 142},
      {(Species.Unown, 14), 142},
      {(Species.Unown, 15), 142},
      {(Species.Unown, 16), 142},
      {(Species.Unown, 17), 142},
      {(Species.Unown, 18), 142},
      {(Species.Unown, 19), 142},
      {(Species.Unown, 20), 142},
      {(Species.Unown, 21), 142},
      {(Species.Unown, 22), 142},
      {(Species.Unown, 23), 142},
      {(Species.Unown, 24), 142},
      {(Species.Unown, 25), 142},
      {(Species.Unown, 26), 142},
      {(Species.Unown, 27), 142},
      {Species.Spheal, 143},
      {Species.Sealeo, 144},
      {Species.Walrein, 145},
      {Species.Remoraid, 146},
      {Species.Octillery, 147},
      {Species.Skorupi, 148},
      {Species.Drapion, 149},
      {(Species.Growlithe, 1), 150},
      {(Species.Arcanine, 1), 151},
      {Species.Glameow, 152},
      {Species.Purugly, 153},
      {Species.Machop, 154},
      {Species.Machoke, 155},
      {Species.Machamp, 156},
      {Species.Chatot, 157},
      {Species.Duskull, 158},
      {Species.Dusclops, 159},
      {Species.Dusknoir, 160},
      {Species.Piplup, 161},
      {Species.Prinplup, 162},
      {Species.Empoleon, 163},
      {Species.Mantyke, 164},
      {Species.Mantine, 165},
      {(Species.Basculin, 2), 166},
      {Species.Basculegion, 167},
      {(Species.Vulpix, 0), 168},
      {(Species.Vulpix, 1), 168},
      {(Species.Ninetales, 0), 169},
      {(Species.Ninetales, 1), 169},
      {Species.Tentacool, 170},
      {Species.Tentacruel, 171},
      {Species.Finneon, 172},
      {Species.Lumineon, 173},
      {Species.Magby, 174},
      {Species.Magmar, 175},
      {Species.Magmortar, 176},
      {Species.Magnemite, 177},
      {Species.Magneton, 178},
      {Species.Magnezone, 179},
      {Species.Bronzor, 180},
      {Species.Bronzong, 181},
      {Species.Elekid, 182},
      {Species.Electabuzz, 183},
      {Species.Electivire, 184},
      {Species.Gligar, 185},
      {Species.Gliscor, 186},
      {Species.Gible, 187},
      {Species.Gabite, 188},
      {Species.Garchomp, 189},
      {Species.Nosepass, 190},
      {Species.Probopass, 191},
      {(Species.Voltorb, 1), 192},
      {(Species.Electrode, 1), 193},
      {(Species.Rotom, 0), 194},
      {(Species.Rotom, 1), 194},
      {(Species.Rotom, 2), 194},
      {(Species.Rotom, 3), 194},
      {(Species.Rotom, 4), 194},
      {(Species.Rotom, 5), 194},
      {Species.Chingling, 195},
      {Species.Chimecho, 196},
      {Species.Misdreavus, 197},
      {Species.Mismagius, 198},
      {Species.Cleffa, 199},
      {Species.Clefairy, 200},
      {Species.Clefable, 201},
      {(Species.Sneasel, 1), 202},
      {(Species.Sneasel, 0), 202},
      {Species.Sneasler, 203},
      {Species.Weavile, 204},
      {Species.Snorunt, 205},
      {Species.Glalie, 206},
      {Species.Froslass, 207},
      {Species.Cranidos, 208},
      {Species.Rampardos, 209},
      {Species.Shieldon, 210},
      {Species.Bastiodon, 211},
      {Species.Swinub, 212},
      {Species.Piloswine, 213},
      {Species.Mamoswine, 214},
      {Species.Bergmite, 215},
      {(Species.Avalugg, 1), 216},
      {Species.Snover, 217},
      {Species.Abomasnow, 218},
      {(Species.Zorua, 1), 219},
      {(Species.Zoroark, 1), 220},
      {Species.Rufflet, 221},
      {(Species.Braviary, 1), 222},
      {Species.Riolu, 223},
      {Species.Lucario, 224},
      {Species.Uxie, 225},
      {Species.Mesprit, 226},
      {Species.Azelf, 227},
      {Species.Heatran, 228},
      {Species.Regigigas, 229},
      {Species.Cresselia, 230},
      {(Species.Tornadus, 0), 231},
      {(Species.Tornadus, 1), 231},
      {(Species.Thundurus, 0), 232},
      {(Species.Thundurus, 1), 232},
      {(Species.Landorus, 0), 233},
      {(Species.Landorus, 1), 233},
      {(Species.Enamorus, 0), 234},
      {(Species.Enamorus, 1), 234},
      {(Species.Dialga, 0), 235},
      {(Species.Dialga, 1), 235},
      {(Species.Palkia, 0), 236},
      {(Species.Palkia, 1), 236},
      {(Species.Giratina, 0), 237},
      {(Species.Giratina, 1), 237},
      {(Species.Arceus, 0), 238},
      {(Species.Arceus, 1), 238},
      {(Species.Arceus, 2), 238},
      {(Species.Arceus, 3), 238},
      {(Species.Arceus, 4), 238},
      {(Species.Arceus, 5), 238},
      {(Species.Arceus, 6), 238},
      {(Species.Arceus, 7), 238},
      {(Species.Arceus, 8), 238},
      {(Species.Arceus, 9), 238},
      {(Species.Arceus, 10), 238},
      {(Species.Arceus, 11), 238},
      {(Species.Arceus, 12), 238},
      {(Species.Arceus, 13), 238},
      {(Species.Arceus, 14), 238},
      {(Species.Arceus, 15), 238},
      {(Species.Arceus, 16), 238},
      {(Species.Arceus, 17), 238},
      {(Species.Arceus, 18), 238},
      {Species.Phione, 239},
      {Species.Manaphy, 240},
      {(Species.Shaymin, 0), 241},
      {(Species.Shaymin, 1), 241},
      {Species.Darkrai, 242}
    };

    public static Func<PKM, IComparable>[] GetObsidianFieldlandsSortFunctions() {
      return GenerateSortingFunctions(ObsidianFieldlandsDex);
    }

    public static Func<PKM, IComparable>[] GetCrimsonMirelandsSortFunctions() {
      return GenerateSortingFunctions(CrimsonMirelandsDex);
    }

    public static Func<PKM, IComparable>[] GetCobaltCoastlandsSortFunctions() {
      return GenerateSortingFunctions(CobaltCoastlandsDex);
    }

    public static Func<PKM, IComparable>[] GetCoronetHighlandsSortFunctions() {
      return GenerateSortingFunctions(CoronetHighlandsDex);
    }

    public static Func<PKM, IComparable>[] GetAlabasterIcelandsSortFunctions() {
      return GenerateSortingFunctions(AlabasterIcelandsDex);
    }

    public static Func<PKM, IComparable>[] GetSortFunctions() {
      return GenerateSortingFunctions(dex);
    }

  }
}
