//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginPile.SortingPlugin {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class PluginSettings : global::System.Configuration.ApplicationSettingsBase {

        private static PluginSettings defaultInstance = ((PluginSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PluginSettings())));

        public static PluginSettings Default {
            get {
                return defaultInstance;
            }
        }

        /// <summary>
        /// Show the individual area Pokedéxes for those that have it.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Show the individual area Pokedéxes for those that have it.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowIndividualPokedéxes {
            get {
                return ((bool)(this["ShowIndividualPokedéxes"]));
            }
            set {
                this["ShowIndividualPokedéxes"] = value;
            }
        }

        /// <summary>
        /// The box to begin sorting from.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The box to begin sorting from.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SortBeginBox {
            get {
                return ((int)(this["SortBeginBox"]));
            }
            set {
                this["SortBeginBox"] = value;
            }
        }

        /// <summary>
        /// The box to ending sorting in.  -1 can be used to specify the last box.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The box to ending sorting in.  -1 can be used to specify the last box.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int SortEndBox {
            get {
                return ((int)(this["SortEndBox"]));
            }
            set {
                this["SortEndBox"] = value;
            }
        }
    }
}
