using PKHeX.Core;

namespace PluginPile.Sorting;
internal class Gen4Sinnoh : SortingBase {

  private static readonly Dictionary<Species, PositionForms> DPDex = new Dictionary<Species, PositionForms>(){
    {Species.Turtwig, 1},
    {Species.Grotle, 2},
    {Species.Torterra, 3},
    {Species.Chimchar, 4},
    {Species.Monferno, 5},
    {Species.Infernape, 6},
    {Species.Piplup, 7},
    {Species.Prinplup, 8},
    {Species.Empoleon, 9},
    {Species.Starly, 10},
    {Species.Staravia, 11},
    {Species.Staraptor, 12},
    {Species.Bidoof, 13},
    {Species.Bibarel, 14},
    {Species.Kricketot, 15},
    {Species.Kricketune, 16},
    {Species.Shinx, 17},
    {Species.Luxio, 18},
    {Species.Luxray, 19},
    {Species.Abra, 20},
    {Species.Kadabra, 21},
    {Species.Alakazam, 22},
    {Species.Magikarp, 23},
    {Species.Gyarados, 24},
    {Species.Budew, 25},
    {Species.Roselia, 26},
    {Species.Roserade, 27},
    {Species.Zubat, 28},
    {Species.Golbat, 29},
    {Species.Crobat, 30},
    {Species.Geodude, 31},
    {Species.Graveler, 32},
    {Species.Golem, 33},
    {Species.Onix, 34},
    {Species.Steelix, 35},
    {Species.Cranidos, 36},
    {Species.Rampardos, 37},
    {Species.Shieldon, 38},
    {Species.Bastiodon, 39},
    {Species.Machop, 40},
    {Species.Machoke, 41},
    {Species.Machamp, 42},
    {Species.Psyduck, 43},
    {Species.Golduck, 44},
    {Species.Burmy, (45, 0..2)},
    {Species.Wormadam, (46, 0..2)},
    {Species.Mothim, (47, 0..2)},
    {Species.Wurmple, 48},
    {Species.Silcoon, 49},
    {Species.Beautifly, 50},
    {Species.Cascoon, 51},
    {Species.Dustox, 52},
    {Species.Combee, 53},
    {Species.Vespiquen, 54},
    {Species.Pachirisu, 55},
    {Species.Buizel, 56},
    {Species.Floatzel, 57},
    {Species.Cherubi, 58},
    {Species.Cherrim, (59, 0..1)},
    {Species.Shellos, (60, 0..1)},
    {Species.Gastrodon, (61, 0..1)},
    {Species.Heracross, 62},
    {Species.Aipom, 63},
    {Species.Ambipom, 64},
    {Species.Drifloon, 65},
    {Species.Drifblim, 66},
    {Species.Buneary, 67},
    {Species.Lopunny, 68},
    {Species.Gastly, 69},
    {Species.Haunter, 70},
    {Species.Gengar, 71},
    {Species.Misdreavus, 72},
    {Species.Mismagius, 73},
    {Species.Murkrow, 74},
    {Species.Honchkrow, 75},
    {Species.Glameow, 76},
    {Species.Purugly, 77},
    {Species.Goldeen, 78},
    {Species.Seaking, 79},
    {Species.Barboach, 80},
    {Species.Whiscash, 81},
    {Species.Chingling, 82},
    {Species.Chimecho, 83},
    {Species.Stunky, 84},
    {Species.Skuntank, 85},
    {Species.Meditite, 86},
    {Species.Medicham, 87},
    {Species.Bronzor, 88},
    {Species.Bronzong, 89},
    {Species.Ponyta, 90},
    {Species.Rapidash, 91},
    {Species.Bonsly, 92},
    {Species.Sudowoodo, 93},
    {Species.MimeJr, 94},
    {Species.MrMime, 95},
    {Species.Happiny, 96},
    {Species.Chansey, 97},
    {Species.Blissey, 98},
    {Species.Cleffa, 99},
    {Species.Clefairy, 100},
    {Species.Clefable, 101},
    {Species.Chatot, 102},
    {Species.Pichu, 103},
    {Species.Pikachu, 104},
    {Species.Raichu, 105},
    {Species.Hoothoot, 106},
    {Species.Noctowl, 107},
    {Species.Spiritomb, 108},
    {Species.Gible, 109},
    {Species.Gabite, 110},
    {Species.Garchomp, 111},
    {Species.Munchlax, 112},
    {Species.Snorlax, 113},
    {Species.Unown, 114},
    {Species.Riolu, 115},
    {Species.Lucario, 116},
    {Species.Wooper, 117},
    {Species.Quagsire, 118},
    {Species.Wingull, 119},
    {Species.Pelipper, 120},
    {Species.Girafarig, 121},
    {Species.Hippopotas, 122},
    {Species.Hippowdon, 123},
    {Species.Azurill, 124},
    {Species.Marill, 125},
    {Species.Azumarill, 126},
    {Species.Skorupi, 127},
    {Species.Drapion, 128},
    {Species.Croagunk, 129},
    {Species.Toxicroak, 130},
    {Species.Carnivine, 131},
    {Species.Remoraid, 132},
    {Species.Octillery, 133},
    {Species.Finneon, 134},
    {Species.Lumineon, 135},
    {Species.Tentacool, 136},
    {Species.Tentacruel, 137},
    {Species.Feebas, 138},
    {Species.Milotic, 139},
    {Species.Mantyke, 140},
    {Species.Mantine, 141},
    {Species.Snover, 142},
    {Species.Abomasnow, 143},
    {Species.Sneasel, 144},
    {Species.Weavile, 145},
    {Species.Uxie, 146},
    {Species.Mesprit, 147},
    {Species.Azelf, 148},
    {Species.Dialga, 149},
    {Species.Palkia, 150},
    {Species.Manaphy, 151},
  };

  private static readonly Dictionary<Species, PositionForms> Ptdex = new Dictionary<Species, PositionForms>(DPDex) {
    {Species.Rotom, (152, 0..5)},
    {Species.Gligar, 153},
    {Species.Gliscor, 154},
    {Species.Nosepass, 155},
    {Species.Probopass, 156},
    {Species.Ralts, 157},
    {Species.Kirlia, 158},
    {Species.Gardevoir, 159},
    {Species.Gallade, 160},
    {Species.Lickitung, 161},
    {Species.Lickilicky, 162},
    {Species.Eevee, 163},
    {Species.Vaporeon, 164},
    {Species.Jolteon, 165},
    {Species.Flareon, 166},
    {Species.Espeon, 167},
    {Species.Umbreon, 168},
    {Species.Leafeon, 169},
    {Species.Glaceon, 170},
    {Species.Swablu, 171},
    {Species.Altaria, 172},
    {Species.Togepi, 173},
    {Species.Togetic, 174},
    {Species.Togekiss, 175},
    {Species.Houndour, 176},
    {Species.Houndoom, 177},
    {Species.Magnemite, 178},
    {Species.Magneton, 179},
    {Species.Magnezone, 180},
    {Species.Tangela, 181},
    {Species.Tangrowth, 182},
    {Species.Yanma, 183},
    {Species.Yanmega, 184},
    {Species.Tropius, 185},
    {Species.Rhyhorn, 186},
    {Species.Rhydon, 187},
    {Species.Rhyperior, 188},
    {Species.Duskull, 189},
    {Species.Dusclops, 190},
    {Species.Dusknoir, 191},
    {Species.Porygon, 192},
    {Species.Porygon2, 193},
    {Species.PorygonZ, 194},
    {Species.Scyther, 195},
    {Species.Scizor, 196},
    {Species.Elekid, 197},
    {Species.Electabuzz, 198},
    {Species.Electivire, 199},
    {Species.Magby, 200},
    {Species.Magmar, 201},
    {Species.Magmortar, 202},
    {Species.Swinub, 203},
    {Species.Piloswine, 204},
    {Species.Mamoswine, 205},
    {Species.Snorunt, 206},
    {Species.Glalie, 207},
    {Species.Froslass, 208},
    {Species.Absol, 209},
    {Species.Giratina, (210, 0..1)},
  };

  public static Func<PKM, IComparable>[] GetDPSortFunctions() {
    return GenerateSortingFunctions(DPDex);
  }

  public static Func<PKM, IComparable>[] GetPtSortFunctions() {
    return GenerateSortingFunctions(Ptdex);
  }

}
