using PKHeX.Core;

namespace PluginPile.Sorting;
internal class Gen7Alola : SortingBase {

  private static readonly Dictionary<Species, PositionForms> SMFullDex = new Dictionary<Species, PositionForms>() {
    {Species.Rowlet, 1},
    {Species.Dartrix, 2},
    {Species.Decidueye, 3},
    {Species.Litten, 4},
    {Species.Torracat, 5},
    {Species.Incineroar, 6},
    {Species.Popplio, 7},
    {Species.Brionne, 8},
    {Species.Primarina, 9},
    {Species.Pikipek, 10},
    {Species.Trumbeak, 11},
    {Species.Toucannon, 12},
    {Species.Yungoos, 13},
    {Species.Gumshoos, 14},
    {Species.Rattata, 15},
    {Species.Raticate, 16},
    {Species.Caterpie, 17},
    {Species.Metapod, 18},
    {Species.Butterfree, 19},
    {Species.Ledyba, 20},
    {Species.Ledian, 21},
    {Species.Spinarak, 22},
    {Species.Ariados, 23},
    {Species.Pichu, 24},
    {Species.Pikachu, 25},
    {Species.Raichu, (26, 1)},
    {Species.Grubbin, 27},
    {Species.Charjabug, 28},
    {Species.Vikavolt, 29},
    {Species.Bonsly, 30},
    {Species.Sudowoodo, 31},
    {Species.Happiny, 32},
    {Species.Chansey, 33},
    {Species.Blissey, 34},
    {Species.Munchlax, 35},
    {Species.Snorlax, 36},
    {Species.Slowpoke, 37},
    {Species.Slowbro, 38},
    {Species.Slowking, 39},
    {Species.Wingull, 40},
    {Species.Pelipper, 41},
    {Species.Abra, 42},
    {Species.Kadabra, 43},
    {Species.Alakazam, 44},
    {Species.Meowth, (45, 1)},
    {Species.Persian, (46, 1)},
    {Species.Magnemite, 47},
    {Species.Magneton, 48},
    {Species.Magnezone, 49},
    {Species.Grimer, (50, 1)},
    {Species.Muk, (51, 1)},
    {Species.Growlithe, 52},
    {Species.Arcanine, 53},
    {Species.Drowzee, 54},
    {Species.Hypno, 55},
    {Species.Makuhita, 56},
    {Species.Hariyama, 57},
    {Species.Smeargle, 58},
    {Species.Crabrawler, 59},
    {Species.Crabominable, 60},
    {Species.Gastly, 61},
    {Species.Haunter, 62},
    {Species.Gengar, 63},
    {Species.Drifloon, 64},
    {Species.Drifblim, 65},
    {Species.Misdreavus, 66},
    {Species.Mismagius, 67},
    {Species.Zubat, 68},
    {Species.Golbat, 69},
    {Species.Crobat, 70},
    {Species.Diglett, (71, 1)},
    {Species.Dugtrio, (72, 1)},
    {Species.Spearow, 73},
    {Species.Fearow, 74},
    {Species.Rufflet, 75},
    {Species.Braviary, 76},
    {Species.Vullaby, 77},
    {Species.Mandibuzz, 78},
    {Species.Mankey, 79},
    {Species.Primeape, 80},
    {Species.Delibird, 81},
    {Species.Oricorio, (82, 0..3)},
    {Species.Cutiefly, 83},
    {Species.Ribombee, 84},
    {Species.Petilil, 85},
    {Species.Lilligant, 86},
    {Species.Cottonee, 87},
    {Species.Whimsicott, 88},
    {Species.Psyduck, 89},
    {Species.Golduck, 90},
    {Species.Magikarp, 91},
    {Species.Gyarados, 92},
    {Species.Barboach, 93},
    {Species.Whiscash, 94},
    {Species.Machop, 95},
    {Species.Machoke, 96},
    {Species.Machamp, 97},
    {Species.Roggenrola, 98},
    {Species.Boldore, 99},
    {Species.Gigalith, 100},
    {Species.Carbink, 101},
    {Species.Sableye, 102},
    {Species.Rockruff, (103, 0..1)},
    {Species.Lycanroc, (104, 0..2)},
    {Species.Spinda, 105},
    {Species.Tentacool, 106},
    {Species.Tentacruel, 107},
    {Species.Finneon, 108},
    {Species.Lumineon, 109},
    {Species.Wishiwashi, (110, 0..1)},
    {Species.Luvdisc, 111},
    {Species.Corsola, 112},
    {Species.Mareanie, 113},
    {Species.Toxapex, 114},
    {Species.Shellder, 115},
    {Species.Cloyster, 116},
    {Species.Bagon, 117},
    {Species.Shelgon, 118},
    {Species.Salamence, 119},
    {Species.Lillipup, 120},
    {Species.Herdier, 121},
    {Species.Stoutland, 122},
    {Species.Eevee, 123},
    {Species.Vaporeon, 124},
    {Species.Jolteon, 125},
    {Species.Flareon, 126},
    {Species.Espeon, 127},
    {Species.Umbreon, 128},
    {Species.Leafeon, 129},
    {Species.Glaceon, 130},
    {Species.Sylveon, 131},
    {Species.Mudbray, 132},
    {Species.Mudsdale, 133},
    {Species.Igglybuff, 134},
    {Species.Jigglypuff, 135},
    {Species.Wigglytuff, 136},
    {Species.Tauros, 137},
    {Species.Miltank, 138},
    {Species.Surskit, 139},
    {Species.Masquerain, 140},
    {Species.Dewpider, 141},
    {Species.Araquanid, 142},
    {Species.Fomantis, 143},
    {Species.Lurantis, 144},
    {Species.Morelull, 145},
    {Species.Shiinotic, 146},
    {Species.Paras, 147},
    {Species.Parasect, 148},
    {Species.Poliwag, 149},
    {Species.Poliwhirl, 150},
    {Species.Poliwrath, 151},
    {Species.Politoed, 152},
    {Species.Goldeen, 153},
    {Species.Seaking, 154},
    {Species.Feebas, 155},
    {Species.Milotic, 156},
    {Species.Alomomola, 157},
    {Species.Fletchling, 158},
    {Species.Fletchinder, 159},
    {Species.Talonflame, 160},
    {Species.Salandit, 161},
    {Species.Salazzle, 162},
    {Species.Cubone, 163},
    {Species.Marowak, (164, 1)},
    {Species.Kangaskhan, 165},
    {Species.Magby, 166},
    {Species.Magmar, 167},
    {Species.Magmortar, 168},
    {Species.Stufful, 169},
    {Species.Bewear, 170},
    {Species.Bounsweet, 171},
    {Species.Steenee, 172},
    {Species.Tsareena, 173},
    {Species.Comfey, 174},
    {Species.Pinsir, 175},
    {Species.Oranguru, 176},
    {Species.Passimian, 177},
    {Species.Goomy, 178},
    {Species.Sliggoo, 179},
    {Species.Goodra, 180},
    {Species.Castform, (181, 0..3)},
    {Species.Wimpod, 182},
    {Species.Golisopod, 183},
    {Species.Staryu, 184},
    {Species.Starmie, 185},
    {Species.Sandygast, 186},
    {Species.Palossand, 187},
    {Species.Cranidos, 188},
    {Species.Rampardos, 189},
    {Species.Shieldon, 190},
    {Species.Bastiodon, 191},
    {Species.Archen, 192},
    {Species.Archeops, 193},
    {Species.Tirtouga, 194},
    {Species.Carracosta, 195},
    {Species.Phantump, 196},
    {Species.Trevenant, 197},
    {Species.Nosepass, 198},
    {Species.Probopass, 199},
    {Species.Pyukumuku, 200},
    {Species.Chinchou, 201},
    {Species.Lanturn, 202},
    {Species.TypeNull, 203},
    {Species.Silvally, (204, 0..17)},
    {Species.Zygarde, 205},
    {Species.Trubbish, 206},
    {Species.Garbodor, 207},
    {Species.Skarmory, 208},
    {Species.Ditto, 209},
    {Species.Cleffa, 210},
    {Species.Clefairy, 211},
    {Species.Clefable, 212},
    {Species.Minior, (213, 0..13)},
    {Species.Beldum, 214},
    {Species.Metang, 215},
    {Species.Metagross, 216},
    {Species.Porygon, 217},
    {Species.Porygon2, 218},
    {Species.PorygonZ, 219},
    {Species.Pancham, 220},
    {Species.Pangoro, 221},
    {Species.Komala, 222},
    {Species.Torkoal, 223},
    {Species.Turtonator, 224},
    {Species.Togedemaru, 225},
    {Species.Elekid, 226},
    {Species.Electabuzz, 227},
    {Species.Electivire, 228},
    {Species.Geodude, (229, 1)},
    {Species.Graveler, (230, 1)},
    {Species.Golem, (231, 1)},
    {Species.Sandile, 232},
    {Species.Krokorok, 233},
    {Species.Krookodile, 234},
    {Species.Trapinch, 235},
    {Species.Vibrava, 236},
    {Species.Flygon, 237},
    {Species.Gible, 238},
    {Species.Gabite, 239},
    {Species.Garchomp, 240},
    {Species.Klefki, 241},
    {Species.Mimikyu, (242, 0..1)},
    {Species.Bruxish, 243},
    {Species.Drampa, 244},
    {Species.Absol, 245},
    {Species.Snorunt, 246},
    {Species.Glalie, 247},
    {Species.Froslass, 248},
    {Species.Sneasel, 249},
    {Species.Weavile, 250},
    {Species.Sandshrew, (251, 1)},
    {Species.Sandslash, (252, 1)},
    {Species.Vulpix, (253, 1)},
    {Species.Ninetales, (254, 1)},
    {Species.Vanillite, 255},
    {Species.Vanillish, 256},
    {Species.Vanilluxe, 257},
    {Species.Snubbull, 258},
    {Species.Granbull, 259},
    {Species.Shellos, (260, 0..1)},
    {Species.Gastrodon, (261, 0..1)},
    {Species.Relicanth, 262},
    {Species.Dhelmise, 263},
    {Species.Carvanha, 264},
    {Species.Sharpedo, 265},
    {Species.Wailmer, 266},
    {Species.Wailord, 267},
    {Species.Lapras, 268},
    {Species.Exeggcute, 269},
    {Species.Exeggutor, (270, 1)},
    {Species.Jangmoo, 271},
    {Species.Hakamoo, 272},
    {Species.Kommoo, 273},
    {Species.Emolga, 274},
    {Species.Scyther, 275},
    {Species.Scizor, 276},
    {Species.Murkrow, 277},
    {Species.Honchkrow, 278},
    {Species.Riolu, 279},
    {Species.Lucario, 280},
    {Species.Dratini, 281},
    {Species.Dragonair, 282},
    {Species.Dragonite, 283},
    {Species.Aerodactyl, 284},
    {Species.TapuKoko, 285},
    {Species.TapuLele, 286},
    {Species.TapuBulu, 287},
    {Species.TapuFini, 288},
    {Species.Cosmog, 289},
    {Species.Cosmoem, 290},
    {Species.Solgaleo, 291},
    {Species.Lunala, 292},
    {Species.Nihilego, 293},
    {Species.Buzzwole, 294},
    {Species.Pheromosa, 295},
    {Species.Xurkitree, 296},
    {Species.Celesteela, 297},
    {Species.Kartana, 298},
    {Species.Guzzlord, 299},
    {Species.Necrozma, (300, 0..3)},
    {Species.Magearna, 301},
    {Species.Marshadow, 302},
  };

  private static readonly Dictionary<Species, PositionForms> SMMelemeleDex = new Dictionary<Species, PositionForms>() {
    {Species.Rowlet, 1},
    {Species.Dartrix, 2},
    {Species.Decidueye, 3},
    {Species.Litten, 4},
    {Species.Torracat, 5},
    {Species.Incineroar, 6},
    {Species.Popplio, 7},
    {Species.Brionne, 8},
    {Species.Primarina, 9},
    {Species.Pikipek, 10},
    {Species.Trumbeak, 11},
    {Species.Toucannon, 12},
    {Species.Yungoos, 13},
    {Species.Gumshoos, 14},
    {Species.Rattata, 15},
    {Species.Raticate, 16},
    {Species.Caterpie, 17},
    {Species.Metapod, 18},
    {Species.Butterfree, 19},
    {Species.Ledyba, 20},
    {Species.Ledian, 21},
    {Species.Spinarak, 22},
    {Species.Ariados, 23},
    {Species.Pichu, 24},
    {Species.Pikachu, 25},
    {Species.Raichu, (26, 1)},
    {Species.Grubbin, 27},
    {Species.Charjabug, 28},
    {Species.Vikavolt, 29},
    {Species.Bonsly, 30},
    {Species.Sudowoodo, 31},
    {Species.Happiny, 32},
    {Species.Chansey, 33},
    {Species.Blissey, 34},
    {Species.Munchlax, 35},
    {Species.Snorlax, 36},
    {Species.Slowpoke, 37},
    {Species.Slowbro, 38},
    {Species.Slowking, 39},
    {Species.Wingull, 40},
    {Species.Pelipper, 41},
    {Species.Abra, 42},
    {Species.Kadabra, 43},
    {Species.Alakazam, 44},
    {Species.Meowth, (45, 1)},
    {Species.Persian, (46, 1)},
    {Species.Magnemite, 47},
    {Species.Magneton, 48},
    {Species.Magnezone, 49},
    {Species.Grimer, (50, 1)},
    {Species.Muk, (51, 1)},
    {Species.Growlithe, 52},
    {Species.Arcanine, 53},
    {Species.Drowzee, 54},
    {Species.Hypno, 55},
    {Species.Makuhita, 56},
    {Species.Hariyama, 57},
    {Species.Smeargle, 58},
    {Species.Crabrawler, 59},
    {Species.Crabominable, 60},
    {Species.Gastly, 61},
    {Species.Haunter, 62},
    {Species.Gengar, 63},
    {Species.Drifloon, 64},
    {Species.Drifblim, 65},
    {Species.Misdreavus, 66},
    {Species.Mismagius, 67},
    {Species.Zubat, 68},
    {Species.Golbat, 69},
    {Species.Crobat, 70},
    {Species.Diglett, (71, 1)},
    {Species.Dugtrio, (72, 1)},
    {Species.Spearow, 73},
    {Species.Fearow, 74},
    {Species.Rufflet, 75},
    {Species.Braviary, 76},
    {Species.Vullaby, 77},
    {Species.Mandibuzz, 78},
    {Species.Mankey, 79},
    {Species.Primeape, 80},
    {Species.Delibird, 81},
    {Species.Oricorio, (82, 0..3)},
    {Species.Cutiefly, 83},
    {Species.Ribombee, 84},
    {Species.Petilil, 85},
    {Species.Lilligant, 86},
    {Species.Cottonee, 87},
    {Species.Whimsicott, 88},
    {Species.Psyduck, 89},
    {Species.Golduck, 90},
    {Species.Magikarp, 91},
    {Species.Gyarados, 92},
    {Species.Barboach, 93},
    {Species.Whiscash, 94},
    {Species.Machop, 95},
    {Species.Machoke, 96},
    {Species.Machamp, 97},
    {Species.Roggenrola, 98},
    {Species.Boldore, 99},
    {Species.Gigalith, 100},
    {Species.Carbink, 101},
    {Species.Sableye, 102},
    {Species.Rockruff, (103, 0..1)},
    {Species.Lycanroc, (104, 0..2)},
    {Species.Spinda, 105},
    {Species.Tentacool, 106},
    {Species.Tentacruel, 107},
    {Species.Finneon, 108},
    {Species.Lumineon, 109},
    {Species.Wishiwashi, (110, 0..1)},
    {Species.Luvdisc, 111},
    {Species.Corsola, 112},
    {Species.Mareanie, 113},
    {Species.Toxapex, 114},
    {Species.Shellder, 115},
    {Species.Cloyster, 116},
    {Species.Bagon, 117},
    {Species.Shelgon, 118},
    {Species.Salamence, 119},
    {Species.TapuKoko, 120}
  };

  private static readonly Dictionary<Species, PositionForms> SMAkalaDex = new Dictionary<Species, PositionForms>() {
    {Species.Pikipek, 1},
    {Species.Trumbeak, 2},
    {Species.Toucannon, 3},
    {Species.Yungoos, 4},
    {Species.Gumshoos, 5},
    {Species.Rattata, 6},
    {Species.Raticate, 7},
    {Species.Caterpie, 8},
    {Species.Metapod, 9},
    {Species.Butterfree, 10},
    {Species.Grubbin, 11},
    {Species.Charjabug, 12},
    {Species.Vikavolt, 13},
    {Species.Bonsly, 14},
    {Species.Sudowoodo, 15},
    {Species.Happiny, 16},
    {Species.Chansey, 17},
    {Species.Blissey, 18},
    {Species.Wingull, 19},
    {Species.Pelipper, 20},
    {Species.Crabrawler, 21},
    {Species.Crabominable, 22},
    {Species.Gastly, 23},
    {Species.Haunter, 24},
    {Species.Gengar, 25},
    {Species.Zubat, 26},
    {Species.Golbat, 27},
    {Species.Crobat, 28},
    {Species.Diglett, (29, 1)},
    {Species.Dugtrio, (30, 1)},
    {Species.Oricorio, (31, 0..3)},
    {Species.Psyduck, 32},
    {Species.Golduck, 33},
    {Species.Magikarp, 34},
    {Species.Gyarados, 35},
    {Species.Barboach, 36},
    {Species.Whiscash, 37},
    {Species.Tentacool, 38},
    {Species.Tentacruel, 39},
    {Species.Finneon, 40},
    {Species.Lumineon, 41},
    {Species.Wishiwashi, (42, 0..1)},
    {Species.Luvdisc, 43},
    {Species.Corsola, 44},
    {Species.Mareanie, 45},
    {Species.Toxapex, 46},
    {Species.Lillipup, 47},
    {Species.Herdier, 48},
    {Species.Stoutland, 49},
    {Species.Eevee, 50},
    {Species.Vaporeon, 51},
    {Species.Jolteon, 52},
    {Species.Flareon, 53},
    {Species.Espeon, 54},
    {Species.Umbreon, 55},
    {Species.Leafeon, 56},
    {Species.Glaceon, 57},
    {Species.Sylveon, 58},
    {Species.Mudbray, 59},
    {Species.Mudsdale, 60},
    {Species.Igglybuff, 61},
    {Species.Jigglypuff, 62},
    {Species.Wigglytuff, 63},
    {Species.Tauros, 64},
    {Species.Miltank, 65},
    {Species.Surskit, 66},
    {Species.Masquerain, 67},
    {Species.Dewpider, 68},
    {Species.Araquanid, 69},
    {Species.Fomantis, 70},
    {Species.Lurantis, 71},
    {Species.Morelull, 72},
    {Species.Shiinotic, 73},
    {Species.Paras, 74},
    {Species.Parasect, 75},
    {Species.Poliwag, 76},
    {Species.Poliwhirl, 77},
    {Species.Poliwrath, 78},
    {Species.Politoed, 79},
    {Species.Goldeen, 80},
    {Species.Seaking, 81},
    {Species.Feebas, 82},
    {Species.Milotic, 83},
    {Species.Alomomola, 84},
    {Species.Fletchling, 85},
    {Species.Fletchinder, 86},
    {Species.Talonflame, 87},
    {Species.Salandit, 88},
    {Species.Salazzle, 89},
    {Species.Cubone, 90},
    {Species.Marowak, (91, 1)},
    {Species.Kangaskhan, 92},
    {Species.Magby, 93},
    {Species.Magmar, 94},
    {Species.Magmortar, 95},
    {Species.Stufful, 96},
    {Species.Bewear, 97},
    {Species.Bounsweet, 98},
    {Species.Steenee, 99},
    {Species.Tsareena, 100},
    {Species.Comfey, 101},
    {Species.Pinsir, 102},
    {Species.Oranguru, 103},
    {Species.Passimian, 104},
    {Species.Goomy, 105},
    {Species.Sliggoo, 106},
    {Species.Goodra, 107},
    {Species.Castform, (108, 0..3)},
    {Species.Wimpod, 109},
    {Species.Golisopod, 110},
    {Species.Staryu, 111},
    {Species.Starmie, 112},
    {Species.Sandygast, 113},
    {Species.Palossand, 114},
    {Species.Cranidos, 115},
    {Species.Rampardos, 116},
    {Species.Shieldon, 117},
    {Species.Bastiodon, 118},
    {Species.Archen, 119},
    {Species.Archeops, 120},
    {Species.Tirtouga, 121},
    {Species.Carracosta, 122},
    {Species.Phantump, 123},
    {Species.Trevenant, 124},
    {Species.Nosepass, 125},
    {Species.Probopass, 126},
    {Species.Pyukumuku, 127},
    {Species.Chinchou, 128},
    {Species.Lanturn, 129},
    {Species.TapuLele, 130}
  };

  private static readonly Dictionary<Species, PositionForms> SMUlaulaDex = new Dictionary<Species, PositionForms>() {
    {Species.Pikipek, 1},
    {Species.Trumbeak, 2},
    {Species.Toucannon, 3},
    {Species.Yungoos, 4},
    {Species.Gumshoos, 5},
    {Species.Rattata, 6},
    {Species.Raticate, 7},
    {Species.Ledyba, 8},
    {Species.Ledian, 9},
    {Species.Spinarak, 10},
    {Species.Ariados, 11},
    {Species.Grubbin, 12},
    {Species.Charjabug, 13},
    {Species.Vikavolt, 14},
    {Species.Happiny, 15},
    {Species.Chansey, 16},
    {Species.Blissey, 17},
    {Species.Slowpoke, 18},
    {Species.Slowbro, 19},
    {Species.Slowking, 20},
    {Species.Wingull, 21},
    {Species.Pelipper, 22},
    {Species.Meowth, (23, 1)},
    {Species.Persian, (24, 1)},
    {Species.Magnemite, 25},
    {Species.Magneton, 26},
    {Species.Magnezone, 27},
    {Species.Grimer, (28, 1)},
    {Species.Muk, (29, 1)},
    {Species.Crabrawler, 30},
    {Species.Crabominable, 31},
    {Species.Gastly, 32},
    {Species.Haunter, 33},
    {Species.Gengar, 34},
    {Species.Zubat, 35},
    {Species.Golbat, 36},
    {Species.Crobat, 37},
    {Species.Diglett, (38, 1)},
    {Species.Dugtrio, (39, 1)},
    {Species.Spearow, 40},
    {Species.Fearow, 41},
    {Species.Oricorio, (42, 0..3)},
    {Species.Cutiefly, 43},
    {Species.Ribombee, 44},
    {Species.Petilil, 45},
    {Species.Lilligant, 46},
    {Species.Cottonee, 47},
    {Species.Whimsicott, 48},
    {Species.Psyduck, 49},
    {Species.Golduck, 50},
    {Species.Magikarp, 51},
    {Species.Gyarados, 52},
    {Species.Tentacool, 53},
    {Species.Tentacruel, 54},
    {Species.Finneon, 55},
    {Species.Lumineon, 56},
    {Species.Wishiwashi, (57, 0..1)},
    {Species.Mudbray, 58},
    {Species.Mudsdale, 59},
    {Species.Surskit, 60},
    {Species.Masquerain, 61},
    {Species.Dewpider, 62},
    {Species.Araquanid, 63},
    {Species.Morelull, 64},
    {Species.Shiinotic, 65},
    {Species.Paras, 66},
    {Species.Parasect, 67},
    {Species.Poliwag, 68},
    {Species.Poliwhirl, 69},
    {Species.Poliwrath, 70},
    {Species.Politoed, 71},
    {Species.Goldeen, 72},
    {Species.Seaking, 73},
    {Species.Goomy, 74},
    {Species.Sliggoo, 75},
    {Species.Goodra, 76},
    {Species.Castform, (77, 0..3)},
    {Species.Trubbish, 78},
    {Species.Garbodor, 79},
    {Species.Skarmory, 80},
    {Species.Ditto, 81},
    {Species.Cleffa, 82},
    {Species.Clefairy, 83},
    {Species.Clefable, 84},
    {Species.Minior, (85, 0..13)},
    {Species.Beldum, 86},
    {Species.Metang, 87},
    {Species.Metagross, 88},
    {Species.Porygon, 89},
    {Species.Porygon2, 90},
    {Species.PorygonZ, 91},
    {Species.Pancham, 92},
    {Species.Pangoro, 93},
    {Species.Komala, 94},
    {Species.Torkoal, 95},
    {Species.Turtonator, 96},
    {Species.Togedemaru, 97},
    {Species.Elekid, 98},
    {Species.Electabuzz, 99},
    {Species.Electivire, 100},
    {Species.Geodude, (101, 1)},
    {Species.Graveler, (102, 1)},
    {Species.Golem, (103, 1)},
    {Species.Sandile, 104},
    {Species.Krokorok, 105},
    {Species.Krookodile, 106},
    {Species.Trapinch, 107},
    {Species.Vibrava, 108},
    {Species.Flygon, 109},
    {Species.Gible, 110},
    {Species.Gabite, 111},
    {Species.Garchomp, 112},
    {Species.Klefki, 113},
    {Species.Mimikyu, (114, 0..1)},
    {Species.Bruxish, 115},
    {Species.Drampa, 116},
    {Species.Absol, 117},
    {Species.Snorunt, 118},
    {Species.Glalie, 119},
    {Species.Froslass, 120},
    {Species.Sneasel, 121},
    {Species.Weavile, 122},
    {Species.Sandshrew, (123, 1)},
    {Species.Sandslash, (124, 1)},
    {Species.Vulpix, (125, 1)},
    {Species.Ninetales, (126, 1)},
    {Species.Vanillite, 127},
    {Species.Vanillish, 128},
    {Species.Vanilluxe, 129},
    {Species.TapuBulu, 130}
  };

  private static readonly Dictionary<Species, PositionForms> SMPoniDex = new Dictionary<Species, PositionForms>() {
    {Species.Pikipek, 1},
    {Species.Trumbeak, 2},
    {Species.Toucannon, 3},
    {Species.Yungoos, 4},
    {Species.Gumshoos, 5},
    {Species.Rattata, 6},
    {Species.Raticate, 7},
    {Species.Happiny, 8},
    {Species.Chansey, 9},
    {Species.Blissey, 10},
    {Species.Wingull, 11},
    {Species.Pelipper, 12},
    {Species.Drowzee, 13},
    {Species.Hypno, 14},
    {Species.Makuhita, 15},
    {Species.Hariyama, 16},
    {Species.Crabrawler, 17},
    {Species.Crabominable, 18},
    {Species.Zubat, 19},
    {Species.Golbat, 20},
    {Species.Crobat, 21},
    {Species.Diglett, (22, 1)},
    {Species.Dugtrio, (23, 1)},
    {Species.Spearow, 24},
    {Species.Fearow, 25},
    {Species.Rufflet, 26},
    {Species.Braviary, 27},
    {Species.Vullaby, 28},
    {Species.Mandibuzz, 29},
    {Species.Mankey, 30},
    {Species.Primeape, 31},
    {Species.Oricorio, (32, 0..3)},
    {Species.Cutiefly, 33},
    {Species.Ribombee, 34},
    {Species.Petilil, 35},
    {Species.Lilligant, 36},
    {Species.Cottonee, 37},
    {Species.Whimsicott, 38},
    {Species.Psyduck, 39},
    {Species.Golduck, 40},
    {Species.Magikarp, 41},
    {Species.Gyarados, 42},
    {Species.Barboach, 43},
    {Species.Whiscash, 44},
    {Species.Machop, 45},
    {Species.Machoke, 46},
    {Species.Machamp, 47},
    {Species.Roggenrola, 48},
    {Species.Boldore, 49},
    {Species.Gigalith, 50},
    {Species.Carbink, 51},
    {Species.Sableye, 52},
    {Species.Rockruff, (53, 0..1)},
    {Species.Lycanroc, (54, 0..2)},
    {Species.Tentacool, 55},
    {Species.Tentacruel, 56},
    {Species.Finneon, 57},
    {Species.Lumineon, 58},
    {Species.Mudbray, 59},
    {Species.Mudsdale, 60},
    {Species.Tauros, 61},
    {Species.Miltank, 62},
    {Species.Stufful, 63},
    {Species.Bewear, 64},
    {Species.Pinsir, 65},
    {Species.Goomy, 66},
    {Species.Sliggoo, 67},
    {Species.Goodra, 68},
    {Species.Castform, (69, 0..3)},
    {Species.Wimpod, 70},
    {Species.Golisopod, 71},
    {Species.Skarmory, 72},
    {Species.Snubbull, 73},
    {Species.Granbull, 74},
    {Species.Shellos, (75, 0..1)},
    {Species.Gastrodon, (76, 0..1)},
    {Species.Relicanth, 77},
    {Species.Dhelmise, 78},
    {Species.Carvanha, 79},
    {Species.Sharpedo, 80},
    {Species.Wailmer, 81},
    {Species.Wailord, 82},
    {Species.Lapras, 83},
    {Species.Exeggcute, 84},
    {Species.Exeggutor, (85, 1)},
    {Species.Jangmoo, 86},
    {Species.Hakamoo, 87},
    {Species.Kommoo, 88},
    {Species.Emolga, 89},
    {Species.Scyther, 90},
    {Species.Scizor, 91},
    {Species.Murkrow, 92},
    {Species.Honchkrow, 93},
    {Species.Riolu, 94},
    {Species.Lucario, 95},
    {Species.Dratini, 96},
    {Species.Dragonair, 97},
    {Species.Dragonite, 98},
    {Species.Aerodactyl, 99},
    {Species.TapuFini, 100}
  };

  private static readonly Dictionary<Species, PositionForms> USUMFullDex = new Dictionary<Species, PositionForms>() {
    {Species.Rowlet, 1},
    {Species.Dartrix, 2},
    {Species.Decidueye, 3},
    {Species.Litten, 4},
    {Species.Torracat, 5},
    {Species.Incineroar, 6},
    {Species.Popplio, 7},
    {Species.Brionne, 8},
    {Species.Primarina, 9},
    {Species.Pikipek, 10},
    {Species.Trumbeak, 11},
    {Species.Toucannon, 12},
    {Species.Yungoos, 13},
    {Species.Gumshoos, 14},
    {Species.Rattata, (15, 1)},
    {Species.Raticate, (16, 1)},
    {Species.Caterpie, 17},
    {Species.Metapod, 18},
    {Species.Butterfree, 19},
    {Species.Ledyba, 20},
    {Species.Ledian, 21},
    {Species.Spinarak, 22},
    {Species.Ariados, 23},
    {Species.Buneary, 24},
    {Species.Lopunny, 25},
    {Species.Inkay, 26},
    {Species.Malamar, 27},
    {Species.Zorua, 28},
    {Species.Zoroark, 29},
    {Species.Furfrou, (30, 0..9)},
    {Species.Pichu, 31},
    {Species.Pikachu, 32},
    {Species.Raichu, (33, 1)},
    {Species.Grubbin, 34},
    {Species.Charjabug, 35},
    {Species.Vikavolt, 36},
    {Species.Bonsly, 37},
    {Species.Sudowoodo, 38},
    {Species.Happiny, 39},
    {Species.Chansey, 40},
    {Species.Blissey, 41},
    {Species.Munchlax, 42},
    {Species.Snorlax, 43},
    {Species.Slowpoke, 44},
    {Species.Slowbro, 45},
    {Species.Slowking, 46},
    {Species.Wingull, 47},
    {Species.Pelipper, 48},
    {Species.Abra, 49},
    {Species.Kadabra, 50},
    {Species.Alakazam, 51},
    {Species.Meowth, (52, 1)},
    {Species.Persian, (53, 1)},
    {Species.Magnemite, 54},
    {Species.Magneton, 55},
    {Species.Magnezone, 56},
    {Species.Grimer, (57, 1)},
    {Species.Muk, (58, 1)},
    {Species.MimeJr, 59},
    {Species.MrMime, 60},
    {Species.Ekans, 61},
    {Species.Arbok, 62},
    {Species.Dunsparce, 63},
    {Species.Growlithe, 64},
    {Species.Arcanine, 65},
    {Species.Drowzee, 66},
    {Species.Hypno, 67},
    {Species.Makuhita, 68},
    {Species.Hariyama, 69},
    {Species.Smeargle, 70},
    {Species.Crabrawler, 71},
    {Species.Crabominable, 72},
    {Species.Gastly, 73},
    {Species.Haunter, 74},
    {Species.Gengar, 75},
    {Species.Drifloon, 76},
    {Species.Drifblim, 77},
    {Species.Murkrow, 78},
    {Species.Honchkrow, 79},
    {Species.Zubat, 80},
    {Species.Golbat, 81},
    {Species.Crobat, 82},
    {Species.Noibat, 83},
    {Species.Noivern, 84},
    {Species.Diglett, (85, 1)},
    {Species.Dugtrio, (86, 1)},
    {Species.Spearow, 87},
    {Species.Fearow, 88},
    {Species.Rufflet, 89},
    {Species.Braviary, 90},
    {Species.Vullaby, 91},
    {Species.Mandibuzz, 92},
    {Species.Mankey, 93},
    {Species.Primeape, 94},
    {Species.Delibird, 95},
    {Species.Hawlucha, 96},
    {Species.Oricorio, (97, 0..3)},
    {Species.Cutiefly, 98},
    {Species.Ribombee, 99},
    {Species.Flabébé, (100, 0..4)},
    {Species.Floette, (101, 0..5)},
    {Species.Florges, (102, 0..4)},
    {Species.Petilil, 103},
    {Species.Lilligant, 104},
    {Species.Cottonee, 105},
    {Species.Whimsicott, 106},
    {Species.Psyduck, 107},
    {Species.Golduck, 108},
    {Species.Smoochum, 109},
    {Species.Jynx, 110},
    {Species.Magikarp, 111},
    {Species.Gyarados, 112},
    {Species.Barboach, 113},
    {Species.Whiscash, 114},
    {Species.Seel, 115},
    {Species.Dewgong, 116},
    {Species.Machop, 117},
    {Species.Machoke, 118},
    {Species.Machamp, 119},
    {Species.Roggenrola, 120},
    {Species.Boldore, 121},
    {Species.Gigalith, 122},
    {Species.Carbink, 123},
    {Species.Sableye, 124},
    {Species.Mawile, 125},
    {Species.Rockruff, (126, 0..1)},
    {Species.Lycanroc, (127, 0..2)},
    {Species.Spinda, 128},
    {Species.Tentacool, 129},
    {Species.Tentacruel, 130},
    {Species.Finneon, 131},
    {Species.Lumineon, 132},
    {Species.Wishiwashi, (133, 0..1)},
    {Species.Luvdisc, 134},
    {Species.Corsola, 135},
    {Species.Mareanie, 136},
    {Species.Toxapex, 137},
    {Species.Shellder, 138},
    {Species.Cloyster, 139},
    {Species.Clamperl, 140},
    {Species.Huntail, 141},
    {Species.Gorebyss, 142},
    {Species.Remoraid, 143},
    {Species.Octillery, 144},
    {Species.Mantyke, 145},
    {Species.Mantine, 146},
    {Species.Bagon, 147},
    {Species.Shelgon, 148},
    {Species.Salamence, 149},
    {Species.Lillipup, 150},
    {Species.Herdier, 151},
    {Species.Stoutland, 152},
    {Species.Eevee, 153},
    {Species.Vaporeon, 154},
    {Species.Jolteon, 155},
    {Species.Flareon, 156},
    {Species.Espeon, 157},
    {Species.Umbreon, 158},
    {Species.Leafeon, 159},
    {Species.Glaceon, 160},
    {Species.Sylveon, 161},
    {Species.Mareep, 162},
    {Species.Flaaffy, 163},
    {Species.Ampharos, 164},
    {Species.Mudbray, 165},
    {Species.Mudsdale, 166},
    {Species.Igglybuff, 167},
    {Species.Jigglypuff, 168},
    {Species.Wigglytuff, 169},
    {Species.Tauros, 170},
    {Species.Miltank, 171},
    {Species.Surskit, 172},
    {Species.Masquerain, 173},
    {Species.Dewpider, 174},
    {Species.Araquanid, 175},
    {Species.Fomantis, 176},
    {Species.Lurantis, 177},
    {Species.Morelull, 178},
    {Species.Shiinotic, 179},
    {Species.Paras, 180},
    {Species.Parasect, 181},
    {Species.Poliwag, 182},
    {Species.Poliwhirl, 183},
    {Species.Poliwrath, 184},
    {Species.Politoed, 185},
    {Species.Goldeen, 186},
    {Species.Seaking, 187},
    {Species.Basculin, (188, 0..1)},
    {Species.Feebas, 189},
    {Species.Milotic, 190},
    {Species.Alomomola, 191},
    {Species.Fletchling, 192},
    {Species.Fletchinder, 193},
    {Species.Talonflame, 194},
    {Species.Salandit, 195},
    {Species.Salazzle, 196},
    {Species.Cubone, 197},
    {Species.Marowak, (198, 1)},
    {Species.Kangaskhan, 199},
    {Species.Magby, 200},
    {Species.Magmar, 201},
    {Species.Magmortar, 202},
    {Species.Larvesta, 203},
    {Species.Volcarona, 204},
    {Species.Stufful, 205},
    {Species.Bewear, 206},
    {Species.Bounsweet, 207},
    {Species.Steenee, 208},
    {Species.Tsareena, 209},
    {Species.Comfey, 210},
    {Species.Pinsir, 211},
    {Species.Hoothoot, 212},
    {Species.Noctowl, 213},
    {Species.Kecleon, 214},
    {Species.Oranguru, 215},
    {Species.Passimian, 216},
    {Species.Goomy, 217},
    {Species.Sliggoo, 218},
    {Species.Goodra, 219},
    {Species.Castform, (220, 0..3)},
    {Species.Wimpod, 221},
    {Species.Golisopod, 222},
    {Species.Staryu, 223},
    {Species.Starmie, 224},
    {Species.Sandygast, 225},
    {Species.Palossand, 226},
    {Species.Omanyte, 227},
    {Species.Omastar, 228},
    {Species.Kabuto, 229},
    {Species.Kabutops, 230},
    {Species.Lileep, 231},
    {Species.Cradily, 232},
    {Species.Anorith, 233},
    {Species.Armaldo, 234},
    {Species.Cranidos, 235},
    {Species.Rampardos, 236},
    {Species.Shieldon, 237},
    {Species.Bastiodon, 238},
    {Species.Archen, 239},
    {Species.Archeops, 240},
    {Species.Tirtouga, 241},
    {Species.Carracosta, 242},
    {Species.Tyrunt, 243},
    {Species.Tyrantrum, 244},
    {Species.Amaura, 245},
    {Species.Aurorus, 246},
    {Species.Larvitar, 247},
    {Species.Pupitar, 248},
    {Species.Tyranitar, 249},
    {Species.Phantump, 250},
    {Species.Trevenant, 251},
    {Species.Natu, 252},
    {Species.Xatu, 253},
    {Species.Nosepass, 254},
    {Species.Probopass, 255},
    {Species.Pyukumuku, 256},
    {Species.Chinchou, 257},
    {Species.Lanturn, 258},
    {Species.TypeNull, 259},
    {Species.Silvally, (260, 0..17)},
    {Species.Poipole, 261},
    {Species.Naganadel, 262},
    {Species.Zygarde, 263},
    {Species.Trubbish, 264},
    {Species.Garbodor, 265},
    {Species.Minccino, 266},
    {Species.Cinccino, 267},
    {Species.Pineco, 268},
    {Species.Forretress, 269},
    {Species.Skarmory, 270},
    {Species.Ditto, 271},
    {Species.Cleffa, 272},
    {Species.Clefairy, 273},
    {Species.Clefable, 274},
    {Species.Elgyem, 275},
    {Species.Beheeyem, 276},
    {Species.Minior, (277, 0..13)},
    {Species.Beldum, 278},
    {Species.Metang, 279},
    {Species.Metagross, 280},
    {Species.Porygon, 281},
    {Species.Porygon2, 282},
    {Species.PorygonZ, 283},
    {Species.Pancham, 284},
    {Species.Pangoro, 285},
    {Species.Komala, 286},
    {Species.Torkoal, 287},
    {Species.Turtonator, 288},
    {Species.Houndour, 289},
    {Species.Houndoom, 290},
    {Species.Dedenne, 291},
    {Species.Togedemaru, 292},
    {Species.Electrike, 293},
    {Species.Manectric, 294},
    {Species.Elekid, 295},
    {Species.Electabuzz, 296},
    {Species.Electivire, 297},
    {Species.Geodude, (298, 1)},
    {Species.Graveler, (299, 1)},
    {Species.Golem, (300, 1)},
    {Species.Sandile, 301},
    {Species.Krokorok, 302},
    {Species.Krookodile, 303},
    {Species.Trapinch, 304},
    {Species.Vibrava, 305},
    {Species.Flygon, 306},
    {Species.Gible, 307},
    {Species.Gabite, 308},
    {Species.Garchomp, 309},
    {Species.Baltoy, 310},
    {Species.Claydol, 311},
    {Species.Golett, 312},
    {Species.Golurk, 313},
    {Species.Klefki, 314},
    {Species.Mimikyu, (315, 0..1)},
    {Species.Shuppet, 316},
    {Species.Banette, 317},
    {Species.Frillish, 318},
    {Species.Jellicent, 319},
    {Species.Bruxish, 320},
    {Species.Drampa, 321},
    {Species.Absol, 322},
    {Species.Snorunt, 323},
    {Species.Glalie, 324},
    {Species.Froslass, 325},
    {Species.Sneasel, 326},
    {Species.Weavile, 327},
    {Species.Sandshrew, (328, 1)},
    {Species.Sandslash, (329, 1)},
    {Species.Vulpix, (330, 1)},
    {Species.Ninetales, (331, 1)},
    {Species.Vanillite, 332},
    {Species.Vanillish, 333},
    {Species.Vanilluxe, 334},
    {Species.Scraggy, 335},
    {Species.Scrafty, 336},
    {Species.Pawniard, 337},
    {Species.Bisharp, 338},
    {Species.Snubbull, 339},
    {Species.Granbull, 340},
    {Species.Shellos, (341, 0..1)},
    {Species.Gastrodon, (342, 0..1)},
    {Species.Relicanth, 343},
    {Species.Dhelmise, 344},
    {Species.Carvanha, 345},
    {Species.Sharpedo, 346},
    {Species.Skrelp, 347},
    {Species.Dragalge, 348},
    {Species.Clauncher, 349},
    {Species.Clawitzer, 350},
    {Species.Wailmer, 351},
    {Species.Wailord, 352},
    {Species.Lapras, 353},
    {Species.Tropius, 354},
    {Species.Exeggcute, 355},
    {Species.Exeggutor, (356, 1)},
    {Species.Corphish, 357},
    {Species.Crawdaunt, 358},
    {Species.Mienfoo, 359},
    {Species.Mienshao, 360},
    {Species.Jangmoo, 361},
    {Species.Hakamoo, 362},
    {Species.Kommoo, 363},
    {Species.Emolga, 364},
    {Species.Scyther, 365},
    {Species.Scizor, 366},
    {Species.Heracross, 367},
    {Species.Aipom, 368},
    {Species.Ambipom, 369},
    {Species.Litleo, 370},
    {Species.Pyroar, 371},
    {Species.Misdreavus, 372},
    {Species.Mismagius, 373},
    {Species.Druddigon, 374},
    {Species.Lickitung, 375},
    {Species.Lickilicky, 376},
    {Species.Riolu, 377},
    {Species.Lucario, 378},
    {Species.Dratini, 379},
    {Species.Dragonair, 380},
    {Species.Dragonite, 381},
    {Species.Aerodactyl, 382},
    {Species.TapuKoko, 383},
    {Species.TapuLele, 384},
    {Species.TapuBulu, 385},
    {Species.TapuFini, 386},
    {Species.Cosmog, 387},
    {Species.Cosmoem, 388},
    {Species.Solgaleo, 389},
    {Species.Lunala, 390},
    {Species.Nihilego, 391},
    {Species.Stakataka, 392},
    {Species.Blacephalon, 393},
    {Species.Buzzwole, 394},
    {Species.Pheromosa, 395},
    {Species.Xurkitree, 396},
    {Species.Celesteela, 397},
    {Species.Kartana, 398},
    {Species.Guzzlord, 399},
    {Species.Necrozma, (400, 0..3)},
    {Species.Magearna, 401},
    {Species.Marshadow, 402},
    {Species.Zeraora, 403},
  };

  private static readonly Dictionary<Species, PositionForms> USUMMelemeleDex = new Dictionary<Species, PositionForms>() {
    {Species.Rowlet, 1},
    {Species.Dartrix, 2},
    {Species.Decidueye, 3},
    {Species.Litten, 4},
    {Species.Torracat, 5},
    {Species.Incineroar, 6},
    {Species.Popplio, 7},
    {Species.Brionne, 8},
    {Species.Primarina, 9},
    {Species.Pikipek, 10},
    {Species.Trumbeak, 11},
    {Species.Toucannon, 12},
    {Species.Yungoos, 13},
    {Species.Gumshoos, 14},
    {Species.Rattata, (15, 1)},
    {Species.Raticate, (16, 1)},
    {Species.Caterpie, 17},
    {Species.Metapod, 18},
    {Species.Butterfree, 19},
    {Species.Ledyba, 20},
    {Species.Ledian, 21},
    {Species.Spinarak, 22},
    {Species.Ariados, 23},
    {Species.Buneary, 24},
    {Species.Lopunny, 25},
    {Species.Inkay, 26},
    {Species.Malamar, 27},
    {Species.Zorua, 28},
    {Species.Zoroark, 29},
    {Species.Furfrou, (30, 0..9)},
    {Species.Pichu, 31},
    {Species.Pikachu, 32},
    {Species.Raichu, (33, 1)},
    {Species.Grubbin, 34},
    {Species.Charjabug, 35},
    {Species.Vikavolt, 36},
    {Species.Bonsly, 37},
    {Species.Sudowoodo, 38},
    {Species.Happiny, 39},
    {Species.Chansey, 40},
    {Species.Blissey, 41},
    {Species.Munchlax, 42},
    {Species.Snorlax, 43},
    {Species.Slowpoke, 44},
    {Species.Slowbro, 45},
    {Species.Slowking, 46},
    {Species.Wingull, 47},
    {Species.Pelipper, 48},
    {Species.Abra, 49},
    {Species.Kadabra, 50},
    {Species.Alakazam, 51},
    {Species.Meowth, (52, 1)},
    {Species.Persian, (53, 1)},
    {Species.Magnemite, 54},
    {Species.Magneton, 55},
    {Species.Magnezone, 56},
    {Species.Grimer, (57, 1)},
    {Species.Muk, (58, 1)},
    {Species.MimeJr, 59},
    {Species.MrMime, 60},
    {Species.Ekans, 61},
    {Species.Arbok, 62},
    {Species.Dunsparce, 63},
    {Species.Growlithe, 64},
    {Species.Arcanine, 65},
    {Species.Drowzee, 66},
    {Species.Hypno, 67},
    {Species.Makuhita, 68},
    {Species.Hariyama, 69},
    {Species.Smeargle, 70},
    {Species.Crabrawler, 71},
    {Species.Crabominable, 72},
    {Species.Gastly, 73},
    {Species.Haunter, 74},
    {Species.Gengar, 75},
    {Species.Drifloon, 76},
    {Species.Drifblim, 77},
    {Species.Murkrow, 78},
    {Species.Honchkrow, 79},
    {Species.Zubat, 80},
    {Species.Golbat, 81},
    {Species.Crobat, 82},
    {Species.Noibat, 83},
    {Species.Noivern, 84},
    {Species.Diglett, (85, 1)},
    {Species.Dugtrio, (86, 1)},
    {Species.Spearow, 87},
    {Species.Fearow, 88},
    {Species.Rufflet, 89},
    {Species.Braviary, 90},
    {Species.Vullaby, 91},
    {Species.Mandibuzz, 92},
    {Species.Mankey, 93},
    {Species.Primeape, 94},
    {Species.Delibird, 95},
    {Species.Hawlucha, 96},
    {Species.Oricorio, (97, 0..3)},
    {Species.Cutiefly, 98},
    {Species.Ribombee, 99},
    {Species.Flabébé, (100, 0..4)},
    {Species.Floette, (101, 0..5)},
    {Species.Florges, (102, 0..4)},
    {Species.Petilil, 103},
    {Species.Lilligant, 104},
    {Species.Cottonee, 105},
    {Species.Whimsicott, 106},
    {Species.Psyduck, 107},
    {Species.Golduck, 108},
    {Species.Smoochum, 109},
    {Species.Jynx, 110},
    {Species.Magikarp, 111},
    {Species.Gyarados, 112},
    {Species.Barboach, 113},
    {Species.Whiscash, 114},
    {Species.Seel, 115},
    {Species.Dewgong, 116},
    {Species.Machop, 117},
    {Species.Machoke, 118},
    {Species.Machamp, 119},
    {Species.Roggenrola, 120},
    {Species.Boldore, 121},
    {Species.Gigalith, 122},
    {Species.Carbink, 123},
    {Species.Sableye, 124},
    {Species.Mawile, 125},
    {Species.Rockruff, (126, 0..1)},
    {Species.Lycanroc, (127, 0..2)},
    {Species.Spinda, 128},
    {Species.Tentacool, 129},
    {Species.Tentacruel, 130},
    {Species.Finneon, 131},
    {Species.Lumineon, 132},
    {Species.Wishiwashi, (133, 0..1)},
    {Species.Luvdisc, 134},
    {Species.Corsola, 135},
    {Species.Mareanie, 136},
    {Species.Toxapex, 137},
    {Species.Shellder, 138},
    {Species.Cloyster, 139},
    {Species.Clamperl, 140},
    {Species.Huntail, 141},
    {Species.Gorebyss, 142},
    {Species.Remoraid, 143},
    {Species.Octillery, 144},
    {Species.Mantyke, 145},
    {Species.Mantine, 146},
    {Species.Bagon, 147},
    {Species.Shelgon, 148},
    {Species.Salamence, 149},
    {Species.TapuKoko, 150}
  };

  private static readonly Dictionary<Species, PositionForms> USUMAkalaDex = new Dictionary<Species, PositionForms>() {
    {Species.Pikipek, 1},
    {Species.Trumbeak, 2},
    {Species.Toucannon, 3},
    {Species.Yungoos, 4},
    {Species.Gumshoos, 5},
    {Species.Rattata, (6, 1)},
    {Species.Raticate, (7, 1)},
    {Species.Caterpie, 8},
    {Species.Metapod, 9},
    {Species.Butterfree, 10},
    {Species.Grubbin, 11},
    {Species.Charjabug, 12},
    {Species.Vikavolt, 13},
    {Species.Bonsly, 14},
    {Species.Sudowoodo, 15},
    {Species.Happiny, 16},
    {Species.Chansey, 17},
    {Species.Blissey, 18},
    {Species.Wingull, 19},
    {Species.Pelipper, 20},
    {Species.Crabrawler, 21},
    {Species.Crabominable, 22},
    {Species.Gastly, 23},
    {Species.Haunter, 24},
    {Species.Gengar, 25},
    {Species.Zubat, 26},
    {Species.Golbat, 27},
    {Species.Crobat, 28},
    {Species.Diglett, (29, 1)},
    {Species.Dugtrio, (30, 1)},
    {Species.Oricorio, (31, 0..3)},
    {Species.Psyduck, 32},
    {Species.Golduck, 33},
    {Species.Magikarp, 34},
    {Species.Gyarados, 35},
    {Species.Barboach, 36},
    {Species.Whiscash, 37},
    {Species.Tentacool, 38},
    {Species.Tentacruel, 39},
    {Species.Finneon, 40},
    {Species.Lumineon, 41},
    {Species.Wishiwashi, (42, 0..1)},
    {Species.Luvdisc, 43},
    {Species.Corsola, 44},
    {Species.Mareanie, 45},
    {Species.Toxapex, 46},
    {Species.Remoraid, 47},
    {Species.Octillery, 48},
    {Species.Mantyke, 49},
    {Species.Mantine, 50},
    {Species.Lillipup, 51},
    {Species.Herdier, 52},
    {Species.Stoutland, 53},
    {Species.Eevee, 54},
    {Species.Vaporeon, 55},
    {Species.Jolteon, 56},
    {Species.Flareon, 57},
    {Species.Espeon, 58},
    {Species.Umbreon, 59},
    {Species.Leafeon, 60},
    {Species.Glaceon, 61},
    {Species.Sylveon, 62},
    {Species.Mareep, 63},
    {Species.Flaaffy, 64},
    {Species.Ampharos, 65},
    {Species.Mudbray, 66},
    {Species.Mudsdale, 67},
    {Species.Igglybuff, 68},
    {Species.Jigglypuff, 69},
    {Species.Wigglytuff, 70},
    {Species.Tauros, 71},
    {Species.Miltank, 72},
    {Species.Surskit, 73},
    {Species.Masquerain, 74},
    {Species.Dewpider, 75},
    {Species.Araquanid, 76},
    {Species.Fomantis, 77},
    {Species.Lurantis, 78},
    {Species.Morelull, 79},
    {Species.Shiinotic, 80},
    {Species.Paras, 81},
    {Species.Parasect, 82},
    {Species.Poliwag, 83},
    {Species.Poliwhirl, 84},
    {Species.Poliwrath, 85},
    {Species.Politoed, 86},
    {Species.Goldeen, 87},
    {Species.Seaking, 88},
    {Species.Basculin, (89, 0..1)},
    {Species.Feebas, 90},
    {Species.Milotic, 91},
    {Species.Alomomola, 92},
    {Species.Fletchling, 93},
    {Species.Fletchinder, 94},
    {Species.Talonflame, 95},
    {Species.Salandit, 96},
    {Species.Salazzle, 97},
    {Species.Cubone, 98},
    {Species.Marowak, (99, 1)},
    {Species.Kangaskhan, 100},
    {Species.Magby, 101},
    {Species.Magmar, 102},
    {Species.Magmortar, 103},
    {Species.Larvesta, 104},
    {Species.Volcarona, 105},
    {Species.Stufful, 106},
    {Species.Bewear, 107},
    {Species.Bounsweet, 108},
    {Species.Steenee, 109},
    {Species.Tsareena, 110},
    {Species.Comfey, 111},
    {Species.Pinsir, 112},
    {Species.Hoothoot, 113},
    {Species.Noctowl, 114},
    {Species.Kecleon, 115},
    {Species.Oranguru, 116},
    {Species.Passimian, 117},
    {Species.Goomy, 118},
    {Species.Sliggoo, 119},
    {Species.Goodra, 120},
    {Species.Castform, (121, 0..3)},
    {Species.Wimpod, 122},
    {Species.Golisopod, 123},
    {Species.Staryu, 124},
    {Species.Starmie, 125},
    {Species.Sandygast, 126},
    {Species.Palossand, 127},
    {Species.Omanyte, 128},
    {Species.Omastar, 129},
    {Species.Kabuto, 130},
    {Species.Kabutops, 131},
    {Species.Lileep, 132},
    {Species.Cradily, 133},
    {Species.Anorith, 134},
    {Species.Armaldo, 135},
    {Species.Cranidos, 136},
    {Species.Rampardos, 137},
    {Species.Shieldon, 138},
    {Species.Bastiodon, 139},
    {Species.Archen, 140},
    {Species.Archeops, 141},
    {Species.Tirtouga, 142},
    {Species.Carracosta, 143},
    {Species.Tyrunt, 144},
    {Species.Tyrantrum, 145},
    {Species.Amaura, 146},
    {Species.Aurorus, 147},
    {Species.Larvitar, 148},
    {Species.Pupitar, 149},
    {Species.Tyranitar, 150},
    {Species.Phantump, 151},
    {Species.Trevenant, 152},
    {Species.Natu, 153},
    {Species.Xatu, 154},
    {Species.Nosepass, 155},
    {Species.Probopass, 156},
    {Species.Pyukumuku, 157},
    {Species.Chinchou, 158},
    {Species.Lanturn, 159},
    {Species.TapuLele, 160}
  };

  private static readonly Dictionary<Species, PositionForms> USUMUlaulaDex = new Dictionary<Species, PositionForms>() {
    {Species.Pikipek, 1},
    {Species.Trumbeak, 2},
    {Species.Toucannon, 3},
    {Species.Yungoos, 4},
    {Species.Gumshoos, 5},
    {Species.Rattata, (6, 1)},
    {Species.Raticate, (7, 1)},
    {Species.Ledyba, 8},
    {Species.Ledian, 9},
    {Species.Spinarak, 10},
    {Species.Ariados, 11},
    {Species.Grubbin, 12},
    {Species.Charjabug, 13},
    {Species.Vikavolt, 14},
    {Species.Happiny, 15},
    {Species.Chansey, 16},
    {Species.Blissey, 17},
    {Species.Slowpoke, 18},
    {Species.Slowbro, 19},
    {Species.Slowking, 20},
    {Species.Wingull, 21},
    {Species.Pelipper, 22},
    {Species.Meowth, (23, 1)},
    {Species.Persian, (24, 1)},
    {Species.Magnemite, 25},
    {Species.Magneton, 26},
    {Species.Magnezone, 27},
    {Species.Grimer, (28, 1)},
    {Species.Muk, (29, 1)},
    {Species.Crabrawler, 30},
    {Species.Crabominable, 31},
    {Species.Gastly, 32},
    {Species.Haunter, 33},
    {Species.Gengar, 34},
    {Species.Zubat, 35},
    {Species.Golbat, 36},
    {Species.Crobat, 37},
    {Species.Diglett, (38, 1)},
    {Species.Dugtrio, (39, 1)},
    {Species.Spearow, 40},
    {Species.Fearow, 41},
    {Species.Oricorio, (42, 0..3)},
    {Species.Cutiefly, 43},
    {Species.Ribombee, 44},
    {Species.Flabébé, (45, 0..4)},
    {Species.Floette, (46, 0..5)},
    {Species.Florges, (47, 0..4)},
    {Species.Petilil, 48},
    {Species.Lilligant, 49},
    {Species.Cottonee, 50},
    {Species.Whimsicott, 51},
    {Species.Psyduck, 52},
    {Species.Golduck, 53},
    {Species.Magikarp, 54},
    {Species.Gyarados, 55},
    {Species.Tentacool, 56},
    {Species.Tentacruel, 57},
    {Species.Finneon, 58},
    {Species.Lumineon, 59},
    {Species.Wishiwashi, (60, 0..1)},
    {Species.Clamperl, 61},
    {Species.Huntail, 62},
    {Species.Gorebyss, 63},
    {Species.Mudbray, 64},
    {Species.Mudsdale, 65},
    {Species.Surskit, 66},
    {Species.Masquerain, 67},
    {Species.Dewpider, 68},
    {Species.Araquanid, 69},
    {Species.Morelull, 70},
    {Species.Shiinotic, 71},
    {Species.Paras, 72},
    {Species.Parasect, 73},
    {Species.Poliwag, 74},
    {Species.Poliwhirl, 75},
    {Species.Poliwrath, 76},
    {Species.Politoed, 77},
    {Species.Goldeen, 78},
    {Species.Seaking, 79},
    {Species.Basculin, (80, 0..1)},
    {Species.Goomy, 81},
    {Species.Sliggoo, 82},
    {Species.Goodra, 83},
    {Species.Castform, (84, 0..3)},
    {Species.Trubbish, 85},
    {Species.Garbodor, 86},
    {Species.Minccino, 87},
    {Species.Cinccino, 88},
    {Species.Pineco, 89},
    {Species.Forretress, 90},
    {Species.Skarmory, 91},
    {Species.Ditto, 92},
    {Species.Cleffa, 93},
    {Species.Clefairy, 94},
    {Species.Clefable, 95},
    {Species.Elgyem, 96},
    {Species.Beheeyem, 97},
    {Species.Minior, (98, 0..13)},
    {Species.Beldum, 99},
    {Species.Metang, 100},
    {Species.Metagross, 101},
    {Species.Porygon, 102},
    {Species.Porygon2, 103},
    {Species.PorygonZ, 104},
    {Species.Pancham, 105},
    {Species.Pangoro, 106},
    {Species.Komala, 107},
    {Species.Torkoal, 108},
    {Species.Turtonator, 109},
    {Species.Houndour, 110},
    {Species.Houndoom, 111},
    {Species.Dedenne, 112},
    {Species.Togedemaru, 113},
    {Species.Electrike, 114},
    {Species.Manectric, 115},
    {Species.Elekid, 116},
    {Species.Electabuzz, 117},
    {Species.Electivire, 118},
    {Species.Geodude, (119, 1)},
    {Species.Graveler, (120, 1)},
    {Species.Golem, (121, 1)},
    {Species.Sandile, 122},
    {Species.Krokorok, 123},
    {Species.Krookodile, 124},
    {Species.Trapinch, 125},
    {Species.Vibrava, 126},
    {Species.Flygon, 127},
    {Species.Gible, 128},
    {Species.Gabite, 129},
    {Species.Garchomp, 130},
    {Species.Baltoy, 131},
    {Species.Claydol, 132},
    {Species.Golett, 133},
    {Species.Golurk, 134},
    {Species.Klefki, 135},
    {Species.Mimikyu, (136, 0..1)},
    {Species.Shuppet, 137},
    {Species.Banette, 138},
    {Species.Frillish, 139},
    {Species.Jellicent, 140},
    {Species.Bruxish, 141},
    {Species.Drampa, 142},
    {Species.Absol, 143},
    {Species.Snorunt, 144},
    {Species.Glalie, 145},
    {Species.Froslass, 146},
    {Species.Sneasel, 147},
    {Species.Weavile, 148},
    {Species.Sandshrew, (149, 1)},
    {Species.Sandslash, (150, 1)},
    {Species.Vulpix, (151, 1)},
    {Species.Ninetales, (152, 1)},
    {Species.Vanillite, 153},
    {Species.Vanillish, 154},
    {Species.Vanilluxe, 155},
    {Species.Scraggy, 156},
    {Species.Scrafty, 157},
    {Species.Pawniard, 158},
    {Species.Bisharp, 159},
    {Species.TapuBulu, 160}
  };

  private static readonly Dictionary<Species, PositionForms> USUMPoniDex = new Dictionary<Species, PositionForms>() {
    {Species.Pikipek, 1},
    {Species.Trumbeak, 2},
    {Species.Toucannon, 3},
    {Species.Yungoos, 4},
    {Species.Gumshoos, 5},
    {Species.Rattata, 6},
    {Species.Raticate, 7},
    {Species.Buneary, 8},
    {Species.Lopunny, 9},
    {Species.Inkay, 10},
    {Species.Malamar, 11},
    {Species.Zorua, 12},
    {Species.Zoroark, 13},
    {Species.Furfrou, (14, 0..9)},
    {Species.Happiny, 15},
    {Species.Chansey, 16},
    {Species.Blissey, 17},
    {Species.Wingull, 18},
    {Species.Pelipper, 19},
    {Species.Drowzee, 20},
    {Species.Hypno, 21},
    {Species.Makuhita, 22},
    {Species.Hariyama, 23},
    {Species.Crabrawler, 24},
    {Species.Crabominable, 25},
    {Species.Zubat, 26},
    {Species.Golbat, 27},
    {Species.Crobat, 28},
    {Species.Noibat, 29},
    {Species.Noivern, 30},
    {Species.Diglett, (31, 1)},
    {Species.Dugtrio, (32, 1)},
    {Species.Spearow, 33},
    {Species.Fearow, 34},
    {Species.Rufflet, 35},
    {Species.Braviary, 36},
    {Species.Vullaby, 37},
    {Species.Mandibuzz, 38},
    {Species.Mankey, 39},
    {Species.Primeape, 40},
    {Species.Oricorio, (41, 0..3)},
    {Species.Cutiefly, 42},
    {Species.Ribombee, 43},
    {Species.Flabébé, (44, 0..4)},
    {Species.Floette, (45, 0..5)},
    {Species.Florges, (46, 0..4)},
    {Species.Petilil, 47},
    {Species.Lilligant, 48},
    {Species.Cottonee, 49},
    {Species.Whimsicott, 50},
    {Species.Psyduck, 51},
    {Species.Golduck, 52},
    {Species.Magikarp, 53},
    {Species.Gyarados, 54},
    {Species.Barboach, 55},
    {Species.Whiscash, 56},
    {Species.Machop, 57},
    {Species.Machoke, 58},
    {Species.Machamp, 59},
    {Species.Roggenrola, 60},
    {Species.Boldore, 61},
    {Species.Gigalith, 62},
    {Species.Carbink, 63},
    {Species.Sableye, 64},
    {Species.Rockruff, (65, 0..1)},
    {Species.Lycanroc, (66, 0..2)},
    {Species.Tentacool, 67},
    {Species.Tentacruel, 68},
    {Species.Finneon, 69},
    {Species.Lumineon, 70},
    {Species.Mudbray, 71},
    {Species.Mudsdale, 72},
    {Species.Tauros, 73},
    {Species.Miltank, 74},
    {Species.Basculin, (75, 0..1)},
    {Species.Stufful, 76},
    {Species.Bewear, 77},
    {Species.Pinsir, 78},
    {Species.Goomy, 79},
    {Species.Sliggoo, 80},
    {Species.Goodra, 81},
    {Species.Castform, (82, 0..3)},
    {Species.Wimpod, 83},
    {Species.Golisopod, 84},
    {Species.Skarmory, 85},
    {Species.Snubbull, 86},
    {Species.Granbull, 87},
    {Species.Shellos , (88, 0..1)},
    {Species.Gastrodon, (89, 0..1)},
    {Species.Relicanth, 90},
    {Species.Dhelmise, 91},
    {Species.Carvanha, 92},
    {Species.Sharpedo, 93},
    {Species.Skrelp, 94},
    {Species.Dragalge, 95},
    {Species.Clauncher, 96},
    {Species.Clawitzer, 97},
    {Species.Wailmer, 98},
    {Species.Wailord, 99},
    {Species.Lapras, 100},
    {Species.Tropius, 101},
    {Species.Exeggcute, 102},
    {Species.Exeggutor, (103, 1)},
    {Species.Corphish, 104},
    {Species.Crawdaunt, 105},
    {Species.Mienfoo, 106},
    {Species.Mienshao, 107},
    {Species.Jangmoo, 108},
    {Species.Hakamoo, 109},
    {Species.Kommoo, 110},
    {Species.Emolga, 111},
    {Species.Scyther, 112},
    {Species.Scizor, 113},
    {Species.Heracross, 114},
    {Species.Aipom, 115},
    {Species.Ambipom, 116},
    {Species.Litleo, 117},
    {Species.Pyroar, 118},
    {Species.Misdreavus, 119},
    {Species.Mismagius, 120},
    {Species.Druddigon, 121},
    {Species.Lickitung, 122},
    {Species.Lickilicky, 123},
    {Species.Riolu, 124},
    {Species.Lucario, 125},
    {Species.Dratini, 126},
    {Species.Dragonair, 127},
    {Species.Dragonite, 128},
    {Species.Aerodactyl, 129},
    {Species.TapuFini, 130}
  };

  public static Func<PKM, IComparable>[] GetSMSortFunctions() {
    return GenerateSortingFunctions(SMFullDex);
  }

  public static Func<PKM, IComparable>[] GetSMMelemeleSortFunctions() {
    return GenerateSortingFunctions(SMMelemeleDex);
  }

  public static Func<PKM, IComparable>[] GetSMAkalaSortFunctions() {
    return GenerateSortingFunctions(SMAkalaDex);
  }

  public static Func<PKM, IComparable>[] GetSMUlaulaSortFunctions() {
    return GenerateSortingFunctions(SMUlaulaDex);
  }

  public static Func<PKM, IComparable>[] GetSMPoniSortFunctions() {
    return GenerateSortingFunctions(SMPoniDex);
  }

  public static Func<PKM, IComparable>[] GetUSUMSortFunctions() {
    return GenerateSortingFunctions(USUMFullDex);
  }

  public static Func<PKM, IComparable>[] GetUSUMMelemeleSortFunctions() {
    return GenerateSortingFunctions(USUMMelemeleDex);
  }

  public static Func<PKM, IComparable>[] GetUSUMAkalaSortFunctions() {
    return GenerateSortingFunctions(USUMAkalaDex);
  }

  public static Func<PKM, IComparable>[] GetUSUMUlaulaSortFunctions() {
    return GenerateSortingFunctions(USUMUlaulaDex);
  }

  public static Func<PKM, IComparable>[] GetUSUMPoniSortFunctions() {
    return GenerateSortingFunctions(USUMPoniDex);
  }

}
