using PKHeX.Core;

namespace PluginPile.Sorting;
internal class Gen8Galar : SortingBase {

  private static readonly Dictionary<Species, PositionForms> GalarDex = new Dictionary<Species, PositionForms>() {
    {Species.Grookey, 1},
    {Species.Thwackey, 2},
    {Species.Rillaboom, 3},
    {Species.Scorbunny, 4},
    {Species.Raboot, 5},
    {Species.Cinderace, 6},
    {Species.Sobble, 7},
    {Species.Drizzile, 8},
    {Species.Inteleon, 9},
    {Species.Blipbug, 10},
    {Species.Dottler, 11},
    {Species.Orbeetle, 12},
    {Species.Caterpie, 13},
    {Species.Metapod, 14},
    {Species.Butterfree, 15},
    {Species.Grubbin, 16},
    {Species.Charjabug, 17},
    {Species.Vikavolt, 18},
    {Species.Hoothoot, 19},
    {Species.Noctowl, 20},
    {Species.Rookidee, 21},
    {Species.Corvisquire, 22},
    {Species.Corviknight, 23},
    {Species.Skwovet, 24},
    {Species.Greedent, 25},
    {Species.Pidove, 26},
    {Species.Tranquill, 27},
    {Species.Unfezant, 28},
    {Species.Nickit, 29},
    {Species.Thievul, 30},
    {Species.Zigzagoon, (31, 1)},
    {Species.Linoone, (32, 1)},
    {Species.Obstagoon, 33},
    {Species.Wooloo, 34},
    {Species.Dubwool, 35},
    {Species.Lotad, 36},
    {Species.Lombre, 37},
    {Species.Ludicolo, 38},
    {Species.Seedot, 39},
    {Species.Nuzleaf, 40},
    {Species.Shiftry, 41},
    {Species.Chewtle, 42},
    {Species.Drednaw, 43},
    {Species.Purrloin, 44},
    {Species.Liepard, 45},
    {Species.Yamper, 46},
    {Species.Boltund, 47},
    {Species.Bunnelby, 48},
    {Species.Diggersby, 49},
    {Species.Minccino, 50},
    {Species.Cinccino, 51},
    {Species.Bounsweet, 52},
    {Species.Steenee, 53},
    {Species.Tsareena, 54},
    {Species.Oddish, 55},
    {Species.Gloom, 56},
    {Species.Vileplume, 57},
    {Species.Bellossom, 58},
    {Species.Budew, 59},
    {Species.Roselia, 60},
    {Species.Roserade, 61},
    {Species.Wingull, 62},
    {Species.Pelipper, 63},
    {Species.Joltik, 64},
    {Species.Galvantula, 65},
    {Species.Electrike, 66},
    {Species.Manectric, 67},
    {Species.Vulpix, 68},
    {Species.Ninetales, 69},
    {Species.Growlithe, 70},
    {Species.Arcanine, 71},
    {Species.Vanillite, 72},
    {Species.Vanillish, 73},
    {Species.Vanilluxe, 74},
    {Species.Swinub, 75},
    {Species.Piloswine, 76},
    {Species.Mamoswine, 77},
    {Species.Delibird, 78},
    {Species.Snorunt, 79},
    {Species.Glalie, 80},
    {Species.Froslass, 81},
    {Species.Baltoy, 82},
    {Species.Claydol, 83},
    {Species.Mudbray, 84},
    {Species.Mudsdale, 85},
    {Species.Dwebble, 86},
    {Species.Crustle, 87},
    {Species.Golett, 88},
    {Species.Golurk, 89},
    {Species.Munna, 90},
    {Species.Musharna, 91},
    {Species.Natu, 92},
    {Species.Xatu, 93},
    {Species.Stufful, 94},
    {Species.Bewear, 95},
    {Species.Snover, 96},
    {Species.Abomasnow, 97},
    {Species.Krabby, 98},
    {Species.Kingler, 99},
    {Species.Wooper, 100},
    {Species.Quagsire, 101},
    {Species.Corphish, 102},
    {Species.Crawdaunt, 103},
    {Species.Nincada, 104},
    {Species.Ninjask, 105},
    {Species.Shedinja, 106},
    {Species.Tyrogue, 107},
    {Species.Hitmonlee, 108},
    {Species.Hitmonchan, 109},
    {Species.Hitmontop, 110},
    {Species.Pancham, 111},
    {Species.Pangoro, 112},
    {Species.Klink, 113},
    {Species.Klang, 114},
    {Species.Klinklang, 115},
    {Species.Combee, 116},
    {Species.Vespiquen, 117},
    {Species.Bronzor, 118},
    {Species.Bronzong, 119},
    {Species.Ralts, 120},
    {Species.Kirlia, 121},
    {Species.Gardevoir, 122},
    {Species.Gallade, 123},
    {Species.Drifloon, 124},
    {Species.Drifblim, 125},
    {Species.Gossifleur, 126},
    {Species.Eldegoss, 127},
    {Species.Cherubi, 128},
    {Species.Cherrim, (129, 0..1)},
    {Species.Stunky, 130},
    {Species.Skuntank, 131},
    {Species.Tympole, 132},
    {Species.Palpitoad, 133},
    {Species.Seismitoad, 134},
    {Species.Duskull, 135},
    {Species.Dusclops, 136},
    {Species.Dusknoir, 137},
    {Species.Machop, 138},
    {Species.Machoke, 139},
    {Species.Machamp, 140},
    {Species.Gastly, 141},
    {Species.Haunter, 142},
    {Species.Gengar, 143},
    {Species.Magikarp, 144},
    {Species.Gyarados, 145},
    {Species.Goldeen, 146},
    {Species.Seaking, 147},
    {Species.Remoraid, 148},
    {Species.Octillery, 149},
    {Species.Shellder, 150},
    {Species.Cloyster, 151},
    {Species.Feebas, 152},
    {Species.Milotic, 153},
    {Species.Basculin, (154, 0..1)},
    {Species.Wishiwashi, (155, 0..1)},
    {Species.Pyukumuku, 156},
    {Species.Trubbish, 157},
    {Species.Garbodor, 158},
    {Species.Sizzlipede, 159},
    {Species.Centiskorch, 160},
    {Species.Rolycoly, 161},
    {Species.Carkol, 162},
    {Species.Coalossal, 163},
    {Species.Diglett, 164},
    {Species.Dugtrio, 165},
    {Species.Drilbur, 166},
    {Species.Excadrill, 167},
    {Species.Roggenrola, 168},
    {Species.Boldore, 169},
    {Species.Gigalith, 170},
    {Species.Timburr, 171},
    {Species.Gurdurr, 172},
    {Species.Conkeldurr, 173},
    {Species.Woobat, 174},
    {Species.Swoobat, 175},
    {Species.Noibat, 176},
    {Species.Noivern, 177},
    {Species.Onix, 178},
    {Species.Steelix, 179},
    {Species.Arrokuda, 180},
    {Species.Barraskewda, 181},
    {Species.Meowth, (182, new HashSet<int>() { 2, 0 })},
    {Species.Perrserker, 183},
    {Species.Persian, 184},
    {Species.Milcery, 185},
    {Species.Alcremie, (186, 0..8)},
    {Species.Cutiefly, 187},
    {Species.Ribombee, 188},
    {Species.Ferroseed, 189},
    {Species.Ferrothorn, 190},
    {Species.Pumpkaboo, (191, 0..3)},
    {Species.Gourgeist, (192, 0..3)},
    {Species.Pichu, 193},
    {Species.Pikachu, 194},
    {Species.Raichu, 195},
    {Species.Eevee, 196},
    {Species.Vaporeon, 197},
    {Species.Jolteon, 198},
    {Species.Flareon, 199},
    {Species.Espeon, 200},
    {Species.Umbreon, 201},
    {Species.Leafeon, 202},
    {Species.Glaceon, 203},
    {Species.Sylveon, 204},
    {Species.Applin, 205},
    {Species.Flapple, 206},
    {Species.Appletun, 207},
    {Species.Espurr, 208},
    {Species.Meowstic, (209, 0..1)},
    {Species.Swirlix, 210},
    {Species.Slurpuff, 211},
    {Species.Spritzee, 212},
    {Species.Aromatisse, 213},
    {Species.Dewpider, 214},
    {Species.Araquanid, 215},
    {Species.Wynaut, 216},
    {Species.Wobbuffet, 217},
    {Species.Farfetchd, (218, 1)},
    {Species.Sirfetchd, 219},
    {Species.Chinchou, 220},
    {Species.Lanturn, 221},
    {Species.Croagunk, 222},
    {Species.Toxicroak, 223},
    {Species.Scraggy, 224},
    {Species.Scrafty, 225},
    {Species.Stunfisk , (226, 1)},
    {Species.Shuckle, 227},
    {Species.Barboach, 228},
    {Species.Whiscash, 229},
    {Species.Shellos, (230, 0..1)},
    {Species.Gastrodon, (231, 0..1)},
    {Species.Wimpod, 232},
    {Species.Golisopod, 233},
    {Species.Binacle, 234},
    {Species.Barbaracle, 235},
    {Species.Corsola, (236, 1)},
    {Species.Cursola, 237},
    {Species.Impidimp, 238},
    {Species.Morgrem, 239},
    {Species.Grimmsnarl, 240},
    {Species.Hatenna, 241},
    {Species.Hattrem, 242},
    {Species.Hatterene, 243},
    {Species.Salandit, 244},
    {Species.Salazzle, 245},
    {Species.Pawniard, 246},
    {Species.Bisharp, 247},
    {Species.Throh, 248},
    {Species.Sawk, 249},
    {Species.Koffing, 250},
    {Species.Weezing, (251, 1)},
    {Species.Bonsly, 252},
    {Species.Sudowoodo, 253},
    {Species.Cleffa, 254},
    {Species.Clefairy, 255},
    {Species.Clefable, 256},
    {Species.Togepi, 257},
    {Species.Togetic, 258},
    {Species.Togekiss, 259},
    {Species.Munchlax, 260},
    {Species.Snorlax, 261},
    {Species.Cottonee, 262},
    {Species.Whimsicott, 263},
    {Species.Rhyhorn, 264},
    {Species.Rhydon, 265},
    {Species.Rhyperior, 266},
    {Species.Gothita, 267},
    {Species.Gothorita, 268},
    {Species.Gothitelle, 269},
    {Species.Solosis, 270},
    {Species.Duosion, 271},
    {Species.Reuniclus, 272},
    {Species.Karrablast, 273},
    {Species.Escavalier, 274},
    {Species.Shelmet, 275},
    {Species.Accelgor, 276},
    {Species.Elgyem, 277},
    {Species.Beheeyem, 278},
    {Species.Cubchoo, 279},
    {Species.Beartic, 280},
    {Species.Rufflet, 281},
    {Species.Braviary, 282},
    {Species.Vullaby, 283},
    {Species.Mandibuzz, 284},
    {Species.Skorupi, 285},
    {Species.Drapion, 286},
    {Species.Litwick, 287},
    {Species.Lampent, 288},
    {Species.Chandelure, 289},
    {Species.Inkay, 290},
    {Species.Malamar, 291},
    {Species.Sneasel, 292},
    {Species.Weavile, 293},
    {Species.Sableye, 294},
    {Species.Mawile, 295},
    {Species.Maractus, 296},
    {Species.Sigilyph, 297},
    {Species.Riolu, 298},
    {Species.Lucario, 299},
    {Species.Torkoal, 300},
    {Species.Mimikyu, (301, 0..1)},
    {Species.Cufant, 302},
    {Species.Copperajah, 303},
    {Species.Qwilfish, 304},
    {Species.Frillish, 305},
    {Species.Jellicent, 306},
    {Species.Mareanie, 307},
    {Species.Toxapex, 308},
    {Species.Cramorant, (309, 0..2)},
    {Species.Toxel, 310},
    {Species.Toxtricity, (311, 0..1)},
    {Species.Silicobra, 312},
    {Species.Sandaconda, 313},
    {Species.Hippopotas, 314},
    {Species.Hippowdon, 315},
    {Species.Durant, 316},
    {Species.Heatmor, 317},
    {Species.Helioptile, 318},
    {Species.Heliolisk, 319},
    {Species.Hawlucha, 320},
    {Species.Trapinch, 321},
    {Species.Vibrava, 322},
    {Species.Flygon, 323},
    {Species.Axew, 324},
    {Species.Fraxure, 325},
    {Species.Haxorus, 326},
    {Species.Yamask, 327},
    {Species.Runerigus, 328},
    {Species.Cofagrigus, 329},
    {Species.Honedge, 330},
    {Species.Doublade, 331},
    {Species.Aegislash, (332, 0..1)},
    {Species.Ponyta, (333, 1)},
    {Species.Rapidash, (334, 1)},
    {Species.Sinistea, (335, 0..1)},
    {Species.Polteageist, (336, 0..1)},
    {Species.Indeedee, (337, 0..1)},
    {Species.Phantump, 338},
    {Species.Trevenant, 339},
    {Species.Morelull, 340},
    {Species.Shiinotic, 341},
    {Species.Oranguru, 342},
    {Species.Passimian, 343},
    {Species.Morpeko, (344, 0..1)},
    {Species.Falinks, 345},
    {Species.Drampa, 346},
    {Species.Turtonator, 347},
    {Species.Togedemaru, 348},
    {Species.Snom, 349},
    {Species.Frosmoth, 350},
    {Species.Clobbopus, 351},
    {Species.Grapploct, 352},
    {Species.Pincurchin, 353},
    {Species.Mantyke, 354},
    {Species.Mantine, 355},
    {Species.Wailmer, 356},
    {Species.Wailord, 357},
    {Species.Bergmite, 358},
    {Species.Avalugg, 359},
    {Species.Dhelmise, 360},
    {Species.Lapras, 361},
    {Species.Lunatone, 362},
    {Species.Solrock, 363},
    {Species.MimeJr, 364},
    {Species.MrMime, (365, 1)},
    {Species.MrRime, 366},
    {Species.Darumaka, (367, 1)},
    {Species.Darmanitan, (368, 2..3)},
    {Species.Stonjourner, 369},
    {Species.Eiscue, (370, 0..1)},
    {Species.Duraludon, 371},
    {Species.Rotom, (372, 0..5)},
    {Species.Ditto, 373},
    {Species.Dracozolt, 374},
    {Species.Arctozolt, 375},
    {Species.Dracovish, 376},
    {Species.Arctovish, 377},
    {Species.Charmander, 378},
    {Species.Charmeleon, 379},
    {Species.Charizard, 380},
    {Species.TypeNull, 381},
    {Species.Silvally, (382, 0..17)},
    {Species.Larvitar, 383},
    {Species.Pupitar, 384},
    {Species.Tyranitar, 385},
    {Species.Deino, 386},
    {Species.Zweilous, 387},
    {Species.Hydreigon, 388},
    {Species.Goomy, 389},
    {Species.Sliggoo, 390},
    {Species.Goodra, 391},
    {Species.Jangmoo, 392},
    {Species.Hakamoo, 393},
    {Species.Kommoo, 394},
    {Species.Dreepy, 395},
    {Species.Drakloak, 396},
    {Species.Dragapult, 397},
    {Species.Zacian, (398, 0..1)},
    {Species.Zamazenta, (399, 0..1)},
    {Species.Eternatus, (400, 0..1)},
  };

  private static readonly Dictionary<Species, PositionForms> IsleOfArmorDex = new Dictionary<Species, PositionForms>() {
    {Species.Slowpoke, (1, 1)},
    {Species.Slowbro, (2, 2)},
    {Species.Slowking, (3, 1)},
    {Species.Buneary, 4},
    {Species.Lopunny, 5},
    {Species.Happiny, 6},
    {Species.Chansey, 7},
    {Species.Blissey, 8},
    {Species.Skwovet, 9},
    {Species.Greedent, 10},
    {Species.Igglybuff, 11},
    {Species.Jigglypuff, 12},
    {Species.Wigglytuff, 13},
    {Species.Blipbug, 14},
    {Species.Dottler, 15},
    {Species.Orbeetle, 16},
    {Species.Fomantis, 17},
    {Species.Lurantis, 18},
    {Species.Applin, 19},
    {Species.Flapple, 20},
    {Species.Appletun, 21},
    {Species.Fletchling, 22},
    {Species.Fletchinder, 23},
    {Species.Talonflame, 24},
    {Species.Shinx, 25},
    {Species.Luxio, 26},
    {Species.Luxray, 27},
    {Species.Klefki, 28},
    {Species.Pawniard, 29},
    {Species.Bisharp, 30},
    {Species.Abra, 31},
    {Species.Kadabra, 32},
    {Species.Alakazam, 33},
    {Species.Ralts, 34},
    {Species.Kirlia, 35},
    {Species.Gardevoir, 36},
    {Species.Gallade, 37},
    {Species.Krabby, 38},
    {Species.Kingler, 39},
    {Species.Tentacool, 40},
    {Species.Tentacruel, 41},
    {Species.Magikarp, 42},
    {Species.Gyarados, 43},
    {Species.Remoraid, 44},
    {Species.Octillery, 45},
    {Species.Mantyke, 46},
    {Species.Mantine, 47},
    {Species.Wingull, 48},
    {Species.Pelipper, 49},
    {Species.Skorupi, 50},
    {Species.Drapion, 51},
    {Species.Dunsparce, 52},
    {Species.Bouffalant, 53},
    {Species.Lickitung, 54},
    {Species.Lickilicky, 55},
    {Species.Chewtle, 56},
    {Species.Drednaw, 57},
    {Species.Wooper, 58},
    {Species.Quagsire, 59},
    {Species.Goomy, 60},
    {Species.Sliggoo, 61},
    {Species.Goodra, 62},
    {Species.Druddigon, 63},
    {Species.Shelmet, 64},
    {Species.Accelgor, 65},
    {Species.Karrablast, 66},
    {Species.Escavalier, 67},
    {Species.Bulbasaur, 68},
    {Species.Ivysaur, 69},
    {Species.Venusaur, 70},
    {Species.Squirtle, 71},
    {Species.Wartortle, 72},
    {Species.Blastoise, 73},
    {Species.Venipede, 74},
    {Species.Whirlipede, 75},
    {Species.Scolipede, 76},
    {Species.Foongus, 77},
    {Species.Amoonguss, 78},
    {Species.Comfey, 79},
    {Species.Tangela, 80},
    {Species.Tangrowth, 81},
    {Species.Croagunk, 82},
    {Species.Toxicroak, 83},
    {Species.Pichu, 84},
    {Species.Pikachu, 85},
    {Species.Raichu, 86},
    {Species.Zorua, 87},
    {Species.Zoroark, 88},
    {Species.Oranguru, 89},
    {Species.Passimian, 90},
    {Species.Corphish, 91},
    {Species.Crawdaunt, 92},
    {Species.Cramorant, (93, 0..2)},
    {Species.Goldeen, 94},
    {Species.Seaking, 95},
    {Species.Arrokuda, 96},
    {Species.Barraskewda, 97},
    {Species.Staryu, 98},
    {Species.Starmie, 99},
    {Species.Kubfu, 100},
    {Species.Urshifu, (101, 0..1)},
    {Species.Emolga, 102},
    {Species.Dedenne, 103},
    {Species.Morpeko, (104, 0..1)},
    {Species.Magnemite, 105},
    {Species.Magneton, 106},
    {Species.Magnezone, 107},
    {Species.Inkay, 108},
    {Species.Malamar, 109},
    {Species.Wishiwashi, (110, 0..1)},
    {Species.Carvanha, 111},
    {Species.Sharpedo, 112},
    {Species.Lillipup, 113},
    {Species.Herdier, 114},
    {Species.Stoutland, 115},
    {Species.Tauros, 116},
    {Species.Miltank, 117},
    {Species.Scyther, 118},
    {Species.Scizor, 119},
    {Species.Pinsir, 120},
    {Species.Heracross, 121},
    {Species.Dwebble, 122},
    {Species.Crustle, 123},
    {Species.Wimpod, 124},
    {Species.Golisopod, 125},
    {Species.Pincurchin, 126},
    {Species.Mareanie, 127},
    {Species.Toxapex, 128},
    {Species.Clobbopus, 129},
    {Species.Grapploct, 130},
    {Species.Shellder, 131},
    {Species.Cloyster, 132},
    {Species.Sandygast, 133},
    {Species.Palossand, 134},
    {Species.Drifloon, 135},
    {Species.Drifblim, 136},
    {Species.Barboach, 137},
    {Species.Whiscash, 138},
    {Species.Azurill, 139},
    {Species.Marill, 140},
    {Species.Azumarill, 141},
    {Species.Poliwag, 142},
    {Species.Poliwhirl, 143},
    {Species.Poliwrath, 144},
    {Species.Politoed, 145},
    {Species.Psyduck, 146},
    {Species.Golduck, 147},
    {Species.Whismur, 148},
    {Species.Loudred, 149},
    {Species.Exploud, 150},
    {Species.Woobat, 151},
    {Species.Swoobat, 152},
    {Species.Skarmory, 153},
    {Species.Roggenrola, 154},
    {Species.Boldore, 155},
    {Species.Gigalith, 156},
    {Species.Rockruff, (157, 0..1)},
    {Species.Lycanroc, (158, 0..2)},
    {Species.Salandit, 159},
    {Species.Salazzle, 160},
    {Species.Scraggy, 161},
    {Species.Scrafty, 162},
    {Species.Mienfoo, 163},
    {Species.Mienshao, 164},
    {Species.Jangmoo, 165},
    {Species.Hakamoo, 166},
    {Species.Kommoo, 167},
    {Species.Sandshrew, 168},
    {Species.Sandslash, 169},
    {Species.Cubone, 170},
    {Species.Marowak, 171},
    {Species.Kangaskhan, 172},
    {Species.Torkoal, 173},
    {Species.Silicobra, 174},
    {Species.Sandaconda, 175},
    {Species.Sandile, 176},
    {Species.Krokorok, 177},
    {Species.Krookodile, 178},
    {Species.Rufflet, 179},
    {Species.Braviary, 180},
    {Species.Vullaby, 181},
    {Species.Mandibuzz, 182},
    {Species.Rhyhorn, 183},
    {Species.Rhydon, 184},
    {Species.Rhyperior, 185},
    {Species.Larvesta, 186},
    {Species.Volcarona, 187},
    {Species.Chinchou, 188},
    {Species.Lanturn, 189},
    {Species.Wailmer, 190},
    {Species.Wailord, 191},
    {Species.Frillish, 192},
    {Species.Jellicent, 193},
    {Species.Skrelp, 194},
    {Species.Dragalge, 195},
    {Species.Clauncher, 196},
    {Species.Clawitzer, 197},
    {Species.Horsea, 198},
    {Species.Seadra, 199},
    {Species.Kingdra, 200},
    {Species.Petilil, 201},
    {Species.Lilligant, 202},
    {Species.Combee, 203},
    {Species.Vespiquen, 204},
    {Species.Exeggcute, 205},
    {Species.Exeggutor, 206},
    {Species.Ditto, 207},
    {Species.Porygon, 208},
    {Species.Porygon2, 209},
    {Species.PorygonZ, 210},
    {Species.Zarude, (211, 0..1)},
  };

  private static readonly Dictionary<Species, PositionForms> CrownTundraDex = new Dictionary<Species, PositionForms>() {
    {Species.Snom, 1},
    {Species.Frosmoth, 2},
    {Species.Wooloo, 3},
    {Species.Dubwool, 4},
    {Species.Skwovet, 5},
    {Species.Greedent, 6},
    {Species.Swinub, 7},
    {Species.Piloswine, 8},
    {Species.Mamoswine, 9},
    {Species.MimeJr, 10},
    {Species.MrMime, (11, 1)},
    {Species.MrRime, 12},
    {Species.Smoochum, 13},
    {Species.Jynx, 14},
    {Species.Elekid, 15},
    {Species.Electabuzz, 16},
    {Species.Electivire, 17},
    {Species.Magby, 18},
    {Species.Magmar, 19},
    {Species.Magmortar, 20},
    {Species.Audino, 21},
    {Species.Vanillite, 22},
    {Species.Vanillish, 23},
    {Species.Vanilluxe, 24},
    {Species.Snorunt, 25},
    {Species.Glalie, 26},
    {Species.Froslass, 27},
    {Species.Sneasel, 28},
    {Species.Weavile, 29},
    {Species.Cryogonal, 30},
    {Species.Snover, 31},
    {Species.Abomasnow, 32},
    {Species.Phantump, 33},
    {Species.Trevenant, 34},
    {Species.Swablu, 35},
    {Species.Altaria, 36},
    {Species.Impidimp, 37},
    {Species.Morgrem, 38},
    {Species.Grimmsnarl, 39},
    {Species.Hatenna, 40},
    {Species.Hattrem, 41},
    {Species.Hatterene, 42},
    {Species.Cleffa, 43},
    {Species.Clefairy, 44},
    {Species.Clefable, 45},
    {Species.Mimikyu, (46, 0..1)},
    {Species.Spiritomb, 47},
    {Species.Litwick, 48},
    {Species.Lampent, 49},
    {Species.Chandelure, 50},
    {Species.Gothita, 51},
    {Species.Gothorita, 52},
    {Species.Gothitelle, 53},
    {Species.Solosis, 54},
    {Species.Duosion, 55},
    {Species.Reuniclus, 56},
    {Species.Timburr, 57},
    {Species.Gurdurr, 58},
    {Species.Conkeldurr, 59},
    {Species.Barboach, 60},
    {Species.Whiscash, 61},
    {Species.Magikarp, 62},
    {Species.Gyarados, 63},
    {Species.Basculin, (64, 0..1)},
    {Species.NidoranF, 65},
    {Species.Nidorina, 66},
    {Species.Nidoqueen, 67},
    {Species.NidoranM, 68},
    {Species.Nidorino, 69},
    {Species.Nidoking, 70},
    {Species.Zigzagoon, (71, 1)},
    {Species.Linoone, (72, 1)},
    {Species.Obstagoon, 73},
    {Species.Eevee, 74},
    {Species.Vaporeon, 75},
    {Species.Jolteon, 76},
    {Species.Flareon, 77},
    {Species.Umbreon, 78},
    {Species.Espeon, 79},
    {Species.Glaceon, 80},
    {Species.Leafeon, 81},
    {Species.Sylveon, 82},
    {Species.Tyrunt, 83},
    {Species.Tyrantrum, 84},
    {Species.Amaura, 85},
    {Species.Aurorus, 86},
    {Species.Bronzor, 87},
    {Species.Bronzong, 88},
    {Species.Stonjourner, 89},
    {Species.Eiscue, (90, 0..1)},
    {Species.Dewpider, 91},
    {Species.Araquanid, 92},
    {Species.Joltik, 93},
    {Species.Galvantula, 94},
    {Species.Karrablast, 95},
    {Species.Escavalier, 96},
    {Species.Shelmet, 97},
    {Species.Accelgor, 98},
    {Species.Sizzlipede, 99},
    {Species.Centiskorch, 100},
    {Species.Durant, 101},
    {Species.Heatmor, 102},
    {Species.Darumaka, 103},
    {Species.Darmanitan, 104},
    {Species.Ponyta, (105, 1)},
    {Species.Rapidash, (106, 1)},
    {Species.Absol, 107},
    {Species.Cufant, 108},
    {Species.Copperajah, 109},
    {Species.Dreepy, 110},
    {Species.Drakloak, 111},
    {Species.Dragapult, 112},
    {Species.Bagon, 113},
    {Species.Shelgon, 114},
    {Species.Salamence, 115},
    {Species.Gible, 116},
    {Species.Gabite, 117},
    {Species.Garchomp, 118},
    {Species.Druddigon, 119},
    {Species.Delibird, 120},
    {Species.Cubchoo, 121},
    {Species.Beartic, 122},
    {Species.Omanyte, 123},
    {Species.Omastar, 124},
    {Species.Kabuto, 125},
    {Species.Kabutops, 126},
    {Species.Aerodactyl, 127},
    {Species.Carbink, 128},
    {Species.Beldum, 129},
    {Species.Metang, 130},
    {Species.Metagross, 131},
    {Species.Sinistea, (132, 0..1)},
    {Species.Polteageist, (133, 0..1)},
    {Species.Riolu, 134},
    {Species.Lucario, 135},
    {Species.Deino, 136},
    {Species.Zweilous, 137},
    {Species.Hydreigon, 138},
    {Species.Larvitar, 139},
    {Species.Pupitar, 140},
    {Species.Tyranitar, 141},
    {Species.Bergmite, 142},
    {Species.Avalugg, 143},
    {Species.Zubat, 144},
    {Species.Golbat, 145},
    {Species.Crobat, 146},
    {Species.Tirtouga, 147},
    {Species.Carracosta, 148},
    {Species.Archen, 149},
    {Species.Archeops, 150},
    {Species.Baltoy, 151},
    {Species.Claydol, 152},
    {Species.Golett, 153},
    {Species.Golurk, 154},
    {Species.Yamper, 155},
    {Species.Boltund, 156},
    {Species.Morpeko, (157, 0..1)},
    {Species.Pincurchin, 158},
    {Species.Spheal, 159},
    {Species.Sealeo, 160},
    {Species.Walrein, 161},
    {Species.Dhelmise, 162},
    {Species.Rookidee, 163},
    {Species.Corvisquire, 164},
    {Species.Corviknight, 165},
    {Species.Gossifleur, 166},
    {Species.Eldegoss, 167},
    {Species.Cottonee, 168},
    {Species.Whimsicott, 169},
    {Species.Shuckle, 170},
    {Species.Indeedee, (171, 0..1)},
    {Species.Munchlax, 172},
    {Species.Snorlax, 173},
    {Species.Sableye, 174},
    {Species.Mawile, 175},
    {Species.Rolycoly, 176},
    {Species.Carkol, 177},
    {Species.Coalossal, 178},
    {Species.Ferroseed, 179},
    {Species.Ferrothorn, 180},
    {Species.Noibat, 181},
    {Species.Noivern, 182},
    {Species.Lileep, 183},
    {Species.Cradily, 184},
    {Species.Anorith, 185},
    {Species.Armaldo, 186},
    {Species.Relicanth, 187},
    {Species.Feebas, 188},
    {Species.Milotic, 189},
    {Species.Lapras, 190},
    {Species.Aron, 191},
    {Species.Lairon, 192},
    {Species.Aggron, 193},
    {Species.Dratini, 194},
    {Species.Dragonair, 195},
    {Species.Dragonite, 196},
    {Species.Regirock, 197},
    {Species.Regice, 198},
    {Species.Registeel, 199},
    {Species.Regieleki, 200},
    {Species.Regidrago, 201},
    {Species.Articuno, (202, 1)},
    {Species.Zapdos, (203, 1)},
    {Species.Moltres, (204, 1)},
    {Species.Cobalion, 205},
    {Species.Terrakion, 206},
    {Species.Virizion, 207},
    {Species.Glastrier, 208},
    {Species.Spectrier, 209},
    {Species.Calyrex, (210, 0..2)},
  };

  public static Func<PKM, IComparable>[] GetGalarDexSortFunctions() {
    return GenerateSortingFunctions(GalarDex);
  }

  public static Func<PKM, IComparable>[] GetIoADexSortFunctions() {
    return GenerateSortingFunctions(IsleOfArmorDex);
  }

  public static Func<PKM, IComparable>[] GetCTDexSortFunction() {
    return GenerateSortingFunctions(CrownTundraDex);
  }

  public static Func<PKM, IComparable>[] GetFullGalarDexSortFunctions() {
    return GenerateSortingFunctions(GalarDex, IsleOfArmorDex, CrownTundraDex);
  }

}
