using PKHeX.Core;

namespace PluginPile.Sorting;
internal class Gen9Kalos : SortingBase {

  private static readonly Dictionary<Species, PositionForms> LumioseDex = new Dictionary<Species, PositionForms>(){
    {Species.Chikorita, 1},
    {Species.Bayleef, 2},
    {Species.Meganium, 3},
    {Species.Tepig, 4},
    {Species.Pignite, 5},
    {Species.Emboar, 6},
    {Species.Totodile, 7},
    {Species.Croconaw, 8},
    {Species.Feraligatr, 9},
    {Species.Fletchling, 10},
    {Species.Fletchinder, 11},
    {Species.Talonflame, 12},
    {Species.Bunnelby, 13},
    {Species.Diggersby, 14},
    {Species.Scatterbug, (15, 0..19)},
    {Species.Spewpa, (16, 0..19)},
    {Species.Vivillon, (017, 0..19)},
    {Species.Weedle, 18},
    {Species.Kakuna, 19},
    {Species.Beedrill, 20},
    {Species.Pidgey, 21},
    {Species.Pidgeotto, 22},
    {Species.Pidgeot, 23},
    {Species.Mareep, 24},
    {Species.Flaaffy, 25},
    {Species.Ampharos, 26},
    {Species.Patrat, 27},
    {Species.Watchog, 28},
    {Species.Budew, 29},
    {Species.Roselia, 30},
    {Species.Roserade, 31},
    {Species.Magikarp, 32},
    {Species.Gyarados, 33},
    {Species.Binacle, 34},
    {Species.Barbaracle, 35},
    {Species.Staryu, 36},
    {Species.Starmie, 37},
    {Species.Flabébé, (038, 0..4)},
    {Species.Floette, (039, 0..5)},
    {Species.Florges, (040, 0..4)},
    {Species.Skiddo, 41},
    {Species.Gogoat, 42},
    {Species.Espurr, 43},
    {Species.Meowstic, (44, 0..1)},
    {Species.Litleo, 45},
    {Species.Pyroar, 46},
    {Species.Pancham, 47},
    {Species.Pangoro, 48},
    {Species.Trubbish, 49},
    {Species.Garbodor, 50},
    {Species.Dedenne, 51},
    {Species.Pichu, 52},
    {Species.Pikachu, 53},
    {Species.Raichu, (054, 0..1)},
    {Species.Cleffa, 55},
    {Species.Clefairy, 56},
    {Species.Clefable, 57},
    {Species.Spinarak, 58},
    {Species.Ariados, 59},
    {Species.Ekans, 60},
    {Species.Arbok, 61},
    {Species.Abra, 62},
    {Species.Kadabra, 63},
    {Species.Alakazam, 64},
    {Species.Gastly, 65},
    {Species.Haunter, 66},
    {Species.Gengar, 67},
    {Species.Venipede, 68},
    {Species.Whirlipede, 69},
    {Species.Scolipede, 70},
    {Species.Honedge, 71},
    {Species.Doublade, 72},
    {Species.Aegislash, 73},
    {Species.Bellsprout, 74},
    {Species.Weepinbell, 75},
    {Species.Victreebel, 76},
    {Species.Pansage, 77},
    {Species.Simisage, 78},
    {Species.Pansear, 79},
    {Species.Simisear, 80},
    {Species.Panpour, 81},
    {Species.Simipour, 82},
    {Species.Meditite, 83},
    {Species.Medicham, 84},
    {Species.Electrike, 85},
    {Species.Manectric, 86},
    {Species.Ralts, 87},
    {Species.Kirlia, 88},
    {Species.Gardevoir, 89},
    {Species.Gallade, 90},
    {Species.Houndour, 91},
    {Species.Houndoom, 92},
    {Species.Swablu, 93},
    {Species.Altaria, 94},
    {Species.Audino, 95},
    {Species.Spritzee, 96},
    {Species.Aromatisse, 97},
    {Species.Swirlix, 98},
    {Species.Slurpuff, 99},
    {Species.Eevee, 100},
    {Species.Vaporeon, 101},
    {Species.Jolteon, 102},
    {Species.Flareon, 103},
    {Species.Espeon, 104},
    {Species.Umbreon, 105},
    {Species.Leafeon, 106},
    {Species.Glaceon, 107},
    {Species.Sylveon, 108},
    {Species.Buneary, 109},
    {Species.Lopunny, 110},
    {Species.Shuppet, 111},
    {Species.Banette, 112},
    {Species.Vanillite, 113},
    {Species.Vanillish, 114},
    {Species.Vanilluxe, 115},
    {Species.Numel, 116},
    {Species.Camerupt, 117},
    {Species.Hippopotas, 118},
    {Species.Hippowdon, 119},
    {Species.Drilbur, 120},
    {Species.Excadrill, 121},
    {Species.Sandile, 122},
    {Species.Krokorok, 123},
    {Species.Krookodile, 124},
    {Species.Machop, 125},
    {Species.Machoke, 126},
    {Species.Machamp, 127},
    {Species.Gible, 128},
    {Species.Gabite, 129},
    {Species.Garchomp, 130},
    {Species.Carbink, 131},
    {Species.Sableye, 132},
    {Species.Mawile, 133},
    {Species.Absol, 134},
    {Species.Riolu, 135},
    {Species.Lucario, 136},
    {Species.Slowpoke, (137, 0..1)},
    {Species.Slowbro, (138, new HashSet<int>() { 0, 2 })},
    {Species.Slowking, (139, 0..1)},
    {Species.Carvanha, 140},
    {Species.Sharpedo, 141},
    {Species.Tynamo, 142},
    {Species.Eelektrik, 143},
    {Species.Eelektross, 144},
    {Species.Dratini, 145},
    {Species.Dragonair, 146},
    {Species.Dragonite, 147},
    {Species.Bulbasaur, 148},
    {Species.Ivysaur, 149},
    {Species.Venusaur, 150},
    {Species.Charmander, 151},
    {Species.Charmeleon, 152},
    {Species.Charizard, 153},
    {Species.Squirtle, 154},
    {Species.Wartortle, 155},
    {Species.Blastoise, 156},
    {Species.Stunfisk, (157, 0..1)},
    {Species.Furfrou, (158, 0..9)},
    {Species.Inkay, 159},
    {Species.Malamar, 160},
    {Species.Skrelp, 161},
    {Species.Dragalge, 162},
    {Species.Clauncher, 163},
    {Species.Clawitzer, 164},
    {Species.Goomy, 165},
    {Species.Sliggoo, (166, 0..1)},
    {Species.Goodra, (167, 0..1)},
    {Species.Delibird, 168},
    {Species.Snorunt, 169},
    {Species.Glalie, 170},
    {Species.Froslass, 171},
    {Species.Snover, 172},
    {Species.Abomasnow, 173},
    {Species.Bergmite, 174},
    {Species.Avalugg, (175, 0..1)},
    {Species.Scyther, 176},
    {Species.Scizor, 177},
    {Species.Pinsir, 178},
    {Species.Heracross, 179},
    {Species.Emolga, 180},
    {Species.Hawlucha, 181},
    {Species.Phantump, 182},
    {Species.Trevenant, 183},
    {Species.Scraggy, 184},
    {Species.Scrafty, 185},
    {Species.Noibat, 186},
    {Species.Noivern, 187},
    {Species.Klefki, 188},
    {Species.Litwick, 189},
    {Species.Lampent, 190},
    {Species.Chandelure, 191},
    {Species.Aerodactyl, 192},
    {Species.Tyrunt, 193},
    {Species.Tyrantrum, 194},
    {Species.Amaura, 195},
    {Species.Aurorus, 196},
    {Species.Onix, 197},
    {Species.Steelix, 198},
    {Species.Aron, 199},
    {Species.Lairon, 200},
    {Species.Aggron, 201},
    {Species.Helioptile, 202},
    {Species.Heliolisk, 203},
    {Species.Pumpkaboo, (204, 0..3)},
    {Species.Gourgeist, (205, 0..3)},
    {Species.Larvitar, 206},
    {Species.Pupitar, 207},
    {Species.Tyranitar, 208},
    {Species.Froakie, 209},
    {Species.Frogadier, 210},
    {Species.Greninja, 211},
    {Species.Falinks, 212},
    {Species.Chespin, 213},
    {Species.Quilladin, 214},
    {Species.Chesnaught, 215},
    {Species.Skarmory, 216},
    {Species.Fennekin, 217},
    {Species.Braixen, 218},
    {Species.Delphox, 219},
    {Species.Bagon, 220},
    {Species.Shelgon, 221},
    {Species.Salamence, 222},
    {Species.Kangaskhan, 223},
    {Species.Drampa, 224},
    {Species.Beldum, 225},
    {Species.Metang, 226},
    {Species.Metagross, 227},
    {Species.Xerneas, 228},
    {Species.Yveltal, 229},
    {Species.Zygarde, (230, 0..3)},
    {Species.Diancie, 231},
    {Species.Mewtwo, 232}
  };

  private static readonly Dictionary<Species, PositionForms> HyperspaceDex = new Dictionary<Species, PositionForms>(){
    {Species.Mankey, 1},
    {Species.Primeape, 2},
    {Species.Annihilape, 3},
    {Species.Meowth, (4, 0..2)},
    {Species.Persian, (5, 0..1)},
    {Species.Perrserker, 6},
    {Species.Farfetchd, (7, 0..1)},
    {Species.Sirfetchd, 8},
    {Species.Cubone, 9},
    {Species.Marowak, (10, 0..1)},
    {Species.Porygon, 11},
    {Species.Porygon2, 12},
    {Species.PorygonZ, 13},
    {Species.Capsakid, 14},
    {Species.Scovillain, 15},
    {Species.Tinkatink, 16},
    {Species.Tinkatuff, 17},
    {Species.Tinkaton, 18},
    {Species.Cyclizar, 19},
    {Species.Glimmet, 20},
    {Species.Glimmora, 21},
    {Species.Rotom, (22, 0..5)},
    {Species.Greavard, 23},
    {Species.Houndstone, 24},
    {Species.Sandygast, 25},
    {Species.Palossand, 26},
    {Species.Kecleon, 27},
    {Species.Flamigo, 28},
    {Species.Cryogonal, 29},
    {Species.Dondozo, 30},
    {Species.Tatsugiri, (31, 0..2)},
    {Species.Frigibax, 32},
    {Species.Arctibax, 33},
    {Species.Baxcalibur, 34},
    {Species.Gimmighoul, (35, 0..1)},
    {Species.Gholdengo, 36},
    {Species.Qwilfish, (37, 0..1)},
    {Species.Overqwil, 38},
    {Species.Treecko, 39},
    {Species.Grovyle, 40},
    {Species.Sceptile, 41},
    {Species.Torchic, 42},
    {Species.Combusken, 43},
    {Species.Blaziken, 44},
    {Species.Mudkip, 45},
    {Species.Marshtomp, 46},
    {Species.Swampert, 47},
    {Species.Feebas, 48},
    {Species.Milotic, 49},
    {Species.Chingling, 50},
    {Species.Chimecho, 51},
    {Species.Indeedee, (52, 0..1)},
    {Species.Purrloin, 53},
    {Species.Liepard, 54},
    {Species.Munna, 55},
    {Species.Musharna, 56},
    {Species.Throh, 57},
    {Species.Sawk, 58},
    {Species.Yamask, (59, 0..1)},
    {Species.Cofagrigus, 60},
    {Species.Runerigus, 61},
    {Species.Wimpod, 62},
    {Species.Golisopod, 63},
    {Species.Nickit, 64},
    {Species.Thievul, 65},
    {Species.Clobbopus, 66},
    {Species.Grapploct, 67},
    {Species.Mimikyu, 68},
    {Species.Kleavor, 69},
    {Species.Morpeko, (70, 0..1)},
    {Species.Golett, 71},
    {Species.Golurk, 72},
    {Species.Rookidee, 73},
    {Species.Corvisquire, 74},
    {Species.Corviknight, 75},
    {Species.Igglybuff, 76},
    {Species.Jigglypuff, 77},
    {Species.Wigglytuff, 78},
    {Species.Fidough, 79},
    {Species.Dachsbun, 80},
    {Species.Starly, 81},
    {Species.Staravia, 82},
    {Species.Staraptor, 83},
    {Species.Spoink, 84},
    {Species.Grumpig, 85},
    {Species.Squawkabilly, (86, 0..3)},
    {Species.Crabrawler, 87},
    {Species.Crabominable, 88},
    {Species.Nacli, 89},
    {Species.Naclstack, 90},
    {Species.Garganacl, 91},
    {Species.Gulpin, 92},
    {Species.Swalot, 93},
    {Species.Zubat, 94},
    {Species.Golbat, 95},
    {Species.Crobat, 96},
    {Species.Charcadet, 97},
    {Species.Armarouge, 98},
    {Species.Ceruledge, 99},
    {Species.Maschiff, 100},
    {Species.Mabosstiff, 101},
    {Species.Toxel, 102},
    {Species.Toxtricity, (103, 0..1)},
    {Species.Shroodle, 104},
    {Species.Grafaiai, 105},
    {Species.Zangoose, 106},
    {Species.Seviper, 107},
    {Species.MimeJr, 108},
    {Species.MrMime, (109, 0..1)},
    {Species.MrRime, 110},
    {Species.Foongus, 111},
    {Species.Amoonguss, 112},
    {Species.Heatran, 113},
    {Species.Volcanion, 114},
    {Species.Cobalion, 115},
    {Species.Terrakion, 116},
    {Species.Virizion, 117},
    {Species.Keldeo, (118, 0..1)},
    {Species.Meloetta, (119, 0..1)},
    {Species.Genesect, (120, 0..4)},
    {Species.Hoopa, (121, 0..1)},
    {Species.Marshadow, 122},
    {Species.Meltan, 123},
    {Species.Melmetal, 124},
    {Species.Darkrai, 125},
    {Species.Latias, 126},
    {Species.Latios, 127},
    {Species.Kyogre, 128},
    {Species.Groudon, 129},
    {Species.Rayquaza, 130},
    {Species.Magearna, (131, 0..1)},
    {Species.Zeraora, 132}
  };

  public static Func<PKM, IComparable>[] GetLumioseDexSortFunctions() {
    return GenerateSortingFunctions(LumioseDex);
  }

  public static Func<PKM, IComparable>[] GetHyperspaceDexSortFunctions() {
    return GenerateSortingFunctions(HyperspaceDex);
  }

  public static Func<PKM, IComparable>[] GetSortFunctions() {
    return GenerateSortingFunctions(LumioseDex, HyperspaceDex);
  }
}
