using PKHeX.Core;

namespace PluginPile.Sorting;
internal class Gen9Paldea : SortingBase {

  private static readonly Dictionary<Species, PositionForms> PaldeaDex = new Dictionary<Species, PositionForms>() {
    {Species.Sprigatito, 1},
    {Species.Floragato, 2},
    {Species.Meowscarada, 3},
    {Species.Fuecoco, 4},
    {Species.Crocalor, 5},
    {Species.Skeledirge, 6},
    {Species.Quaxly, 7},
    {Species.Quaxwell, 8},
    {Species.Quaquaval, 9},
    {Species.Lechonk, 10},
    {Species.Oinkologne, (11, 0..1)},
    {Species.Tarountula, 12},
    {Species.Spidops, 13},
    {Species.Nymble, 14},
    {Species.Lokix, 15},
    {Species.Hoppip, 16},
    {Species.Skiploom, 17},
    {Species.Jumpluff, 18},
    {Species.Fletchling, 19},
    {Species.Fletchinder, 20},
    {Species.Talonflame, 21},
    {Species.Pawmi, 22},
    {Species.Pawmo, 23},
    {Species.Pawmot, 24},
    {Species.Houndour, 25},
    {Species.Houndoom, 26},
    {Species.Yungoos, 27},
    {Species.Gumshoos, 28},
    {Species.Skwovet, 29},
    {Species.Greedent, 30},
    {Species.Sunkern, 31},
    {Species.Sunflora, 32},
    {Species.Kricketot, 33},
    {Species.Kricketune, 34},
    {Species.Scatterbug, (35, 0..19)},
    {Species.Spewpa, (36, 0..19)},
    {Species.Vivillon, (37, 0..19)},
    {Species.Combee, 38},
    {Species.Vespiquen, 39},
    {Species.Rookidee, 40},
    {Species.Corvisquire, 41},
    {Species.Corviknight, 42},
    {Species.Happiny, 43},
    {Species.Chansey, 44},
    {Species.Blissey, 45},
    {Species.Azurill, 46},
    {Species.Marill, 47},
    {Species.Azumarill, 48},
    {Species.Surskit, 49},
    {Species.Masquerain, 50},
    {Species.Buizel, 51},
    {Species.Floatzel, 52},
    {Species.Wooper, (53, 1)},
    {Species.Clodsire, 54},
    {Species.Psyduck, 55},
    {Species.Golduck, 56},
    {Species.Chewtle, 57},
    {Species.Drednaw, 58},
    {Species.Igglybuff, 59},
    {Species.Jigglypuff, 60},
    {Species.Wigglytuff, 61},
    {Species.Ralts, 62},
    {Species.Kirlia, 63},
    {Species.Gardevoir, 64},
    {Species.Gallade, 65},
    {Species.Drowzee, 66},
    {Species.Hypno, 67},
    {Species.Gastly, 68},
    {Species.Haunter, 69},
    {Species.Gengar, 70},
    {Species.Tandemaus, 71},
    {Species.Maushold, (72, 0..1)},
    {Species.Pichu, 73},
    {Species.Pikachu, 74},
    {Species.Raichu, 75},
    {Species.Fidough, 76},
    {Species.Dachsbun, 77},
    {Species.Slakoth, 78},
    {Species.Vigoroth, 79},
    {Species.Slaking, 80},
    {Species.Bounsweet, 81},
    {Species.Steenee, 82},
    {Species.Tsareena, 83},
    {Species.Smoliv, 84},
    {Species.Dolliv, 85},
    {Species.Arboliva, 86},
    {Species.Bonsly, 87},
    {Species.Sudowoodo, 88},
    {Species.Rockruff, (89, 0..1)},
    {Species.Lycanroc, (90, 0..2)},
    {Species.Rolycoly, 91},
    {Species.Carkol, 92},
    {Species.Coalossal, 93},
    {Species.Shinx, 94},
    {Species.Luxio, 95},
    {Species.Luxray, 96},
    {Species.Starly, 97},
    {Species.Staravia, 98},
    {Species.Staraptor, 99},
    {Species.Oricorio, (100, 0..3)},
    {Species.Mareep, 101},
    {Species.Flaaffy, 102},
    {Species.Ampharos, 103},
    {Species.Petilil, 104},
    {Species.Lilligant, 105},
    {Species.Shroomish, 106},
    {Species.Breloom, 107},
    {Species.Applin, 108},
    {Species.Flapple, 109},
    {Species.Appletun, 110},
    {Species.Spoink, 111},
    {Species.Grumpig, 112},
    {Species.Squawkabilly, (113, 0..3)},
    {Species.Misdreavus, 114},
    {Species.Mismagius, 115},
    {Species.Makuhita, 116},
    {Species.Hariyama, 117},
    {Species.Crabrawler, 118},
    {Species.Crabominable, 119},
    {Species.Salandit, 120},
    {Species.Salazzle, 121},
    {Species.Phanpy, 122},
    {Species.Donphan, 123},
    {Species.Cufant, 124},
    {Species.Copperajah, 125},
    {Species.Gible, 126},
    {Species.Gabite, 127},
    {Species.Garchomp, 128},
    {Species.Nacli, 129},
    {Species.Naclstack, 130},
    {Species.Garganacl, 131},
    {Species.Wingull, 132},
    {Species.Pelipper, 133},
    {Species.Magikarp, 134},
    {Species.Gyarados, 135},
    {Species.Arrokuda, 136},
    {Species.Barraskewda, 137},
    {Species.Basculin, (138, 0..1)},
    {Species.Gulpin, 139},
    {Species.Swalot, 140},
    {Species.Meowth, 141},
    {Species.Persian, 142},
    {Species.Drifloon, 143},
    {Species.Drifblim, 144},
    {Species.Flabébé, (145, 0..4)},
    {Species.Floette, (146, 0..4)},
    {Species.Florges, (147, 0..4)},
    {Species.Diglett, 148},
    {Species.Dugtrio, 149},
    {Species.Torkoal, 150},
    {Species.Numel, 151},
    {Species.Camerupt, 152},
    {Species.Bronzor, 153},
    {Species.Bronzong, 154},
    {Species.Axew, 155},
    {Species.Fraxure, 156},
    {Species.Haxorus, 157},
    {Species.Mankey, 158},
    {Species.Primeape, 159},
    {Species.Annihilape, 160},
    {Species.Meditite, 161},
    {Species.Medicham, 162},
    {Species.Riolu, 163},
    {Species.Lucario, 164},
    {Species.Charcadet, 165},
    {Species.Armarouge, 166},
    {Species.Ceruledge, 167},
    {Species.Barboach, 168},
    {Species.Whiscash, 169},
    {Species.Tadbulb, 170},
    {Species.Bellibolt, 171},
    {Species.Goomy, 172},
    {Species.Sliggoo, 173},
    {Species.Goodra, 174},
    {Species.Croagunk, 175},
    {Species.Toxicroak, 176},
    {Species.Wattrel, 177},
    {Species.Kilowattrel, 178},
    {Species.Eevee, 179},
    {Species.Vaporeon, 180},
    {Species.Jolteon, 181},
    {Species.Flareon, 182},
    {Species.Espeon, 183},
    {Species.Umbreon, 184},
    {Species.Leafeon, 185},
    {Species.Glaceon, 186},
    {Species.Sylveon, 187},
    {Species.Dunsparce, 188},
    {Species.Dudunsparce, (189, 0..1)},
    {Species.Deerling, (190, 0..3)},
    {Species.Sawsbuck, (191, 0..3)},
    {Species.Girafarig, 192},
    {Species.Farigiraf, 193},
    {Species.Grimer, 194},
    {Species.Muk, 195},
    {Species.Maschiff, 196},
    {Species.Mabosstiff, 197},
    {Species.Toxel, 198},
    {Species.Toxtricity, (199, 0..1)},
    {Species.Dedenne, 200},
    {Species.Pachirisu, 201},
    {Species.Shroodle, 202},
    {Species.Grafaiai, 203},
    {Species.Stantler, 204},
    {Species.Foongus, 205},
    {Species.Amoonguss, 206},
    {Species.Voltorb, 207},
    {Species.Electrode, 208},
    {Species.Magnemite, 209},
    {Species.Magneton, 210},
    {Species.Magnezone, 211},
    {Species.Ditto, 212},
    {Species.Growlithe, 213},
    {Species.Arcanine, 214},
    {Species.Teddiursa, 215},
    {Species.Ursaring, 216},
    {Species.Zangoose, 217},
    {Species.Seviper, 218},
    {Species.Swablu, 219},
    {Species.Altaria, 220},
    {Species.Skiddo, 221},
    {Species.Gogoat, 222},
    {Species.Tauros, (223, 1..3)},
    {Species.Litleo, 224},
    {Species.Pyroar, 225},
    {Species.Stunky, 226},
    {Species.Skuntank, 227},
    {Species.Zorua, 228},
    {Species.Zoroark, 229},
    {Species.Sneasel, 230},
    {Species.Weavile, 231},
    {Species.Murkrow, 232},
    {Species.Honchkrow, 233},
    {Species.Gothita, 234},
    {Species.Gothorita, 235},
    {Species.Gothitelle, 236},
    {Species.Sinistea, (237, 0..1)},
    {Species.Polteageist, (238, 0..1)},
    {Species.Mimikyu, (239, 0..1)},
    {Species.Klefki, 240},
    {Species.Indeedee, (241, 0..1)},
    {Species.Bramblin, 242},
    {Species.Brambleghast, 243},
    {Species.Toedscool, 244},
    {Species.Toedscruel, 245},
    {Species.Tropius, 246},
    {Species.Fomantis, 247},
    {Species.Lurantis, 248},
    {Species.Klawf, 249},
    {Species.Capsakid, 250},
    {Species.Scovillain, 251},
    {Species.Cacnea, 252},
    {Species.Cacturne, 253},
    {Species.Rellor, 254},
    {Species.Rabsca, 255},
    {Species.Venonat, 256},
    {Species.Venomoth, 257},
    {Species.Pineco, 258},
    {Species.Forretress, 259},
    {Species.Scyther, 260},
    {Species.Scizor, 261},
    {Species.Heracross, 262},
    {Species.Flittle, 263},
    {Species.Espathra, 264},
    {Species.Hippopotas, 265},
    {Species.Hippowdon, 266},
    {Species.Sandile, 267},
    {Species.Krokorok, 268},
    {Species.Krookodile, 269},
    {Species.Silicobra, 270},
    {Species.Sandaconda, 271},
    {Species.Mudbray, 272},
    {Species.Mudsdale, 273},
    {Species.Larvesta, 274},
    {Species.Volcarona, 275},
    {Species.Bagon, 276},
    {Species.Shelgon, 277},
    {Species.Salamence, 278},
    {Species.Tinkatink, 279},
    {Species.Tinkatuff, 280},
    {Species.Tinkaton, 281},
    {Species.Hatenna, 282},
    {Species.Hattrem, 283},
    {Species.Hatterene, 284},
    {Species.Impidimp, 285},
    {Species.Morgrem, 286},
    {Species.Grimmsnarl, 287},
    {Species.Wiglett, 288},
    {Species.Wugtrio, 289},
    {Species.Bombirdier, 290},
    {Species.Finizen, 291},
    {Species.Palafin, (292, 0..1)},
    {Species.Varoom, 293},
    {Species.Revavroom, 294},
    {Species.Cyclizar, 295},
    {Species.Orthworm, 296},
    {Species.Sableye, 297},
    {Species.Shuppet, 298},
    {Species.Banette, 299},
    {Species.Falinks, 300},
    {Species.Hawlucha, 301},
    {Species.Spiritomb, 302},
    {Species.Noibat, 303},
    {Species.Noivern, 304},
    {Species.Dreepy, 305},
    {Species.Drakloak, 306},
    {Species.Dragapult, 307},
    {Species.Glimmet, 308},
    {Species.Glimmora, 309},
    {Species.Rotom, (310, 0..5)},
    {Species.Greavard, 311},
    {Species.Houndstone, 312},
    {Species.Oranguru, 313},
    {Species.Passimian, 314},
    {Species.Komala, 315},
    {Species.Larvitar, 316},
    {Species.Pupitar, 317},
    {Species.Tyranitar, 318},
    {Species.Stonjourner, 319},
    {Species.Eiscue, (320, 0..1)},
    {Species.Pincurchin, 321},
    {Species.Sandygast, 322},
    {Species.Palossand, 323},
    {Species.Slowpoke, 324},
    {Species.Slowbro, 325},
    {Species.Slowking, 326},
    {Species.Shellos, (327, 0..1)},
    {Species.Gastrodon, (328, 0..1)},
    {Species.Shellder, 329},
    {Species.Cloyster, 330},
    {Species.Qwilfish, 331},
    {Species.Luvdisc, 332},
    {Species.Finneon, 333},
    {Species.Lumineon, 334},
    {Species.Bruxish, 335},
    {Species.Alomomola, 336},
    {Species.Skrelp, 337},
    {Species.Dragalge, 338},
    {Species.Clauncher, 339},
    {Species.Clawitzer, 340},
    {Species.Tynamo, 341},
    {Species.Eelektrik, 342},
    {Species.Eelektross, 343},
    {Species.Mareanie, 344},
    {Species.Toxapex, 345},
    {Species.Flamigo, 346},
    {Species.Dratini, 347},
    {Species.Dragonair, 348},
    {Species.Dragonite, 349},
    {Species.Snom, 350},
    {Species.Frosmoth, 351},
    {Species.Snover, 352},
    {Species.Abomasnow, 353},
    {Species.Delibird, 354},
    {Species.Cubchoo, 355},
    {Species.Beartic, 356},
    {Species.Snorunt, 357},
    {Species.Glalie, 358},
    {Species.Froslass, 359},
    {Species.Cryogonal, 360},
    {Species.Cetoddle, 361},
    {Species.Cetitan, 362},
    {Species.Bergmite, 363},
    {Species.Avalugg, 364},
    {Species.Rufflet, 365},
    {Species.Braviary, 366},
    {Species.Pawniard, 367},
    {Species.Bisharp, 368},
    {Species.Kingambit, 369},
    {Species.Deino, 370},
    {Species.Zweilous, 371},
    {Species.Hydreigon, 372},
    {Species.Veluza, 373},
    {Species.Dondozo, 374},
    {Species.Tatsugiri, (375, 0..2)},
    {Species.GreatTusk, 376},
    {Species.ScreamTail, 377},
    {Species.BruteBonnet, 378},
    {Species.FlutterMane, 379},
    {Species.SlitherWing, 380},
    {Species.SandyShocks, 381},
    {Species.IronTreads, 382},
    {Species.IronBundle, 383},
    {Species.IronHands, 384},
    {Species.IronJugulis, 385},
    {Species.IronMoth, 386},
    {Species.IronThorns, 387},
    {Species.Frigibax, 388},
    {Species.Arctibax, 389},
    {Species.Baxcalibur, 390},
    {Species.Gimmighoul, 391},
    {Species.Gholdengo, 392},
    {Species.WoChien, 393},
    {Species.ChienPao, 394},
    {Species.TingLu, 395},
    {Species.ChiYu, 396},
    {Species.RoaringMoon, 397},
    {Species.IronValiant, 398},
    {Species.Koraidon, 399},
    {Species.Miraidon, 400}
  };

  private static readonly Dictionary<Species, PositionForms> KitakamiDex = new Dictionary<Species, PositionForms>() {
    {Species.Spinarak, 1},
    {Species.Ariados, 2},
    {Species.Yanma, 3},
    {Species.Yanmega, 4},
    {Species.Wooper , (5, 0)},
    {Species.Quagsire, 6},
    {Species.Poochyena, 7},
    {Species.Mightyena, 8},
    {Species.Volbeat, 9},
    {Species.Illumise, 10},
    {Species.Corphish, 11},
    {Species.Crawdaunt, 12},
    {Species.Sewaddle, 13},
    {Species.Swadloon, 14},
    {Species.Leavanny, 15},
    {Species.Cutiefly, 16},
    {Species.Ribombee, 17},
    {Species.Ekans, 18},
    {Species.Arbok, 19},
    {Species.Pichu, 20},
    {Species.Pikachu, 21},
    {Species.Raichu, 22},
    {Species.Bellsprout, 23},
    {Species.Weepinbell, 24},
    {Species.Victreebel, 25},
    {Species.Sentret, 26},
    {Species.Furret, 27},
    {Species.Starly, 28},
    {Species.Staravia, 29},
    {Species.Staraptor, 30},
    {Species.Fomantis, 31},
    {Species.Lurantis, 32},
    {Species.Applin, 33},
    {Species.Flapple, 34},
    {Species.Appletun, 35},
    {Species.Dipplin, 36},
    {Species.Vulpix, 37},
    {Species.Ninetales, 38},
    {Species.Poliwag, 39},
    {Species.Poliwhirl, 40},
    {Species.Poliwrath, 41},
    {Species.Politoed, 42},
    {Species.Magikarp, 43},
    {Species.Gyarados, 44},
    {Species.Hoothoot, 45},
    {Species.Noctowl, 46},
    {Species.Aipom, 47},
    {Species.Ambipom, 48},
    {Species.Heracross, 49},
    {Species.Swinub, 50},
    {Species.Piloswine, 51},
    {Species.Mamoswine, 52},
    {Species.Stantler, 53},
    {Species.Seedot, 54},
    {Species.Nuzleaf, 55},
    {Species.Shiftry, 56},
    {Species.Ralts, 57},
    {Species.Kirlia, 58},
    {Species.Gardevoir, 59},
    {Species.Gallade, 60},
    {Species.Kricketot, 61},
    {Species.Kricketune, 62},
    {Species.Pachirisu, 63},
    {Species.Riolu, 64},
    {Species.Lucario, 65},
    {Species.Petilil, 66},
    {Species.Lilligant, 67},
    {Species.Phantump, 68},
    {Species.Trevenant, 69},
    {Species.Rockruff, (70, 0..1)},
    {Species.Lycanroc, (71, 0..2)},
    {Species.Skwovet, 72},
    {Species.Greedent, 73},
    {Species.Toedscool, 74},
    {Species.Toedscruel, 75},
    {Species.Poltchageist, (76, 0..1)},
    {Species.Sinistcha, (77, 0..1)},
    {Species.Growlithe, 78},
    {Species.Arcanine, 79},
    {Species.Geodude, 80},
    {Species.Graveler, 81},
    {Species.Golem, 82},
    {Species.Bonsly, 83},
    {Species.Sudowoodo, 84},
    {Species.Timburr, 85},
    {Species.Gurdurr, 86},
    {Species.Conkeldurr, 87},
    {Species.Noibat, 88},
    {Species.Noivern, 89},
    {Species.Arrokuda, 90},
    {Species.Barraskewda, 91},
    {Species.Hatenna, 92},
    {Species.Hattrem, 93},
    {Species.Hatterene, 94},
    {Species.Morpeko, 95},
    {Species.Orthworm, 96},
    {Species.Tandemaus, 97},
    {Species.Maushold, (98, 0..1)},
    {Species.Mankey, 99},
    {Species.Primeape, 100},
    {Species.Annihilape, 101},
    {Species.Munchlax, 102},
    {Species.Snorlax, 103},
    {Species.Lotad, 104},
    {Species.Lombre, 105},
    {Species.Ludicolo, 106},
    {Species.Nosepass, 107},
    {Species.Probopass, 108},
    {Species.Shinx, 109},
    {Species.Luxio, 110},
    {Species.Luxray, 111},
    {Species.Grubbin, 112},
    {Species.Charjabug, 113},
    {Species.Vikavolt, 114},
    {Species.Oricorio, (115, 0..3)},
    {Species.Sandshrew, 116},
    {Species.Sandslash, 117},
    {Species.Gastly, 118},
    {Species.Haunter, 119},
    {Species.Gengar, 120},
    {Species.Gligar, 121},
    {Species.Gliscor, 122},
    {Species.Houndour, 123},
    {Species.Houndoom, 124},
    {Species.Spoink, 125},
    {Species.Grumpig, 126},
    {Species.Vullaby, 127},
    {Species.Mandibuzz, 128},
    {Species.Mudbray, 129},
    {Species.Mudsdale, 130},
    {Species.Jangmoo, 131},
    {Species.Hakamoo, 132},
    {Species.Kommoo, 133},
    {Species.Bombirdier, 134},
    {Species.Koffing, 135},
    {Species.Weezing, 136},
    {Species.Mienfoo, 137},
    {Species.Mienshao, 138},
    {Species.Duskull, 139},
    {Species.Dusclops, 140},
    {Species.Dusknoir, 141},
    {Species.Chingling, 142},
    {Species.Chimecho, 143},
    {Species.Slugma, 144},
    {Species.Magcargo, 145},
    {Species.Litwick, 146},
    {Species.Lampent, 147},
    {Species.Chandelure, 148},
    {Species.Surskit, 149},
    {Species.Masquerain, 150},
    {Species.Cleffa, 151},
    {Species.Clefairy, 152},
    {Species.Clefable, 153},
    {Species.Bronzor, 154},
    {Species.Bronzong, 155},
    {Species.Glimmet, 156},
    {Species.Glimmora, 157},
    {Species.Feebas, 158},
    {Species.Milotic, 159},
    {Species.Dunsparce, 160},
    {Species.Dudunsparce, (161, 0..1)},
    {Species.Barboach, 162},
    {Species.Whiscash, 163},
    {Species.Gible, 164},
    {Species.Gabite, 165},
    {Species.Garchomp, 166},
    {Species.Carbink, 167},
    {Species.Salandit, 168},
    {Species.Salazzle, 169},
    {Species.Sneasel, 170},
    {Species.Weavile, 171},
    {Species.Snorunt, 172},
    {Species.Glalie, 173},
    {Species.Froslass, 174},
    {Species.Tynamo, 175},
    {Species.Eelektrik, 176},
    {Species.Eelektross, 177},
    {Species.Goomy, 178},
    {Species.Sliggoo, 179},
    {Species.Goodra, 180},
    {Species.Ducklett, 181},
    {Species.Swanna, 182},
    {Species.Chewtle, 183},
    {Species.Drednaw, 184},
    {Species.Cramorant, (185, 0..2)},
    {Species.Pawniard, 186},
    {Species.Bisharp, 187},
    {Species.Kingambit, 188},
    {Species.Mimikyu, (189, 0..1)},
    {Species.Impidimp, 190},
    {Species.Morgrem, 191},
    {Species.Grimmsnarl, 192},
    {Species.Indeedee, (193, 0..1)},
    {Species.Basculin, (194, 2)},
    {Species.Basculegion, (195, 0..1)},
    {Species.Ursaluna, (196, 1)},
    {Species.Okidogi, 197},
    {Species.Munkidori, 198},
    {Species.Fezandipiti, 199},
    {Species.Ogerpon, (200, 0..7)},
  };

  private static readonly Dictionary<Species, PositionForms> BlueberryAcademyDex = new Dictionary<Species, PositionForms>() {
    {Species.Doduo, 1},
    {Species.Dodrio, 2},
    {Species.Exeggcute, 3},
    {Species.Exeggutor, (4, 0..1)},
    {Species.Rhyhorn, 5},
    {Species.Rhydon, 6},
    {Species.Rhyperior, 7},
    {Species.Venonat, 8},
    {Species.Venomoth, 9},
    {Species.Elekid, 10},
    {Species.Electabuzz, 11},
    {Species.Electivire, 12},
    {Species.Magby, 13},
    {Species.Magmar, 14},
    {Species.Magmortar, 15},
    {Species.Happiny, 16},
    {Species.Chansey, 17},
    {Species.Blissey, 18},
    {Species.Scyther, 19},
    {Species.Scizor, 20},
    {Species.Kleavor, 21},
    {Species.Tauros, 22},
    {Species.Blitzle, 23},
    {Species.Zebstrika, 24},
    {Species.Girafarig, 25},
    {Species.Farigiraf, 26},
    {Species.Sandile, 27},
    {Species.Krokorok, 28},
    {Species.Krookodile, 29},
    {Species.Rellor, 30},
    {Species.Rabsca, 31},
    {Species.Rufflet, 32},
    {Species.Braviary, 33},
    {Species.Vullaby, 34},
    {Species.Mandibuzz, 35},
    {Species.Litleo, 36},
    {Species.Pyroar, 37},
    {Species.Deerling, (38, 0..3)},
    {Species.Sawsbuck, (39, 0..3)},
    {Species.Smeargle, 40},
    {Species.Rotom, (41, 0..5)},
    {Species.Milcery, 42},
    {Species.Alcremie, (43, 0..8)},
    {Species.Trapinch, 44},
    {Species.Vibrava, 45},
    {Species.Flygon, 46},
    {Species.Pikipek, 47},
    {Species.Trumbeak, 48},
    {Species.Toucannon, 49},
    {Species.Tentacool, 50},
    {Species.Tentacruel, 51},
    {Species.Horsea, 52},
    {Species.Seadra, 53},
    {Species.Kingdra, 54},
    {Species.Bruxish, 55},
    {Species.Cottonee, 56},
    {Species.Whimsicott, 57},
    {Species.Comfey, 58},
    {Species.Slakoth, 59},
    {Species.Vigoroth, 60},
    {Species.Slaking, 61},
    {Species.Oddish, 62},
    {Species.Gloom, 63},
    {Species.Vileplume, 64},
    {Species.Bellossom, 65},
    {Species.Diglett, (66, 1)},
    {Species.Dugtrio, (67, 1)},
    {Species.Grimer, (68, 1)},
    {Species.Muk, (69, 1)},
    {Species.Zangoose, 70},
    {Species.Seviper, 71},
    {Species.Crabrawler, 72},
    {Species.Crabominable, 73},
    {Species.Oricorio, (115, 0..3)},
    {Species.Slowpoke, (75, 1)},
    {Species.Slowbro, (76, 2)},
    {Species.Slowking, (77, 1)},
    {Species.Chinchou, 78},
    {Species.Lanturn, 79},
    {Species.Inkay, 80},
    {Species.Malamar, 81},
    {Species.Luvdisc, 82},
    {Species.Finneon, 83},
    {Species.Lumineon, 84},
    {Species.Alomomola, 85},
    {Species.Torkoal, 86},
    {Species.Fletchling, 87},
    {Species.Fletchinder, 88},
    {Species.Talonflame, 89},
    {Species.Dewpider, 90},
    {Species.Araquanid, 91},
    {Species.Tyrogue, 92},
    {Species.Hitmonlee, 93},
    {Species.Hitmonchan, 94},
    {Species.Hitmontop, 95},
    {Species.Geodude, (96, 1)},
    {Species.Graveler, (97, 1)},
    {Species.Golem, (98, 1)},
    {Species.Drilbur, 99},
    {Species.Excadrill, 100},
    {Species.Gothita, 101},
    {Species.Gothorita, 102},
    {Species.Gothitelle, 103},
    {Species.Espurr, 104},
    {Species.Meowstic, (105, 0..1)},
    {Species.Minior, (106, 0..13)},
    {Species.Cranidos, 107},
    {Species.Rampardos, 108},
    {Species.Shieldon, 109},
    {Species.Bastiodon, 110},
    {Species.Minccino, 111},
    {Species.Cinccino, 112},
    {Species.Skarmory, 113},
    {Species.Swablu, 114},
    {Species.Altaria, 115},
    {Species.Magnemite, 116},
    {Species.Magneton, 117},
    {Species.Magnezone, 118},
    {Species.Plusle, 119},
    {Species.Minun, 120},
    {Species.Scraggy, 121},
    {Species.Scrafty, 122},
    {Species.Golett, 123},
    {Species.Golurk, 124},
    {Species.Numel, 125},
    {Species.Camerupt, 126},
    {Species.Sinistea, (127, 0..1)},
    {Species.Polteageist, (128, 0..1)},
    {Species.Porygon, 129},
    {Species.Porygon2, 130},
    {Species.PorygonZ, 131},
    {Species.Joltik, 132},
    {Species.Galvantula, 133},
    {Species.Tynamo, 134},
    {Species.Eelektrik, 135},
    {Species.Eelektross, 136},
    {Species.Beldum, 137},
    {Species.Metang, 138},
    {Species.Metagross, 139},
    {Species.Axew, 140},
    {Species.Fraxure, 141},
    {Species.Haxorus, 142},
    {Species.Seel, 143},
    {Species.Dewgong, 144},
    {Species.Lapras, 145},
    {Species.Qwilfish, (146, 1)},
    {Species.Overqwil, 147},
    {Species.Solosis, 148},
    {Species.Duosion, 149},
    {Species.Reuniclus, 150},
    {Species.Snubbull, 151},
    {Species.Granbull, 152},
    {Species.Cubchoo, 153},
    {Species.Beartic, 154},
    {Species.Sandshrew, (155, 1)},
    {Species.Sandslash, (156, 1)},
    {Species.Vulpix, (157, 1)},
    {Species.Ninetales, (158, 1)},
    {Species.Snover, 159},
    {Species.Abomasnow, 160},
    {Species.Duraludon, 161},
    {Species.Archaludon, 162},
    {Species.Hydrapple, 163},
    {Species.Bulbasaur, 164},
    {Species.Ivysaur, 165},
    {Species.Venusaur, 166},
    {Species.Charmander, 167},
    {Species.Charmeleon, 168},
    {Species.Charizard, 169},
    {Species.Squirtle, 170},
    {Species.Wartortle, 171},
    {Species.Blastoise, 172},
    {Species.Chikorita, 173},
    {Species.Bayleef, 174},
    {Species.Meganium, 175},
    {Species.Cyndaquil, 176},
    {Species.Quilava, 177},
    {Species.Typhlosion, 178},
    {Species.Totodile, 179},
    {Species.Croconaw, 180},
    {Species.Feraligatr, 181},
    {Species.Treecko, 182},
    {Species.Grovyle, 183},
    {Species.Sceptile, 184},
    {Species.Torchic, 185},
    {Species.Combusken, 186},
    {Species.Blaziken, 187},
    {Species.Mudkip, 188},
    {Species.Marshtomp, 189},
    {Species.Swampert, 190},
    {Species.Turtwig, 191},
    {Species.Grotle, 192},
    {Species.Torterra, 193},
    {Species.Chimchar, 194},
    {Species.Monferno, 195},
    {Species.Infernape, 196},
    {Species.Piplup, 197},
    {Species.Prinplup, 198},
    {Species.Empoleon, 199},
    {Species.Snivy, 200},
    {Species.Servine, 201},
    {Species.Serperior, 202},
    {Species.Tepig, 203},
    {Species.Pignite, 204},
    {Species.Emboar, 205},
    {Species.Oshawott, 206},
    {Species.Dewott, 207},
    {Species.Samurott, 208},
    {Species.Chespin, 209},
    {Species.Quilladin, 210},
    {Species.Chesnaught, 211},
    {Species.Fennekin, 212},
    {Species.Braixen, 213},
    {Species.Delphox, 214},
    {Species.Froakie, 215},
    {Species.Frogadier, 216},
    {Species.Greninja, 217},
    {Species.Rowlet, 218},
    {Species.Dartrix, 219},
    {Species.Decidueye, 220},
    {Species.Litten, 221},
    {Species.Torracat, 222},
    {Species.Incineroar, 223},
    {Species.Popplio, 224},
    {Species.Brionne, 225},
    {Species.Primarina, 226},
    {Species.Grookey, 227},
    {Species.Thwackey, 228},
    {Species.Rillaboom, 229},
    {Species.Scorbunny, 230},
    {Species.Raboot, 231},
    {Species.Cinderace, 232},
    {Species.Sobble, 233},
    {Species.Drizzile, 234},
    {Species.Inteleon, 235},
    {Species.GougingFire, 236},
    {Species.RagingBolt, 237},
    {Species.IronCrown, 238},
    {Species.IronBoulder, 239},
    {Species.Terapagos, 240},
    {Species.WalkingWake, 241},
    {Species.IronLeaves, 242},
    {Species.Pecharunt, 243},
  };

  public static Func<PKM, IComparable>[] GetPaldeaSortFunctions() {
    return GenerateSortingFunctions(PaldeaDex);
  }

  public static Func<PKM, IComparable>[] GetKitakamiSortFunctions() {
    return GenerateSortingFunctions(KitakamiDex);
  }

  public static Func<PKM, IComparable>[] GetBlueberryAcademySortFunctions() {
    return GenerateSortingFunctions(BlueberryAcademyDex);
  }

  public static Func<PKM, IComparable>[] GetSortFunctions() {
    return GenerateSortingFunctions(PaldeaDex, KitakamiDex, BlueberryAcademyDex);
  }

}
