using PKHeX.Core;

namespace PluginPile.Sorting;
internal class Gen9Kalos : SortingBase {

  private static readonly Dictionary<Species, PositionForms> LumioseDex = new Dictionary<Species, PositionForms>(){
    {Species.Chikorita, 1},
    {Species.Bayleef, 2},
    {Species.Meganium, 3},
    {Species.Tepig, 4},
    {Species.Pignite, 5},
    {Species.Emboar, 6},
    {Species.Totodile, 7},
    {Species.Croconaw, 8},
    {Species.Feraligatr, 9},
    {Species.Fletchling, 10},
    {Species.Fletchinder, 11},
    {Species.Talonflame, 12},
    {Species.Bunnelby, 13},
    {Species.Diggersby, 14},
    {Species.Scatterbug, (15, 0..19)},
    {Species.Spewpa, (16, 0..19)},
    {Species.Vivillon, (017, 0..19)},
    {Species.Weedle, 18},
    {Species.Kakuna, 19},
    {Species.Beedrill, 20},
    {Species.Pidgey, 21},
    {Species.Pidgeotto, 22},
    {Species.Pidgeot, 23},
    {Species.Mareep, 24},
    {Species.Flaaffy, 25},
    {Species.Ampharos, 26},
    {Species.Patrat, 27},
    {Species.Watchog, 28},
    {Species.Budew, 29},
    {Species.Roselia, 30},
    {Species.Roserade, 31},
    {Species.Magikarp, 32},
    {Species.Gyarados, 33},
    {Species.Binacle, 34},
    {Species.Barbaracle, 35},
    {Species.Staryu, 36},
    {Species.Starmie, 37},
    {Species.Flabébé, (038, 0..4)},
    {Species.Floette, (039, 0..5)},
    {Species.Florges, (040, 0..4)},
    {Species.Skiddo, 41},
    {Species.Gogoat, 42},
    {Species.Espurr, 43},
    {Species.Meowstic, (44, 0..1)},
    {Species.Litleo, 45},
    {Species.Pyroar, 46},
    {Species.Pancham, 47},
    {Species.Pangoro, 48},
    {Species.Trubbish, 49},
    {Species.Garbodor, 50},
    {Species.Dedenne, 51},
    {Species.Pichu, 52},
    {Species.Pikachu, 53},
    {Species.Raichu, (054, 0..1)},
    {Species.Cleffa, 55},
    {Species.Clefairy, 56},
    {Species.Clefable, 57},
    {Species.Spinarak, 58},
    {Species.Ariados, 59},
    {Species.Ekans, 60},
    {Species.Arbok, 61},
    {Species.Abra, 62},
    {Species.Kadabra, 63},
    {Species.Alakazam, 64},
    {Species.Gastly, 65},
    {Species.Haunter, 66},
    {Species.Gengar, 67},
    {Species.Venipede, 68},
    {Species.Whirlipede, 69},
    {Species.Scolipede, 70},
    {Species.Honedge, 71},
    {Species.Doublade, 72},
    {Species.Aegislash, 73},
    {Species.Bellsprout, 74},
    {Species.Weepinbell, 75},
    {Species.Victreebel, 76},
    {Species.Pansage, 77},
    {Species.Simisage, 78},
    {Species.Pansear, 79},
    {Species.Simisear, 80},
    {Species.Panpour, 81},
    {Species.Simipour, 82},
    {Species.Meditite, 83},
    {Species.Medicham, 84},
    {Species.Electrike, 85},
    {Species.Manectric, 86},
    {Species.Ralts, 87},
    {Species.Kirlia, 88},
    {Species.Gardevoir, 89},
    {Species.Gallade, 90},
    {Species.Houndour, 91},
    {Species.Houndoom, 92},
    {Species.Swablu, 93},
    {Species.Altaria, 94},
    {Species.Audino, 95},
    {Species.Spritzee, 96},
    {Species.Aromatisse, 97},
    {Species.Swirlix, 98},
    {Species.Slurpuff, 99},
    {Species.Eevee, 100},
    {Species.Vaporeon, 101},
    {Species.Jolteon, 102},
    {Species.Flareon, 103},
    {Species.Espeon, 104},
    {Species.Umbreon, 105},
    {Species.Leafeon, 106},
    {Species.Glaceon, 107},
    {Species.Sylveon, 108},
    {Species.Buneary, 109},
    {Species.Lopunny, 110},
    {Species.Shuppet, 111},
    {Species.Banette, 112},
    {Species.Vanillite, 113},
    {Species.Vanillish, 114},
    {Species.Vanilluxe, 115},
    {Species.Numel, 116},
    {Species.Camerupt, 117},
    {Species.Hippopotas, 118},
    {Species.Hippowdon, 119},
    {Species.Drilbur, 120},
    {Species.Excadrill, 121},
    {Species.Sandile, 122},
    {Species.Krokorok, 123},
    {Species.Krookodile, 124},
    {Species.Machop, 125},
    {Species.Machoke, 126},
    {Species.Machamp, 127},
    {Species.Gible, 128},
    {Species.Gabite, 129},
    {Species.Garchomp, 130},
    {Species.Carbink, 131},
    {Species.Sableye, 132},
    {Species.Mawile, 133},
    {Species.Absol, 134},
    {Species.Riolu, 135},
    {Species.Lucario, 136},
    {Species.Slowpoke, (137, 0..1)},
    {Species.Slowbro, (138, new HashSet<int>() { 0, 2 })},
    {Species.Slowking, (139, 0..1)},
    {Species.Carvanha, 140},
    {Species.Sharpedo, 141},
    {Species.Tynamo, 142},
    {Species.Eelektrik, 143},
    {Species.Eelektross, 144},
    {Species.Dratini, 145},
    {Species.Dragonair, 146},
    {Species.Dragonite, 147},
    {Species.Bulbasaur, 148},
    {Species.Ivysaur, 149},
    {Species.Venusaur, 150},
    {Species.Charmander, 151},
    {Species.Charmeleon, 152},
    {Species.Charizard, 153},
    {Species.Squirtle, 154},
    {Species.Wartortle, 155},
    {Species.Blastoise, 156},
    {Species.Stunfisk, (157, 0..1)},
    {Species.Furfrou, (158, 0..9)},
    {Species.Inkay, 159},
    {Species.Malamar, 160},
    {Species.Skrelp, 161},
    {Species.Dragalge, 162},
    {Species.Clauncher, 163},
    {Species.Clawitzer, 164},
    {Species.Goomy, 165},
    {Species.Sliggoo, (166, 0..1)},
    {Species.Goodra, (167, 0..1)},
    {Species.Delibird, 168},
    {Species.Snorunt, 169},
    {Species.Glalie, 170},
    {Species.Froslass, 171},
    {Species.Snover, 172},
    {Species.Abomasnow, 173},
    {Species.Bergmite, 174},
    {Species.Avalugg, (175, 0..1)},
    {Species.Scyther, 176},
    {Species.Scizor, 177},
    {Species.Pinsir, 178},
    {Species.Heracross, 179},
    {Species.Emolga, 180},
    {Species.Hawlucha, 181},
    {Species.Phantump, 182},
    {Species.Trevenant, 183},
    {Species.Scraggy, 184},
    {Species.Scrafty, 185},
    {Species.Noibat, 186},
    {Species.Noivern, 187},
    {Species.Klefki, 188},
    {Species.Litwick, 189},
    {Species.Lampent, 190},
    {Species.Chandelure, 191},
    {Species.Aerodactyl, 192},
    {Species.Tyrunt, 193},
    {Species.Tyrantrum, 194},
    {Species.Amaura, 195},
    {Species.Aurorus, 196},
    {Species.Onix, 197},
    {Species.Steelix, 198},
    {Species.Aron, 199},
    {Species.Lairon, 200},
    {Species.Aggron, 201},
    {Species.Helioptile, 202},
    {Species.Heliolisk, 203},
    {Species.Pumpkaboo, (204, 0..3)},
    {Species.Gourgeist, (205, 0..3)},
    {Species.Larvitar, 206},
    {Species.Pupitar, 207},
    {Species.Tyranitar, 208},
    {Species.Froakie, 209},
    {Species.Frogadier, 210},
    {Species.Greninja, 211},
    {Species.Falinks, 212},
    {Species.Chespin, 213},
    {Species.Quilladin, 214},
    {Species.Chesnaught, 215},
    {Species.Skarmory, 216},
    {Species.Fennekin, 217},
    {Species.Braixen, 218},
    {Species.Delphox, 219},
    {Species.Bagon, 220},
    {Species.Shelgon, 221},
    {Species.Salamence, 222},
    {Species.Kangaskhan, 223},
    {Species.Drampa, 224},
    {Species.Beldum, 225},
    {Species.Metang, 226},
    {Species.Metagross, 227},
    {Species.Xerneas, 228},
    {Species.Yveltal, 229},
    {Species.Zygarde, (230, 0..3)},
    {Species.Diancie, 231},
    {Species.Mewtwo, 232}
  };

  public static Func<PKM, IComparable>[] GetLumioseDexSortFunctions() {
    return GenerateSortingFunctions(LumioseDex);
  }

}
